/**
 * What Apple's Vision read off each shipped Catchphrase drawing.
 *
 * **Generated by `npm run write-catchphrase-pack`. Do not edit by hand.**
 * Empty means it read nothing. `catchphrase-gate.test.ts` refuses any entry
 * that names its own answer, so the rule holds in `npm test` without a Mac.
 */

export const CATCHPHRASE_PICTURE_TEXT: Record<string, string> = {
  "cp-big-cheese": "",
  "cp-bite-bullet": "",
  "cp-break-ice": "",
  "cp-bull-china": "",
  "cp-cat-bag": "",
  "cp-cloud-nine": "9",
  "cp-cold-feet": "T",
  "cp-couch-potato": "000m 00B0",
  "cp-crystal-maze": "",
  "cp-dads-army": "",
  "cp-daylight-robbery": "",
  "cp-egg-face": "",
  "cp-eggshells": "",
  "cp-face-music": "",
  "cp-fools-horses": "ONLY",
  "cp-frog-throat": "",
  "cp-frying-pan": "",
  "cp-heart-sleeve": "",
  "cp-neighbours": "",
  "cp-penny-thoughts": "",
  "cp-pigs-fly": "",
  "cp-pulling-leg": "",
  "cp-same-boat": "",
  "cp-spill-beans": "",
  "cp-square-one": "",
  "cp-storm-teacup": "",
  "cp-top-dog": "",
  "cp-two-peas": "",
  "cp-under-weather": "",
  "cp-wrong-tree": "\"s,.",
};
