/**
 * Picture-round stills. Answers live here so the write script can seal and
 * vault them. Not imported by the app bundle.
 */
import type { StillSpec } from '../src/questions/stills-source';

export const STILL_SPECS: readonly StillSpec[] = [
  {
    slug: 'hay-wain',
    prompt: 'Which painting is this?',
    correct: 'The Hay Wain',
    incorrect: ['The Cornfield', 'Flatford Mill', 'The Leaping Horse'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'John_Constable_The_Hay_Wain.jpg' },
    attribution:
      'John Constable, The Hay Wain (1821). Wikimedia Commons, PD-Art (Constable d. 1837).',
    jigsaw: true,
  },
  {
    slug: 'temeraire',
    prompt: 'Which painting is this?',
    correct: 'The Fighting Temeraire',
    incorrect: ['Rain, Steam and Speed', 'The Slave Ship', 'Dido Building Carthage'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg' },
    attribution:
      'J. M. W. Turner, The Fighting Temeraire (1839). Wikimedia Commons, PD-Art (Turner d. 1851).',
    jigsaw: true,
  },
  {
    slug: 'starry-night',
    prompt: 'Which painting is this?',
    correct: 'The Starry Night',
    incorrect: ['Café Terrace at Night', 'Wheatfield with Crows', 'Irises'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg' },
    attribution:
      'Vincent van Gogh, The Starry Night (1889). Wikimedia Commons, PD-Art (d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'sunflowers',
    prompt: 'Which painting is this?',
    correct: 'Sunflowers',
    incorrect: ['Irises', 'Almond Blossom', 'The Night Café'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Vincent_van_Gogh_-_Sunflowers_(1888,_National_Gallery_London).jpg',
    },
    attribution:
      'Vincent van Gogh, Sunflowers (1888, National Gallery, London). Wikimedia Commons, PD-Art — not the Gallery picture-library JPEG.',
    jigsaw: true,
  },
  {
    slug: 'great-wave',
    prompt: 'Which print is this?',
    correct: 'The Great Wave off Kanagawa',
    incorrect: ['Fine Wind, Clear Morning', 'Thunderstorm Beneath the Summit', 'Kajikazawa in Kai Province'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'The_Great_Wave_off_Kanagawa.jpg' },
    attribution:
      'Katsushika Hokusai, The Great Wave off Kanagawa (c. 1831). Wikimedia Commons, PD-Art (d. 1849).',
    jigsaw: true,
  },
  {
    slug: 'scream',
    prompt: 'Which painting is this?',
    correct: 'The Scream',
    incorrect: ['Madonna', 'The Dance of Life', 'Anxiety'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg',
    },
    attribution:
      'Edvard Munch, The Scream (1893). Wikimedia Commons, PD-Art (Munch d. 1944). Not a Munchmuseet NC photograph.',
    jigsaw: true,
  },
  {
    slug: 'salisbury',
    prompt: 'Which painting is this?',
    correct: 'Salisbury Cathedral from the Bishop’s Grounds',
    incorrect: ['The Hay Wain', 'Wivenhoe Park', 'Salisbury Cathedral from the Meadows'],
    difficulty: 'medium',
    source: { kind: 'met', objectId: 435922 },
    attribution:
      'John Constable, Salisbury Cathedral from the Bishop’s Grounds (c. 1825). The Met, 50.145.8, CC0.',
  },
  {
    slug: 'stonehenge',
    prompt: 'What is this monument?',
    correct: 'Stonehenge',
    incorrect: ['Avebury', 'Callanish', 'Carnac'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Stonehenge2007_07_30.jpg' },
    credit: 'Photo: garethwiscombe, CC BY 2.0',
    attribution:
      'Stonehenge, photograph by garethwiscombe, 30 July 2007. Wikimedia Commons, CC BY 2.0.',
    jigsaw: true,
  },
  {
    slug: 'blue-marble',
    prompt: 'Which mission took this photograph?',
    correct: 'Apollo 17',
    incorrect: ['Apollo 8', 'Apollo 11', 'Gemini 4'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'The_Earth_seen_from_Apollo_17_(AS17-148-22727).jpg' },
    attribution:
      'NASA AS17-148-22727, The Blue Marble, 7 December 1972. PD-USGov. Credit NASA. No agency logo.',
    jigsaw: true,
  },
  {
    slug: 'cornfield',
    prompt: 'Which painting is this?',
    correct: 'The Cornfield',
    incorrect: ['The Hay Wain', 'The Leaping Horse', 'Dedham Vale'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Constable_-_The_Cornfield.jpg' },
    attribution:
      'John Constable, The Cornfield (1826). Wikimedia Commons, PD-Art (Constable d. 1837).',
    jigsaw: true,
  },
  {
    slug: 'rain-steam-speed',
    prompt: 'Which painting is this?',
    correct: 'Rain, Steam and Speed',
    incorrect: ['The Fighting Temeraire', 'Snow Storm: Steam-Boat off a Harbour’s Mouth', 'The Slave Ship'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Turner_-_Rain,_Steam_and_Speed_-_National_Gallery_file.jpg' },
    attribution:
      'J. M. W. Turner, Rain, Steam and Speed – The Great Western Railway (1844). Wikimedia Commons, PD-Art — not the Gallery picture-library JPEG.',
    jigsaw: true,
  },
  {
    slug: 'impression-sunrise',
    prompt: 'Which painting is this?',
    correct: 'Impression, Sunrise',
    incorrect: ['Water Lilies', 'Woman with a Parasol', 'The Magpie'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Monet_-_Impression,_Sunrise.jpg' },
    attribution:
      'Claude Monet, Impression, Sunrise (1872). Wikimedia Commons, PD-Art (Monet d. 1926).',
    jigsaw: true,
  },
  {
    slug: 'houses-of-parliament',
    prompt: 'Which painting is this?',
    correct: 'Houses of Parliament, Sunset',
    incorrect: ['Impression, Sunrise', 'The Thames below Westminster', 'Waterloo Bridge'],
    difficulty: 'medium',
    source: {
      kind: 'commons',
      file: 'Claude_Monet,_Houses_of_Parliament,_London,_1900-1903,_1933.1164,_Art_Institute_of_Chicago.jpg',
    },
    attribution:
      'Claude Monet, Houses of Parliament, Sunset (1900–1903). Art Institute of Chicago 1933.1164, Wikimedia Commons, CC0.',
    jigsaw: true,
  },
  {
    slug: 'water-lily-bridge',
    prompt: 'Which painting is this?',
    correct: 'Bridge over a Pond of Water Lilies',
    incorrect: ['Impression, Sunrise', 'The Japanese Footbridge', 'Water Lilies and Japanese Bridge'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Bridge_over_a_Pond_of_Water_Lilies_MET_DT1854.jpg' },
    attribution:
      'Claude Monet, Bridge over a Pond of Water Lilies (1899). The Met, 29.100.113, Wikimedia Commons, CC0.',
    jigsaw: true,
  },
  {
    slug: 'bar-folies-bergere',
    prompt: 'Which painting is this?',
    correct: 'A Bar at the Folies-Bergère',
    incorrect: ['Olympia', 'Luncheon on the Grass', 'The Railway'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Edouard_Manet,_A_Bar_at_the_Folies-Bergère.jpg' },
    attribution:
      'Édouard Manet, A Bar at the Folies-Bergère (1882). Wikimedia Commons, PD-Art (Manet d. 1883).',
    jigsaw: true,
  },
  {
    slug: 'ballet-class',
    prompt: 'Which painting is this?',
    correct: 'The Ballet Class',
    incorrect: ['L’Absinthe', 'The Dance Lesson', 'Miss La La at the Cirque Fernando'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Edgar_Degas_-_The_Ballet_Class_-_Google_Art_Project.jpg' },
    attribution:
      'Edgar Degas, The Ballet Class (c. 1874). Wikimedia Commons, PD-Art (Degas d. 1917).',
    jigsaw: true,
  },
  {
    slug: 'mont-sainte-victoire',
    prompt: 'Which painting is this?',
    correct: 'Mont Sainte-Victoire',
    incorrect: ['The Card Players', 'The Bathers', 'Still Life with Apples'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Mont_Sainte-Victoire_with_Large_Pine,_by_Paul_Cézanne.jpg' },
    attribution:
      'Paul Cézanne, Mont Sainte-Victoire with Large Pine (c. 1887). Wikimedia Commons, PD-Art (Cézanne d. 1906).',
    jigsaw: true,
  },
  {
    slug: 'card-players',
    prompt: 'Which painting is this?',
    correct: 'The Card Players',
    incorrect: ['Mont Sainte-Victoire', 'The Bathers', 'The House of the Hanged Man'],
    difficulty: 'medium',
    source: {
      kind: 'commons',
      file: 'Paul_Cézanne,_1892-95,_Les_joueurs_de_carte_(The_Card_Players),_60_x_73_cm,_oil_on_canvas,_Courtauld_Institute_of_Art,_London.jpg',
    },
    attribution:
      'Paul Cézanne, The Card Players (c. 1892–95, Courtauld). Wikimedia Commons, PD-Art (Cézanne d. 1906).',
    jigsaw: true,
  },
  {
    slug: 'grande-jatte',
    prompt: 'Which painting is this?',
    correct: 'A Sunday Afternoon on the Island of La Grande Jatte',
    incorrect: ['Bathers at Asnières', 'Circus Sideshow', 'The Circus'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg' },
    attribution:
      'Georges Seurat, A Sunday Afternoon on the Island of La Grande Jatte (1884–86). Wikimedia Commons, PD-Art (Seurat d. 1891).',
    jigsaw: true,
  },
  {
    slug: 'the-kiss',
    prompt: 'Which painting is this?',
    correct: 'The Kiss',
    incorrect: ['Portrait of Adele Bloch-Bauer I', 'Judith and the Head of Holofernes', 'Danaë'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg' },
    attribution:
      'Gustav Klimt, The Kiss (1907–08). Wikimedia Commons, PD-Art (Klimt d. 1918).',
    jigsaw: true,
  },
  {
    slug: 'american-gothic',
    prompt: 'Which painting is this?',
    correct: 'American Gothic',
    incorrect: ['Nighthawks', 'Christina’s World', 'The Midnight Ride of Paul Revere'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg' },
    attribution:
      'Grant Wood, American Gothic (1930). Wikimedia Commons, PD-Art (Wood d. 1942; UK PD 1 Jan 2013, US PD 1 Jan 2026).',
    jigsaw: true,
  },
  {
    slug: 'blue-boy',
    prompt: 'Which painting is this?',
    correct: 'The Blue Boy',
    incorrect: ['Mr and Mrs Andrews', 'The Pink Boy', 'The Honourable Mrs Graham'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Thomas_Gainsborough_-_The_Blue_Boy_(c._1770).jpg' },
    attribution:
      'Thomas Gainsborough, The Blue Boy (c. 1770). Wikimedia Commons, PD-Art (Gainsborough d. 1788).',
    jigsaw: true,
  },
  {
    slug: 'mr-mrs-andrews',
    prompt: 'Which painting is this?',
    correct: 'Mr and Mrs Andrews',
    incorrect: ['The Blue Boy', 'Mr and Mrs William Hallett', 'The Morning Walk'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Thomas_Gainsborough_-_Mr_and_Mrs_Andrews.jpg' },
    attribution:
      'Thomas Gainsborough, Mr and Mrs Andrews (c. 1750). Wikimedia Commons, PD-Art (Gainsborough d. 1788).',
    jigsaw: true,
  },
  {
    slug: 'canaletto-grand-canal',
    prompt: 'Which painting is this?',
    correct: 'Entrance to the Grand Canal, Venice',
    incorrect: ['The Stonemason’s Yard', 'The Basin of San Marco on Ascension Day', 'London: Westminster Bridge'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Canaletto_Entrance_to_the_Grand_Canal_Venice.jpg' },
    attribution:
      'Canaletto, Entrance to the Grand Canal, Venice. Wikimedia Commons, PD-Art (Canaletto d. 1768).',
    jigsaw: true,
  },
  {
    slug: 'red-fuji',
    prompt: 'Which print is this?',
    correct: 'Fine Wind, Clear Morning',
    incorrect: ['The Great Wave off Kanagawa', 'Thunderstorm Beneath the Summit', 'Kajikazawa in Kai Province'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Red_Fuji_southern_wind_clear_morning.jpg' },
    attribution:
      'Katsushika Hokusai, Fine Wind, Clear Morning (Red Fuji, c. 1830–32). Wikimedia Commons, PD-Art (d. 1849).',
    jigsaw: true,
  },
  {
    slug: 'earthrise',
    prompt: 'Which mission took this photograph?',
    correct: 'Apollo 8',
    incorrect: ['Apollo 11', 'Apollo 17', 'Gemini 8'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'NASA-Apollo8-Dec24-Earthrise.jpg' },
    attribution:
      'NASA AS8-14-2383, Earthrise, 24 December 1968. PD-USGov. Credit NASA / Bill Anders. No agency logo.',
    jigsaw: true,
  },
  {
    slug: 'saturn-equinox',
    prompt: 'Which spacecraft took this photograph?',
    correct: 'Cassini',
    incorrect: ['Voyager 1', 'Pioneer 11', 'Juno'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Saturn_during_Equinox.jpg' },
    attribution:
      'NASA / JPL / Space Science Institute, Saturn during equinox, 2009. PD-USGov. Credit NASA. No agency logo.',
    jigsaw: true,
  },
  {
    slug: 'pillars-of-creation',
    prompt: 'Which telescope took this photograph?',
    correct: 'Hubble Space Telescope',
    incorrect: ['James Webb Space Telescope', 'Spitzer Space Telescope', 'Chandra X-ray Observatory'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Pillars_of_creation_2014_HST_WFC3-UVIS_full-res.jpg' },
    attribution:
      'NASA / ESA / Hubble Heritage, Pillars of Creation (2014 revisit). PD-USGov. Credit NASA. No agency logo.',
    jigsaw: true,
  },
  {
    slug: 'birth-of-venus',
    prompt: 'Which painting is this?',
    correct: 'The Birth of Venus',
    incorrect: ['Primavera', 'Venus and Mars', 'The Birth of Bacchus'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
    },
    attribution:
      'Sandro Botticelli, The Birth of Venus (c. 1485). Wikimedia Commons, PD-Art.',
    jigsaw: true,
  },
  {
    slug: 'night-watch',
    prompt: 'Which painting is this?',
    correct: 'The Night Watch',
    incorrect: ['The Anatomy Lesson of Dr Nicolaes Tulp', 'The Jewish Bride', 'The Syndics'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'The_Nightwatch_by_Rembrandt.jpg' },
    attribution:
      'Rembrandt, The Night Watch (1642). Wikimedia Commons, PD-Art (Rembrandt d. 1669).',
    jigsaw: true,
  },
  {
    slug: 'liberty-leading',
    prompt: 'Which painting is this?',
    correct: 'Liberty Leading the People',
    incorrect: ['The Raft of the Medusa', 'The Death of Sardanapalus', 'Massacre at Chios'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Eugène_Delacroix_-_Le_28_Juillet._La_Liberté_guidant_le_peuple.jpg',
    },
    attribution:
      'Eugène Delacroix, Liberty Leading the People (1830). Wikimedia Commons, PD-Art (Delacroix d. 1863).',
    jigsaw: true,
  },
  {
    slug: 'hunters-in-the-snow',
    prompt: 'Which painting is this?',
    correct: 'The Hunters in the Snow',
    incorrect: ['The Harvesters', 'Netherlandish Proverbs', 'The Tower of Babel'],
    difficulty: 'medium',
    source: {
      kind: 'commons',
      file: 'Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_(Winter)_-_Google_Art_Project.jpg',
    },
    attribution:
      'Pieter Bruegel the Elder, The Hunters in the Snow (1565). Wikimedia Commons, PD-Art.',
    jigsaw: true,
  },
  {
    slug: 'wanderer',
    prompt: 'Which painting is this?',
    correct: 'Wanderer above the Sea of Fog',
    incorrect: ['The Monk by the Sea', 'Chalk Cliffs on Rügen', 'The Sea of Ice'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg' },
    attribution:
      'Caspar David Friedrich, Wanderer above the Sea of Fog (c. 1818). Wikimedia Commons, PD-Art (Friedrich d. 1840).',
    jigsaw: true,
  },
  {
    slug: 'whistlers-mother',
    prompt: 'Which painting is this?',
    correct: 'Whistler’s Mother',
    incorrect: ['Symphony in White, No. 1', 'Nocturne in Black and Gold', 'Harmony in Pink and Grey'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Whistlers_Mother_high_res.jpg' },
    attribution:
      'James McNeill Whistler, Arrangement in Grey and Black No. 1 (Whistler’s Mother, 1871). Wikimedia Commons, PD-Art (Whistler d. 1903).',
    jigsaw: true,
  },
  {
    slug: 'view-of-delft',
    prompt: 'Which painting is this?',
    correct: 'View of Delft',
    incorrect: ['The Little Street', 'Girl with a Pearl Earring', 'The Milkmaid'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Vermeer-view-of-delft.jpg' },
    attribution:
      'Johannes Vermeer, View of Delft (c. 1661). Wikimedia Commons, PD-Art (Vermeer d. 1675).',
    jigsaw: true,
  },
  {
    slug: 'las-meninas',
    prompt: 'Which painting is this?',
    correct: 'Las Meninas',
    incorrect: ['The Surrender of Breda', 'The Spinners', 'Pope Innocent X'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg',
    },
    attribution:
      'Diego Velázquez, Las Meninas (1656). Wikimedia Commons, PD-Art (Velázquez d. 1660).',
    jigsaw: true,
  },
  {
    slug: 'third-of-may',
    prompt: 'Which painting is this?',
    correct: 'The Third of May 1808',
    incorrect: ['The Second of May 1808', 'Saturn Devouring His Son', 'The Family of Charles IV'],
    difficulty: 'medium',
    source: {
      kind: 'commons',
      file: 'El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_in_Google_Earth.jpg',
    },
    attribution:
      'Francisco Goya, The Third of May 1808 (1814). Wikimedia Commons, PD-Art (Goya d. 1828).',
    jigsaw: true,
  },
  {
    slug: 'raft-of-the-medusa',
    prompt: 'Which painting is this?',
    correct: 'The Raft of the Medusa',
    incorrect: ['Liberty Leading the People', 'The Charging Chasseur', 'The Death of Sardanapalus'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Théodore_Géricault_-_The_Raft_of_the_Medusa_-_WGA08630.jpg' },
    attribution:
      'Théodore Géricault, The Raft of the Medusa (1818–19). Wikimedia Commons, PD-Art (Géricault d. 1824).',
    jigsaw: true,
  },
  {
    slug: 'surprised-tiger',
    prompt: 'Which painting is this?',
    correct: 'Tiger in a Tropical Storm',
    incorrect: ['The Sleeping Gypsy', 'The Dream', 'The Hungry Lion Throws Itself on the Antelope'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Surprised-Rousseau.jpg' },
    attribution:
      'Henri Rousseau, Tiger in a Tropical Storm (Surprised!, 1891). Wikimedia Commons, PD-Art (Rousseau d. 1910).',
    jigsaw: true,
  },
  {
    slug: 'boating-party',
    prompt: 'Which painting is this?',
    correct: 'Luncheon of the Boating Party',
    incorrect: ['Dance at Le Moulin de la Galette', 'The Swing', 'Girls at the Piano'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg',
    },
    attribution:
      'Pierre-Auguste Renoir, Luncheon of the Boating Party (1880–81). Wikimedia Commons, PD-Art (Renoir d. 1919).',
    jigsaw: true,
  },
  {
    slug: 'whistlejacket',
    prompt: 'Which painting is this?',
    correct: 'Whistlejacket',
    incorrect: ['Mares and Foals', 'The Hambletonian', 'A Lion Attacking a Horse'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Whistlejacket_by_George_Stubbs.jpg' },
    attribution:
      'George Stubbs, Whistlejacket (c. 1762). Wikimedia Commons, PD-Art (Stubbs d. 1806).',
    jigsaw: true,
  },
  {
    slug: 'ambassadors',
    prompt: 'Which painting is this?',
    correct: 'The Ambassadors',
    incorrect: ['The Arnolfini Portrait', 'Christina of Denmark', 'Sir Thomas More'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg',
    },
    attribution:
      'Hans Holbein the Younger, The Ambassadors (1533). Wikimedia Commons, PD-Art.',
    jigsaw: true,
  },
  {
    slug: 'flaming-june',
    prompt: 'Which painting is this?',
    correct: 'Flaming June',
    incorrect: ['The Bath of Psyche', 'Cimabue’s Celebrated Madonna', 'The Garden of the Hesperides'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Flaming_June,_by_Frederic_Lord_Leighton_(1830-1896).jpg' },
    attribution:
      'Frederic Leighton, Flaming June (1895). Wikimedia Commons, PD-Art (Leighton d. 1896). Not a Tate photograph.',
    jigsaw: true,
  },
  {
    slug: 'arnolfini',
    prompt: 'Which painting is this?',
    correct: 'The Arnolfini Portrait',
    incorrect: ['The Ambassadors', 'Portrait of a Man in a Red Turban', 'Madonna of Chancellor Rolin'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Van_Eyck_-_Arnolfini_Portrait.jpg' },
    attribution:
      'Jan van Eyck, The Arnolfini Portrait (1434). Wikimedia Commons, PD-Art.',
    jigsaw: true,
  },
  {
    slug: 'washington-crossing',
    prompt: 'Which painting is this?',
    correct: 'Washington Crossing the Delaware',
    incorrect: ['The Declaration of Independence', 'Watson and the Shark', 'The Course of Empire'],
    difficulty: 'easy',
    source: {
      kind: 'commons',
      file: 'Washington_Crossing_the_Delaware_by_Emanuel_Leutze,_MMA-NYC,_1851.jpg',
    },
    attribution:
      'Emanuel Leutze, Washington Crossing the Delaware (1851). Wikimedia Commons, PD-Art (Leutze d. 1868).',
    jigsaw: true,
  },
  {
    slug: 'death-of-socrates',
    prompt: 'Which painting is this?',
    correct: 'The Death of Socrates',
    incorrect: ['The Oath of the Horatii', 'The Intervention of the Sabine Women', 'Napoleon Crossing the Alps'],
    difficulty: 'medium',
    source: { kind: 'met', objectId: 436105 },
    attribution:
      'Jacques-Louis David, The Death of Socrates (1787). The Met, 31.45, CC0.',
    jigsaw: true,
  },
  {
    slug: 'madame-x',
    prompt: 'Which painting is this?',
    correct: 'Madame X',
    incorrect: ['Portrait of Madame Monet', 'Lady Agnew of Lochnaw', 'Portrait of Madame Récamier'],
    difficulty: 'medium',
    source: { kind: 'met', objectId: 12127 },
    attribution:
      'John Singer Sargent, Madame X (1883–84). The Met, 16.53, CC0. Sargent d. 1925.',
    jigsaw: true,
  },
  {
    slug: 'the-harvesters',
    prompt: 'Which painting is this?',
    correct: 'The Harvesters',
    incorrect: ['The Hunters in the Snow', 'The Peasant Wedding', 'The Corn Harvest'],
    difficulty: 'medium',
    source: { kind: 'met', objectId: 435809 },
    attribution:
      'Pieter Bruegel the Elder, The Harvesters (1565). The Met, 19.164, CC0.',
    jigsaw: true,
  },
  {
    slug: 'gulf-stream',
    prompt: 'Which painting is this?',
    correct: 'The Gulf Stream',
    incorrect: ['Breezing Up', 'Snap the Whip', 'The Fog Warning'],
    difficulty: 'medium',
    source: { kind: 'met', objectId: 11122 },
    attribution:
      'Winslow Homer, The Gulf Stream (1899). The Met, 06.1234, CC0. Homer d. 1910.',
    jigsaw: true,
  },
  // Third batch, 26 September 2026: the pack had no hard questions at all, and 24 fresh.
  {
    slug: 'mona-lisa',
    prompt: 'Which painting is this?',
    correct: 'Mona Lisa',
    incorrect: ['Lady with an Ermine', 'La Belle Ferronnière', 'Ginevra de’ Benci'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg' },
    attribution:
      'Leonardo da Vinci, Mona Lisa (c. 1503–1519). Wikimedia Commons, PD-Art (Leonardo d. 1519).',
    jigsaw: true,
  },
  {
    slug: 'last-supper',
    prompt: 'Which painting is this?',
    correct: 'The Last Supper',
    incorrect: ['The Supper at Emmaus', 'The Wedding at Cana', 'The School of Athens'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Leonardo da Vinci (1452-1519) - The Last Supper (1495-1498).jpg' },
    attribution:
      'Leonardo da Vinci, The Last Supper (1495–1498). Wikimedia Commons, PD-Art (Leonardo d. 1519).',
    jigsaw: true,
  },
  {
    slug: 'lady-with-an-ermine',
    prompt: 'Which painting is this?',
    correct: 'Lady with an Ermine',
    incorrect: ['Mona Lisa', 'Ginevra de’ Benci', 'Portrait of a Musician'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Lady with an Ermine - Leonardo da Vinci - Google Art Project.jpg' },
    attribution:
      'Leonardo da Vinci, Lady with an Ermine (c. 1489–1491). Wikimedia Commons, PD-Art (Leonardo d. 1519).',
    jigsaw: true,
  },
  {
    slug: 'creation-of-adam',
    prompt: 'Which painting is this?',
    correct: 'The Creation of Adam',
    incorrect: ['The Last Judgment', 'The School of Athens', 'The Fall of Man'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Michelangelo - Creation of Adam (cropped).jpg' },
    attribution:
      'Michelangelo, The Creation of Adam (c. 1512). Wikimedia Commons, PD-Art (Michelangelo d. 1564).',
    jigsaw: true,
  },
  {
    slug: 'school-of-athens',
    prompt: 'Which painting is this?',
    correct: 'The School of Athens',
    incorrect: ['The Last Supper', 'The Disputation of the Holy Sacrament', 'The Marriage of the Virgin'],
    difficulty: 'medium',
    source: { kind: 'commons', file: '"The School of Athens" by Raffaello Sanzio da Urbino.jpg' },
    attribution:
      'Raphael, The School of Athens (1509–1511). Wikimedia Commons, PD-Art (Raphael d. 1520).',
    jigsaw: true,
  },
  {
    slug: 'girl-pearl-earring',
    prompt: 'Which painting is this?',
    correct: 'Girl with a Pearl Earring',
    incorrect: ['The Milkmaid', 'Woman Reading a Letter', 'The Girl with a Red Hat'],
    difficulty: 'easy',
    source: { kind: 'commons', file: '1665 Girl with a Pearl Earring.jpg' },
    attribution:
      'Johannes Vermeer, Girl with a Pearl Earring (c. 1665). Wikimedia Commons, PD-Art (Vermeer d. 1675).',
    jigsaw: true,
  },
  {
    slug: 'the-milkmaid',
    prompt: 'Which painting is this?',
    correct: 'The Milkmaid',
    incorrect: ['Girl with a Pearl Earring', 'The Lacemaker', 'Woman Holding a Balance'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Johannes Vermeer - Het melkmeisje - Google Art Project.jpg' },
    attribution:
      'Johannes Vermeer, The Milkmaid (c. 1658). Wikimedia Commons, PD-Art (Vermeer d. 1675).',
    jigsaw: true,
  },
  {
    slug: 'primavera',
    prompt: 'Which painting is this?',
    correct: 'Primavera',
    incorrect: ['The Birth of Venus', 'Venus and Mars', 'The Calumny of Apelles'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Botticelli-primavera.jpg' },
    attribution:
      'Sandro Botticelli, Primavera (c. 1480). Wikimedia Commons, PD-Art (Botticelli d. 1510).',
    jigsaw: true,
  },
  {
    slug: 'tower-of-babel',
    prompt: 'Which painting is this?',
    correct: 'The Tower of Babel',
    incorrect: ['The Hunters in the Snow', 'Netherlandish Proverbs', 'The Triumph of Death'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Pieter Bruegel the Elder - The Tower of Babel (Vienna) - Google Art Project - edited.jpg' },
    attribution:
      'Pieter Bruegel the Elder, The Tower of Babel (1563). Wikimedia Commons, PD-Art (Elder d. 1569).',
    jigsaw: true,
  },
  {
    slug: 'netherlandish-proverbs',
    prompt: 'Which painting is this?',
    correct: 'Netherlandish Proverbs',
    incorrect: ['The Fight Between Carnival and Lent', 'Children’s Games', 'The Tower of Babel'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Pieter Brueghel the Elder - The Dutch Proverbs - Google Art Project.jpg' },
    attribution:
      'Pieter Bruegel the Elder, Netherlandish Proverbs (1559). Wikimedia Commons, PD-Art (Elder d. 1569).',
    jigsaw: true,
  },
  {
    slug: 'anatomy-lesson',
    prompt: 'Which painting is this?',
    correct: 'The Anatomy Lesson of Dr Nicolaes Tulp',
    incorrect: ['The Night Watch', 'The Syndics of the Drapers’ Guild', 'The Jewish Bride'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Rembrandt - The Anatomy Lesson of Dr Nicolaes Tulp.jpg' },
    attribution:
      'Rembrandt, The Anatomy Lesson of Dr Nicolaes Tulp (1632). Wikimedia Commons, PD-Art (Rembrandt d. 1669).',
    jigsaw: true,
  },
  {
    slug: 'laughing-cavalier',
    prompt: 'Which painting is this?',
    correct: 'The Laughing Cavalier',
    incorrect: ['The Night Watch', 'The Merry Drinker', 'Portrait of a Man with a Glove'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Frans Hals – The Laughing Cavalier.jpg' },
    attribution:
      'Frans Hals, The Laughing Cavalier (1624). Wikimedia Commons, PD-Art (Hals d. 1666).',
    jigsaw: true,
  },
  {
    slug: 'supper-at-emmaus',
    prompt: 'Which painting is this?',
    correct: 'The Supper at Emmaus',
    incorrect: ['The Calling of Saint Matthew', 'The Conversion of Saint Paul', 'The Entombment of Christ'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Supper at Emmaus-Caravaggio (1601).jpg' },
    attribution:
      'Caravaggio, The Supper at Emmaus (1601). Wikimedia Commons, PD-Art (Caravaggio d. 1610).',
    jigsaw: true,
  },
  {
    slug: 'calling-of-saint-matthew',
    prompt: 'Which painting is this?',
    correct: 'The Calling of Saint Matthew',
    incorrect: ['The Supper at Emmaus', 'The Entombment of Christ', 'The Conversion of Saint Paul'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'The Calling of Saint Matthew-Caravaggo (1599-1600).jpg' },
    attribution:
      'Caravaggio, The Calling of Saint Matthew (1599–1600). Wikimedia Commons, PD-Art (Caravaggio d. 1610).',
    jigsaw: true,
  },
  {
    slug: 'hannibal-snowstorm',
    prompt: 'Which painting is this?',
    correct: 'Snow Storm: Hannibal and his Army Crossing the Alps',
    incorrect: ['Rain, Steam and Speed', 'The Fighting Temeraire', 'The Slave Ship'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Joseph Mallord William Turner - Snow Storm, Hannibal and his Army Crossing the Alps - WGA23167.jpg' },
    attribution:
      'J. M. W. Turner, Snow Storm: Hannibal and his Army Crossing the Alps (1812). Wikimedia Commons, PD-Art (Turner d. 1851).',
    jigsaw: true,
  },
  {
    slug: 'burning-parliament',
    prompt: 'Which painting is this?',
    correct: 'The Burning of the Houses of Lords and Commons',
    incorrect: ['Rain, Steam and Speed', 'Snow Storm: Hannibal and his Army Crossing the Alps', 'The Fighting Temeraire'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Joseph Mallord William Turner, English - The Burning of the Houses of Lords and Commons, October 16, 1834 - Google Art Project.jpg' },
    attribution:
      'J. M. W. Turner, The Burning of the Houses of Lords and Commons (1834). Wikimedia Commons, PD-Art (Turner d. 1851).',
    jigsaw: true,
  },
  {
    slug: 'ophelia',
    prompt: 'Which painting is this?',
    correct: 'Ophelia',
    incorrect: ['The Lady of Shalott', 'Proserpine', 'Flaming June'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'John Everett Millais - Ophelia - Google Art Project.jpg' },
    attribution:
      'John Everett Millais, Ophelia (1851–1852). Wikimedia Commons, PD-Art (Millais d. 1896).',
    jigsaw: true,
  },
  {
    slug: 'lady-of-shalott',
    prompt: 'Which painting is this?',
    correct: 'The Lady of Shalott',
    incorrect: ['Ophelia', 'Hylas and the Nymphs', 'Proserpine'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'John William Waterhouse - The Lady of Shalott - Google Art Project.jpg' },
    attribution:
      'John William Waterhouse, The Lady of Shalott (1888). Wikimedia Commons, PD-Art (Waterhouse d. 1917).',
    jigsaw: true,
  },
  {
    slug: 'henry-viii',
    prompt: 'Which painting is this?',
    correct: 'Portrait of Henry VIII',
    incorrect: ['Portrait of Thomas More', 'Portrait of Anne of Cleves', 'The Ambassadors'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'After Hans Holbein the Younger - Portrait of Henry VIII - Google Art Project.jpg' },
    attribution:
      'After Hans Holbein the Younger, Portrait of Henry VIII (c. 1537–1547). Wikimedia Commons, PD-Art (Holbein d. 1543).',
    jigsaw: true,
  },
  {
    slug: 'armada-portrait',
    prompt: 'Which painting is this?',
    correct: 'The Armada Portrait',
    incorrect: ['The Ditchley Portrait', 'The Rainbow Portrait', 'Portrait of Henry VIII'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Elizabeth I Armada Portrait British School.jpg' },
    attribution:
      'Unknown English artist, The Armada Portrait (c. 1588). Wikimedia Commons, PD-Art.',
    jigsaw: true,
  },
  {
    slug: 'bird-in-the-air-pump',
    prompt: 'Which painting is this?',
    correct: 'An Experiment on a Bird in the Air Pump',
    incorrect: ['A Philosopher Lecturing on the Orrery', 'The Alchemist', 'Mr and Mrs Andrews'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'An Experiment on a Bird in an Air Pump by Joseph Wright of Derby, 1768.jpg' },
    attribution:
      'Joseph Wright of Derby, An Experiment on a Bird in the Air Pump (1768). Wikimedia Commons, PD-Art (Derby d. 1797).',
    jigsaw: true,
  },
  {
    slug: 'nocturne-black-gold',
    prompt: 'Which painting is this?',
    correct: 'Nocturne in Black and Gold – The Falling Rocket',
    incorrect: ['Whistler’s Mother', 'Nocturne: Blue and Gold – Old Battersea Bridge', 'Symphony in White, No. 1'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Whistler-Nocturne in black and gold.jpg' },
    attribution:
      'James McNeill Whistler, Nocturne in Black and Gold – The Falling Rocket (1875). Wikimedia Commons, PD-Art (Whistler d. 1903).',
    jigsaw: true,
  },
  {
    slug: 'carnation-lily',
    prompt: 'Which painting is this?',
    correct: 'Carnation, Lily, Lily, Rose',
    incorrect: ['Madame X', 'Gassed', 'El Jaleo'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'John Singer Sargent - Carnation, Lily, Lily, Rose - Google Art Project.jpg' },
    attribution:
      'John Singer Sargent, Carnation, Lily, Lily, Rose (1885–1886). Wikimedia Commons, PD-Art (Sargent d. 1925).',
    jigsaw: true,
  },
  {
    slug: 'sleeping-gypsy',
    prompt: 'Which painting is this?',
    correct: 'The Sleeping Gypsy',
    incorrect: ['Tiger in a Tropical Storm', 'The Dream', 'The Snake Charmer'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'La Bohémienne endormie.jpg' },
    attribution:
      'Henri Rousseau, The Sleeping Gypsy (1897). Wikimedia Commons, PD-Art (Rousseau d. 1910).',
    jigsaw: true,
  },
  {
    slug: 'tahitian-women',
    prompt: 'Which painting is this?',
    correct: 'Tahitian Women on the Beach',
    incorrect: ['Where Do We Come From? What Are We? Where Are We Going?', 'The Yellow Christ', 'Vision After the Sermon'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Paul Gauguin 056.jpg' },
    attribution:
      'Paul Gauguin, Tahitian Women on the Beach (1891). Wikimedia Commons, PD-Art (Gauguin d. 1903).',
    jigsaw: true,
  },
  {
    slug: 'at-the-moulin-rouge',
    prompt: 'Which painting is this?',
    correct: 'At the Moulin Rouge',
    incorrect: ['Bal du moulin de la Galette', 'A Bar at the Folies-Bergère', 'L’Absinthe'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Henri de Toulouse-Lautrec - At the Moulin Rouge - 1928.610 - Art Institute of Chicago.jpg' },
    attribution:
      'Henri de Toulouse-Lautrec, At the Moulin Rouge (1892–1895). Wikimedia Commons, PD-Art (Toulouse-Lautrec d. 1901).',
    jigsaw: true,
  },
  {
    slug: 'bal-du-moulin',
    prompt: 'Which painting is this?',
    correct: 'Bal du moulin de la Galette',
    incorrect: ['Luncheon of the Boating Party', 'Dance at Bougival', 'At the Moulin Rouge'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Auguste Renoir - Dance at Le Moulin de la Galette - Google Art Project.jpg' },
    attribution:
      'Pierre-Auguste Renoir, Bal du moulin de la Galette (1876). Wikimedia Commons, PD-Art (Renoir d. 1919).',
    jigsaw: true,
  },
  {
    slug: 'absinthe',
    prompt: 'Which painting is this?',
    correct: 'L’Absinthe',
    incorrect: ['The Ballet Class', 'At the Moulin Rouge', 'A Bar at the Folies-Bergère'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Edgar Degas - In a Café - Google Art Project 2.jpg' },
    attribution:
      'Edgar Degas, L’Absinthe (1875–1876). Wikimedia Commons, PD-Art (Degas d. 1917).',
    jigsaw: true,
  },
  {
    slug: 'woman-with-parasol',
    prompt: 'Which painting is this?',
    correct: 'Woman with a Parasol',
    incorrect: ['Impression, Sunrise', 'Poppy Field', 'Camille Monet on Her Deathbed'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg' },
    attribution:
      'Claude Monet, Woman with a Parasol (1875). Wikimedia Commons, PD-Art (Monet d. 1926).',
    jigsaw: true,
  },
  {
    slug: 'poppy-field',
    prompt: 'Which painting is this?',
    correct: 'Poppy Field',
    incorrect: ['Woman with a Parasol', 'Haystacks', 'Impression, Sunrise'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Claude Monet - Poppy Field - Google Art Project.jpg' },
    attribution:
      'Claude Monet, Poppy Field (1873). Wikimedia Commons, PD-Art (Monet d. 1926).',
    jigsaw: true,
  },
  {
    slug: 'haystacks',
    prompt: 'Which painting is this?',
    correct: 'Haystacks',
    incorrect: ['Poppy Field', 'Rouen Cathedral', 'Impression, Sunrise'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Claude Monet - Haystacks, end of Summer - Google Art Project.jpg' },
    attribution:
      'Claude Monet, Haystacks (1890–1891). Wikimedia Commons, PD-Art (Monet d. 1926).',
    jigsaw: true,
  },
  {
    slug: 'cafe-terrace',
    prompt: 'Which painting is this?',
    correct: 'Café Terrace at Night',
    incorrect: ['The Starry Night', 'The Night Café', 'Starry Night Over the Rhône'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Van Gogh - Terrasse des Cafés an der Place du Forum in Arles am Abend1.jpeg' },
    attribution:
      'Vincent van Gogh, Café Terrace at Night (1888). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'the-bedroom',
    prompt: 'Which painting is this?',
    correct: 'The Bedroom',
    incorrect: ['The Night Café', 'The Yellow House', 'Café Terrace at Night'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Vincent van Gogh - De slaapkamer - Google Art Project.jpg' },
    attribution:
      'Vincent van Gogh, The Bedroom (1888). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'irises',
    prompt: 'Which painting is this?',
    correct: 'Irises',
    incorrect: ['Sunflowers', 'Almond Blossoms', 'Wheatfield with Cypresses'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Irises-Vincent van Gogh.jpg' },
    attribution:
      'Vincent van Gogh, Irises (1889). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'almond-blossoms',
    prompt: 'Which painting is this?',
    correct: 'Almond Blossoms',
    incorrect: ['Irises', 'Sunflowers', 'The Starry Night'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Vincent van Gogh - Almond blossom - Google Art Project.jpg' },
    attribution:
      'Vincent van Gogh, Almond Blossoms (1890). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'bandaged-ear',
    prompt: 'Which painting is this?',
    correct: 'Self-Portrait with Bandaged Ear',
    incorrect: ['Self-Portrait with Grey Felt Hat', 'Portrait of Dr Gachet', 'The Potato Eaters'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'Vincent van Gogh - Self-portrait with bandaged ear (1889, Courtauld Institute).jpg' },
    attribution:
      'Vincent van Gogh, Self-Portrait with Bandaged Ear (1889). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'wheatfield-with-crows',
    prompt: 'Which painting is this?',
    correct: 'Wheatfield with Crows',
    incorrect: ['Wheatfield with Cypresses', 'The Sower', 'Irises'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Vincent van Gogh - Wheatfield with crows - Google Art Project.jpg' },
    attribution:
      'Vincent van Gogh, Wheatfield with Crows (1890). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'potato-eaters',
    prompt: 'Which painting is this?',
    correct: 'The Potato Eaters',
    incorrect: ['The Night Café', 'The Sower', 'The Bedroom'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'The Potato Eaters - Vincent Van Gogh.jpg' },
    attribution:
      'Vincent van Gogh, The Potato Eaters (1885). Wikimedia Commons, PD-Art (Gogh d. 1890).',
    jigsaw: true,
  },
  {
    slug: 'adele-bloch-bauer',
    prompt: 'Which painting is this?',
    correct: 'Portrait of Adele Bloch-Bauer I',
    incorrect: ['The Kiss', 'The Tree of Life', 'Judith and the Head of Holofernes'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Gustav Klimt, 1907, Adele Bloch-Bauer I, Neue Galerie New York.jpg' },
    attribution:
      'Gustav Klimt, Portrait of Adele Bloch-Bauer I (1907). Wikimedia Commons, PD-Art (Klimt d. 1918).',
    jigsaw: true,
  },
  {
    slug: 'tree-of-life-klimt',
    prompt: 'Which painting is this?',
    correct: 'The Tree of Life',
    incorrect: ['The Kiss', 'Portrait of Adele Bloch-Bauer I', 'Beethoven Frieze'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Klimt Tree of Life 1909.jpg' },
    attribution:
      'Gustav Klimt, The Tree of Life (1909). Wikimedia Commons, PD-Art (Klimt d. 1918).',
    jigsaw: true,
  },
  {
    slug: 'composition-vii',
    prompt: 'Which painting is this?',
    correct: 'Composition VII',
    incorrect: ['Yellow-Red-Blue', 'Several Circles', 'Composition VIII'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Composition VII - Wassily Kandinsky, GAC.jpg' },
    attribution:
      'Wassily Kandinsky, Composition VII (1913). Wikimedia Commons, PD-Art (Kandinsky d. 1944).',
    jigsaw: true,
  },
  {
    slug: 'mondrian-rby',
    prompt: 'Which painting is this?',
    correct: 'Composition with Red, Blue and Yellow',
    incorrect: ['Broadway Boogie-Woogie', 'Victory Boogie-Woogie', 'Composition No. 10'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Piet Mondriaan, 1930 - Mondrian Composition II in Red, Blue, and Yellow.jpg' },
    attribution:
      'Piet Mondrian, Composition with Red, Blue and Yellow (1930). Wikimedia Commons, PD-Art (Mondrian d. 1944).',
    jigsaw: true,
  },
  {
    slug: 'vertumnus',
    prompt: 'Which painting is this?',
    correct: 'Vertumnus',
    incorrect: ['Summer', 'The Librarian', 'Winter'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Vertumnus årstidernas gud målad av Giuseppe Arcimboldo 1591 - Skoklosters slott - 91503.jpg' },
    attribution:
      'Giuseppe Arcimboldo, Vertumnus (1591). Wikimedia Commons, PD-Art (Arcimboldo d. 1593).',
    jigsaw: true,
  },
  {
    slug: 'bacchus-ariadne',
    prompt: 'Which painting is this?',
    correct: 'Bacchus and Ariadne',
    incorrect: ['Venus of Urbino', 'Assumption of the Virgin', 'Diana and Actaeon'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Titian - Bacchus and Ariadne - Google Art Project.jpg' },
    attribution:
      'Titian, Bacchus and Ariadne (1520–1523). Wikimedia Commons, PD-Art (Titian d. 1576).',
    jigsaw: true,
  },
  {
    slug: 'bathers-asnieres',
    prompt: 'Which painting is this?',
    correct: 'Bathers at Asnières',
    incorrect: ['A Sunday Afternoon on the Island of La Grande Jatte', 'The Circus', 'Le Chahut'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Baigneurs a Asnieres.jpg' },
    attribution:
      'Georges Seurat, Bathers at Asnières (1884). Wikimedia Commons, PD-Art (Seurat d. 1891).',
    jigsaw: true,
  },
  {
    slug: 'the-swing',
    prompt: 'Which painting is this?',
    correct: 'The Swing',
    incorrect: ['The Reader', 'The Stolen Kiss', 'The Progress of Love'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Fragonard, The Swing.jpg' },
    attribution:
      'Jean-Honoré Fragonard, The Swing (1767). Wikimedia Commons, PD-Art (Fragonard d. 1806).',
    jigsaw: true,
  },
  {
    slug: 'the-gleaners',
    prompt: 'Which painting is this?',
    correct: 'The Gleaners',
    incorrect: ['The Angelus', 'The Sower', 'The Harvesters'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Jean-François Millet - Gleaners - Google Art Project 2.jpg' },
    attribution:
      'Jean-François Millet, The Gleaners (1857). Wikimedia Commons, PD-Art (Millet d. 1875).',
    jigsaw: true,
  },
  {
    slug: 'the-angelus',
    prompt: 'Which painting is this?',
    correct: 'The Angelus',
    incorrect: ['The Gleaners', 'The Sower', 'Man with a Hoe'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'JEAN-FRANÇOIS MILLET - El Ángelus (Museo de Orsay, 1857-1859. Óleo sobre lienzo, 55.5 x 66 cm).jpg' },
    attribution:
      'Jean-François Millet, The Angelus (1857–1859). Wikimedia Commons, PD-Art (Millet d. 1875).',
    jigsaw: true,
  },
  {
    slug: 'the-nightmare',
    prompt: 'Which painting is this?',
    correct: 'The Nightmare',
    incorrect: ['The Ghost of a Flea', 'Titania and Bottom', 'Satan Summoning His Legions'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Henry Fuseli (1741–1825), The Nightmare, 1781.jpg' },
    attribution:
      'Henry Fuseli, The Nightmare (1781). Wikimedia Commons, PD-Art (Fuseli d. 1825).',
    jigsaw: true,
  },
  {
    slug: 'lady-jane-grey',
    prompt: 'Which painting is this?',
    correct: 'The Execution of Lady Jane Grey',
    incorrect: ['The Princes in the Tower', 'Napoleon at Fontainebleau', 'The Death of Marat'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'PAUL DELAROCHE - Ejecución de Lady Jane Grey (National Gallery de Londres, 1834).jpg' },
    attribution:
      'Paul Delaroche, The Execution of Lady Jane Grey (1833). Wikimedia Commons, PD-Art (Delaroche d. 1856).',
    jigsaw: true,
  },
  {
    slug: 'light-of-the-world',
    prompt: 'Which painting is this?',
    correct: 'The Light of the World',
    incorrect: ['The Scapegoat', 'The Awakening Conscience', 'The Shadow of Death'],
    difficulty: 'hard',
    source: { kind: 'commons', file: 'Hunt-light-of-the-world.jpeg' },
    attribution:
      'William Holman Hunt, The Light of the World (1851–1853). Wikimedia Commons, PD-Art (Hunt d. 1910).',
    jigsaw: true,
  },
  {
    slug: 'bubbles-millais',
    prompt: 'Which painting is this?',
    correct: 'Bubbles',
    incorrect: ['Ophelia', 'The Boyhood of Raleigh', 'The Blind Girl'],
    difficulty: 'medium',
    source: { kind: 'commons', file: 'Bubbles - Sir John Everett Millais.png' },
    attribution:
      'John Everett Millais, Bubbles (1886). Wikimedia Commons, PD-Art (Millais d. 1896).',
    jigsaw: true,
  },
  {
    slug: 'monarch-of-the-glen',
    prompt: 'Which painting is this?',
    correct: 'The Monarch of the Glen',
    incorrect: ['Whistlejacket', 'Dignity and Impudence', 'The Old Shepherd’s Chief Mourner'],
    difficulty: 'easy',
    source: { kind: 'commons', file: 'The Monarch of the Glen, Edwin Landseer, 1851.png' },
    attribution:
      'Edwin Landseer, The Monarch of the Glen (1851). Wikimedia Commons, PD-Art (Landseer d. 1873).',
    jigsaw: true,
  },
];
