import type { Difficulty } from '../src/questions/types';

export interface SleeveSpec {
  slug: string;
  prompt: string;
  correct: string;
  incorrect: string[];
  difficulty: Difficulty;
  artist: string;
  term: string;
  /** When search is drowned by tributes, lookup this GB collection id. */
  collectionId?: number;
}

const COVER = 'Which album is this?';

export const SLEEVE_SPECS: SleeveSpec[] = [
  { slug: 'abbey-road', prompt: COVER, correct: 'Abbey Road', incorrect: ['Let It Be', 'Sgt. Pepper’s Lonely Hearts Club Band', 'Revolver'], difficulty: 'easy', artist: 'The Beatles', term: 'abbey road beatles' },
  { slug: 'dark-side', prompt: COVER, correct: 'The Dark Side of the Moon', incorrect: ['The Wall', 'Wish You Were Here', 'Animals'], difficulty: 'easy', artist: 'Pink Floyd', term: 'dark side of the moon pink floyd', collectionId: 1065973699 },
  { slug: 'nevermind', prompt: COVER, correct: 'Nevermind', incorrect: ['In Utero', 'Ten', 'Siamese Dream'], difficulty: 'easy', artist: 'Nirvana', term: 'Nevermind Nirvana', collectionId: 1440783617 },
  { slug: 'sgt-pepper', prompt: COVER, correct: 'Sgt. Pepper’s Lonely Hearts Club Band', incorrect: ['Magical Mystery Tour', 'Abbey Road', 'Their Satanic Majesties Request'], difficulty: 'easy', artist: 'The Beatles', term: 'sgt pepper beatles' },
  { slug: 'ziggy', prompt: COVER, correct: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', incorrect: ['Aladdin Sane', 'Hunky Dory', 'Diamond Dogs'], difficulty: 'medium', artist: 'David Bowie', term: 'ziggy stardust bowie' },
  { slug: 'aladdin-sane', prompt: COVER, correct: 'Aladdin Sane', incorrect: ['Ziggy Stardust', 'Heroes', 'Low'], difficulty: 'medium', artist: 'David Bowie', term: 'aladdin sane bowie' },
  { slug: 'london-calling', prompt: COVER, correct: 'London Calling', incorrect: ['The Clash', 'Combat Rock', 'Give ’Em Enough Rope'], difficulty: 'easy', artist: 'The Clash', term: 'london calling clash' },
  { slug: 'queen-is-dead', prompt: COVER, correct: 'The Queen Is Dead', incorrect: ['Meat Is Murder', 'Strangeways, Here We Come', 'The Smiths'], difficulty: 'medium', artist: 'The Smiths', term: 'the queen is dead smiths' },
  { slug: 'definitely-maybe', prompt: COVER, correct: 'Definitely Maybe', incorrect: ['(What’s the Story) Morning Glory?', 'Be Here Now', 'Parklife'], difficulty: 'easy', artist: 'Oasis', term: 'definitely maybe oasis' },
  { slug: 'morning-glory', prompt: COVER, correct: '(What’s the Story) Morning Glory?', incorrect: ['Definitely Maybe', 'The Bends', 'Parklife'], difficulty: 'easy', artist: 'Oasis', term: 'morning glory oasis' },
  { slug: 'ok-computer', prompt: COVER, correct: 'OK Computer', incorrect: ['The Bends', 'Kid A', 'In Rainbows'], difficulty: 'medium', artist: 'Radiohead', term: 'ok computer radiohead' },
  { slug: 'the-bends', prompt: COVER, correct: 'The Bends', incorrect: ['OK Computer', 'Pablo Honey', 'The Queen Is Dead'], difficulty: 'hard', artist: 'Radiohead', term: 'the bends radiohead' },
  { slug: 'stone-roses', prompt: COVER, correct: 'The Stone Roses', incorrect: ['Second Coming', 'Pills ’n’ Thrills and Bellyaches', 'Screamadelica'], difficulty: 'medium', artist: 'The Stone Roses', term: 'the stone roses album' },
  { slug: 'different-class', prompt: COVER, correct: 'Different Class', incorrect: ['His ’n’ Hers', 'This Is Hardcore', 'Parklife'], difficulty: 'medium', artist: 'Pulp', term: 'Different Class Pulp', collectionId: 1440923838 },
  { slug: 'parklife-album', prompt: COVER, correct: 'Parklife', incorrect: ['The Great Escape', 'Modern Life Is Rubbish', 'Definitely Maybe'], difficulty: 'medium', artist: 'Blur', term: 'parklife blur album' },
  { slug: 'am-album', prompt: COVER, correct: 'AM', incorrect: ['Whatever People Say I Am, That’s What I’m Not', 'Favourite Worst Nightmare', 'Tranquility Base Hotel & Casino'], difficulty: 'easy', artist: 'Arctic Monkeys', term: 'am arctic monkeys', collectionId: 663097964 },
  { slug: 'whatever-people-say', prompt: COVER, correct: 'Whatever People Say I Am, That’s What I’m Not', incorrect: ['AM', 'Favourite Worst Nightmare', 'Is This It'], difficulty: 'easy', artist: 'Arctic Monkeys', term: "Whatever People Say I Am That's What I'm Not", collectionId: 111153953 },
  { slug: 'rumours', prompt: COVER, correct: 'Rumours', incorrect: ['Tusk', 'Fleetwood Mac', 'Hotel California'], difficulty: 'easy', artist: 'Fleetwood Mac', term: 'rumours fleetwood mac' },
  { slug: 'thriller-album', prompt: COVER, correct: 'Thriller', incorrect: ['Bad', 'Off the Wall', 'Purple Rain'], difficulty: 'easy', artist: 'Michael Jackson', term: 'thriller michael jackson' },
  { slug: 'back-in-black-album', prompt: COVER, correct: 'Back in Black', incorrect: ['Highway to Hell', 'The Razors Edge', 'Appetite for Destruction'], difficulty: 'easy', artist: 'AC/DC', term: 'back in black acdc' },
  { slug: 'led-zeppelin-iv', prompt: COVER, correct: 'Led Zeppelin IV', incorrect: ['Led Zeppelin II', 'Houses of the Holy', 'Physical Graffiti'], difficulty: 'easy', artist: 'Led Zeppelin', term: 'led zeppelin iv' },
  { slug: 'the-wall', prompt: COVER, correct: 'The Wall', incorrect: ['The Dark Side of the Moon', 'Animals', 'Wish You Were Here'], difficulty: 'easy', artist: 'Pink Floyd', term: 'The Wall Pink Floyd', collectionId: 1065975633 },
  { slug: 'unknown-pleasures', prompt: COVER, correct: 'Unknown Pleasures', incorrect: ['Closer', 'Substance', 'The Queen Is Dead'], difficulty: 'easy', artist: 'Joy Division', term: 'unknown pleasures joy division' },
  { slug: 'velvet-underground-nico', prompt: COVER, correct: 'The Velvet Underground & Nico', incorrect: ['White Light/White Heat', 'Loaded', 'Transformer'], difficulty: 'medium', artist: 'The Velvet Underground', term: 'velvet underground nico' },
  { slug: 'sticky-fingers', prompt: COVER, correct: 'Sticky Fingers', incorrect: ['Exile on Main St.', 'Let It Bleed', 'Some Girls'], difficulty: 'medium', artist: 'The Rolling Stones', term: 'sticky fingers rolling stones' },
  { slug: 'appetite', prompt: COVER, correct: 'Appetite for Destruction', incorrect: ['Use Your Illusion I', 'Back in Black', 'Nevermind'], difficulty: 'medium', artist: "Guns N' Roses", term: 'Appetite for Destruction Guns N Roses', collectionId: 1377813284 },
  { slug: 'joshua-tree', prompt: COVER, correct: 'The Joshua Tree', incorrect: ['Achtung Baby', 'War', 'The Unforgettable Fire'], difficulty: 'easy', artist: 'U2', term: 'the joshua tree u2' },
  { slug: 'automatic-for-the-people', prompt: COVER, correct: 'Automatic for the People', incorrect: ['Out of Time', 'Monster', 'Document'], difficulty: 'medium', artist: 'R.E.M.', term: 'automatic for the people rem', collectionId: 1440949853 },
  { slug: 'is-this-it', prompt: COVER, correct: 'Is This It', incorrect: ['Room on Fire', 'Whatever People Say I Am, That’s What I’m Not', 'Turn On the Bright Lights'], difficulty: 'medium', artist: 'The Strokes', term: 'Is This It The Strokes', collectionId: 269080434 },
  { slug: 'discovery', prompt: COVER, correct: 'Discovery', incorrect: ['Homework', 'Random Access Memories', 'Human After All'], difficulty: 'easy', artist: 'Daft Punk', term: 'discovery daft punk' },
  { slug: '21-adele', prompt: COVER, correct: '21', incorrect: ['19', '25', '30'], difficulty: 'easy', artist: 'Adele', term: '21 adele' },
  { slug: '25-adele', prompt: COVER, correct: '25', incorrect: ['21', '19', '30'], difficulty: 'hard', artist: 'Adele', term: '25 adele' },
  { slug: 'x-ed', prompt: COVER, correct: 'x', incorrect: ['+', '÷', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'x ed sheeran' },
  { slug: 'back-to-black', prompt: COVER, correct: 'Back to Black', incorrect: ['Frank', 'Lioness: Hidden Treasures', '19'], difficulty: 'easy', artist: 'Amy Winehouse', term: 'back to black amy winehouse' },
  { slug: 'dummy', prompt: COVER, correct: 'Dummy', incorrect: ['Mezzanine', 'Third', 'Homogenic'], difficulty: 'hard', artist: 'Portishead', term: 'dummy portishead' },
  { slug: 'homogenic', prompt: COVER, correct: 'Homogenic', incorrect: ['Debut', 'Post', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'homogenic bjork' },
  { slug: 'kid-a', prompt: COVER, correct: 'Kid A', incorrect: ['OK Computer', 'Amnesiac', 'Hail to the Thief'], difficulty: 'hard', artist: 'Radiohead', term: 'kid a radiohead' },
  { slug: 'in-rainbows', prompt: COVER, correct: 'In Rainbows', incorrect: ['OK Computer', 'Kid A', 'A Moon Shaped Pool'], difficulty: 'hard', artist: 'Radiohead', term: 'in rainbows radiohead' },
  { slug: 'hounds-of-love', prompt: COVER, correct: 'Hounds of Love', incorrect: ['The Kick Inside', 'The Dreaming', 'Aerial'], difficulty: 'hard', artist: 'Kate Bush', term: 'hounds of love kate bush' },
  { slug: 'parallel-lines', prompt: COVER, correct: 'Parallel Lines', incorrect: ['Eat to the Beat', 'Autoamerican', 'Plastic Letters'], difficulty: 'medium', artist: 'Blondie', term: 'parallel lines blondie' },
  { slug: 'born-to-run-album', prompt: COVER, correct: 'Born to Run', incorrect: ['Darkness on the Edge of Town', 'Born in the U.S.A.', 'The River'], difficulty: 'medium', artist: 'Bruce Springsteen', term: 'born to run springsteen' },
  { slug: 'hotel-california-album', prompt: COVER, correct: 'Hotel California', incorrect: ['The Long Run', 'One of These Nights', 'Rumours'], difficulty: 'easy', artist: 'Eagles', term: 'hotel california eagles album' },
  { slug: 'illmatic', prompt: COVER, correct: 'Illmatic', incorrect: ['Ready to Die', 'The Chronic', 'Enter the Wu-Tang (36 Chambers)'], difficulty: 'hard', artist: 'Nas', term: 'illmatic nas' },
  { slug: 'to-pimp-a-butterfly', prompt: COVER, correct: 'To Pimp a Butterfly', incorrect: ['good kid, m.A.A.d city', 'DAMN.', 'Channel Orange'], difficulty: 'easy', artist: 'Kendrick Lamar', term: 'to pimp a butterfly kendrick' },
  { slug: 'channel-orange', prompt: COVER, correct: 'Channel Orange', incorrect: ['Blonde', 'Nostalgia, Ultra', 'To Pimp a Butterfly'], difficulty: 'hard', artist: 'Frank Ocean', term: 'channel orange frank ocean', collectionId: 1440765580 },
  { slug: 'the-fame', prompt: COVER, correct: 'The Fame', incorrect: ['Born This Way', 'The Fame Monster', 'Artpop'], difficulty: 'medium', artist: 'Lady Gaga', term: 'the fame lady gaga', collectionId: 1440818588 },
  { slug: '1989', prompt: COVER, correct: '1989', incorrect: ['Red', 'Lover', 'Midnights'], difficulty: 'easy', artist: 'Taylor Swift', term: '1989 taylor swift' },
  { slug: 'american-idiot', prompt: COVER, correct: 'American Idiot', incorrect: ['Dookie', 'Nimrod', 'Warning'], difficulty: 'medium', artist: 'Green Day', term: 'American Idiot Green Day', collectionId: 1161539183 },
  { slug: 'californication', prompt: COVER, correct: 'Californication', incorrect: ['Blood Sugar Sex Magik', 'Stadium Arcadium', 'By the Way'], difficulty: 'medium', artist: 'Red Hot Chili Peppers', term: 'californication red hot chili peppers' },
  { slug: 'screamadelica', prompt: COVER, correct: 'Screamadelica', incorrect: ['The Stone Roses', 'Pills ’n’ Thrills and Bellyaches', 'Lazer Guided Melodies'], difficulty: 'hard', artist: 'Primal Scream', term: 'screamadelica primal scream' },
  { slug: 'urban-hymns', prompt: COVER, correct: 'Urban Hymns', incorrect: ['A Northern Soul', 'A Storm in Heaven', 'The Bends'], difficulty: 'hard', artist: 'The Verve', term: 'urban hymns verve' },
  { slug: 'rush-of-blood', prompt: COVER, correct: 'A Rush of Blood to the Head', incorrect: ['Parachutes', 'X&Y', 'Viva la Vida or Death and All His Friends'], difficulty: 'medium', artist: 'Coldplay', term: 'a rush of blood to the head coldplay' },

  /*
    Added 21 September 2026, to refill the pack after the cover-text gate.

    Thirty-three of the original fifty-two sleeves print their own title, so
    `npm run sleeve-audit` refuses them and the pack fell to eighteen — below
    the forty-five a round wants. These are candidates, not keepers: none of
    them was chosen for having a wordless cover, because nobody here can see
    the artwork iTunes GB will return. The audit decides, and what it refuses
    stays in this list as a record of what was tried.
  */
  { slug: 'wish-you-were-here-album', prompt: COVER, correct: 'Wish You Were Here', incorrect: ['The Dark Side of the Moon', 'Animals', 'The Final Cut'], difficulty: 'easy', artist: 'Pink Floyd', term: 'wish you were here pink floyd' },
  { slug: 'animals-pf', prompt: COVER, correct: 'Animals', incorrect: ['The Wall', 'Meddle', 'Wish You Were Here'], difficulty: 'hard', artist: 'Pink Floyd', term: 'pink floyd animals' },
  { slug: 'let-it-be', prompt: COVER, correct: 'Let It Be', incorrect: ['Abbey Road', 'Help!', 'Rubber Soul'], difficulty: 'medium', artist: 'The Beatles', term: 'let it be beatles' },
  { slug: 'revolver', prompt: COVER, correct: 'Revolver', incorrect: ['Rubber Soul', 'Help!', 'A Hard Day’s Night'], difficulty: 'medium', artist: 'The Beatles', term: 'revolver beatles' },
  { slug: 'white-album', prompt: COVER, correct: 'The Beatles', incorrect: ['Abbey Road', 'Let It Be', 'Magical Mystery Tour'], difficulty: 'hard', artist: 'The Beatles', term: 'the beatles white album' },
  { slug: 'houses-of-the-holy', prompt: COVER, correct: 'Houses of the Holy', incorrect: ['Led Zeppelin IV', 'Physical Graffiti', 'Presence'], difficulty: 'easy', artist: 'Led Zeppelin', term: 'houses of the holy led zeppelin' },
  { slug: 'physical-graffiti', prompt: COVER, correct: 'Physical Graffiti', incorrect: ['Led Zeppelin II', 'Houses of the Holy', 'In Through the Out Door'], difficulty: 'easy', artist: 'Led Zeppelin', term: 'physical graffiti led zeppelin' },
  { slug: 'led-zeppelin-ii', prompt: COVER, correct: 'Led Zeppelin II', incorrect: ['Led Zeppelin IV', 'Presence', 'Coda'], difficulty: 'hard', artist: 'Led Zeppelin', term: 'led zeppelin ii' },
  { slug: 'in-utero', prompt: COVER, correct: 'In Utero', incorrect: ['Nevermind', 'Bleach', 'MTV Unplugged in New York'], difficulty: 'medium', artist: 'Nirvana', term: 'in utero nirvana' },
  { slug: 'closer-jd', prompt: COVER, correct: 'Closer', incorrect: ['Unknown Pleasures', 'Still', 'Substance'], difficulty: 'hard', artist: 'Joy Division', term: 'closer joy division' },
  { slug: 'power-corruption-lies', prompt: COVER, correct: 'Power, Corruption & Lies', incorrect: ['Technique', 'Low-Life', 'Brotherhood'], difficulty: 'medium', artist: 'New Order', term: 'power corruption and lies new order' },
  { slug: 'technique', prompt: COVER, correct: 'Technique', incorrect: ['Low-Life', 'Republic', 'Brotherhood'], difficulty: 'hard', artist: 'New Order', term: 'technique new order' },
  { slug: 'meat-is-murder', prompt: COVER, correct: 'Meat Is Murder', incorrect: ['The Queen Is Dead', 'Strangeways, Here We Come', 'The Smiths'], difficulty: 'hard', artist: 'The Smiths', term: 'meat is murder smiths' },
  { slug: 'strangeways', prompt: COVER, correct: 'Strangeways, Here We Come', incorrect: ['The Queen Is Dead', 'Meat Is Murder', 'The Smiths'], difficulty: 'hard', artist: 'The Smiths', term: 'strangeways here we come smiths' },
  { slug: 'post-bjork', prompt: COVER, correct: 'Post', incorrect: ['Debut', 'Homogenic', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'post bjork' },
  { slug: 'debut-bjork', prompt: COVER, correct: 'Debut', incorrect: ['Post', 'Homogenic', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'debut bjork' },
  { slug: 'vespertine', prompt: COVER, correct: 'Vespertine', incorrect: ['Debut', 'Post', 'Homogenic'], difficulty: 'hard', artist: 'Björk', term: 'vespertine bjork' },
  { slug: 'amnesiac', prompt: COVER, correct: 'Amnesiac', incorrect: ['Kid A', 'Hail to the Thief', 'In Rainbows'], difficulty: 'hard', artist: 'Radiohead', term: 'amnesiac radiohead' },
  { slug: 'moon-shaped-pool', prompt: COVER, correct: 'A Moon Shaped Pool', incorrect: ['In Rainbows', 'Amnesiac', 'Hail to the Thief'], difficulty: 'hard', artist: 'Radiohead', term: 'a moon shaped pool radiohead' },
  { slug: 'parachutes', prompt: COVER, correct: 'Parachutes', incorrect: ['A Rush of Blood to the Head', 'X&Y', 'Ghost Stories'], difficulty: 'medium', artist: 'Coldplay', term: 'parachutes coldplay' },
  { slug: 'x-and-y', prompt: COVER, correct: 'X&Y', incorrect: ['Parachutes', 'A Rush of Blood to the Head', 'Mylo Xyloto'], difficulty: 'medium', artist: 'Coldplay', term: 'x&y coldplay' },
  { slug: 'viva-la-vida-album', prompt: COVER, correct: 'Viva la Vida or Death and All His Friends', incorrect: ['Parachutes', 'X&Y', 'Ghost Stories'], difficulty: 'medium', artist: 'Coldplay', term: 'viva la vida coldplay' },
  { slug: 'homework', prompt: COVER, correct: 'Homework', incorrect: ['Discovery', 'Human After All', 'Random Access Memories'], difficulty: 'medium', artist: 'Daft Punk', term: 'homework daft punk' },
  { slug: 'random-access', prompt: COVER, correct: 'Random Access Memories', incorrect: ['Discovery', 'Homework', 'Human After All'], difficulty: 'medium', artist: 'Daft Punk', term: 'random access memories daft punk' },
  { slug: 'mezzanine', prompt: COVER, correct: 'Mezzanine', incorrect: ['Blue Lines', 'Protection', '100th Window'], difficulty: 'hard', artist: 'Massive Attack', term: 'mezzanine massive attack' },
  { slug: 'blue-lines', prompt: COVER, correct: 'Blue Lines', incorrect: ['Mezzanine', 'Protection', 'Heligoland'], difficulty: 'hard', artist: 'Massive Attack', term: 'blue lines massive attack' },
  { slug: 'fat-of-the-land', prompt: COVER, correct: 'The Fat of the Land', incorrect: ['Music for the Jilted Generation', 'Experience', 'Invaders Must Die'], difficulty: 'medium', artist: 'The Prodigy', term: 'the fat of the land prodigy' },
  { slug: 'good-kid', prompt: COVER, correct: 'good kid, m.A.A.d city', incorrect: ['To Pimp a Butterfly', 'DAMN.', 'Section.80'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'good kid maad city kendrick lamar' },
  { slug: 'damn-kendrick', prompt: COVER, correct: 'DAMN.', incorrect: ['good kid, m.A.A.d city', 'To Pimp a Butterfly', 'Section.80'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'damn kendrick lamar' },
  { slug: 'blonde-frank', prompt: COVER, correct: 'Blonde', incorrect: ['Channel Orange', 'Nostalgia, Ultra', 'Endless'], difficulty: 'hard', artist: 'Frank Ocean', term: 'frank ocean blonde album' },
  { slug: 'war-u2', prompt: COVER, correct: 'War', incorrect: ['Boy', 'October', 'The Unforgettable Fire'], difficulty: 'medium', artist: 'U2', term: 'war u2' },
  { slug: 'achtung-baby', prompt: COVER, correct: 'Achtung Baby', incorrect: ['The Joshua Tree', 'Zooropa', 'Pop'], difficulty: 'medium', artist: 'U2', term: 'achtung baby u2' },
  { slug: 'unforgettable-fire', prompt: COVER, correct: 'The Unforgettable Fire', incorrect: ['War', 'Boy', 'The Joshua Tree'], difficulty: 'hard', artist: 'U2', term: 'the unforgettable fire u2' },
  { slug: 'hunky-dory', prompt: COVER, correct: 'Hunky Dory', incorrect: ['Low', 'Heroes', 'Diamond Dogs'], difficulty: 'hard', artist: 'David Bowie', term: 'hunky dory bowie' },
  { slug: 'low-bowie', prompt: COVER, correct: 'Low', incorrect: ['Heroes', 'Lodger', 'Station to Station'], difficulty: 'hard', artist: 'David Bowie', term: 'low david bowie' },
  { slug: 'heroes-bowie', prompt: COVER, correct: 'Heroes', incorrect: ['Low', 'Lodger', 'Hunky Dory'], difficulty: 'hard', artist: 'David Bowie', term: 'heroes david bowie' },
  { slug: 'diamond-dogs', prompt: COVER, correct: 'Diamond Dogs', incorrect: ['Hunky Dory', 'Aladdin Sane', 'Pin Ups'], difficulty: 'hard', artist: 'David Bowie', term: 'diamond dogs bowie' },
  { slug: 'night-at-the-opera', prompt: COVER, correct: 'A Night at the Opera', incorrect: ['News of the World', 'Sheer Heart Attack', 'A Day at the Races'], difficulty: 'medium', artist: 'Queen', term: 'a night at the opera queen' },
  { slug: 'news-of-the-world', prompt: COVER, correct: 'News of the World', incorrect: ['A Night at the Opera', 'Jazz', 'The Game'], difficulty: 'medium', artist: 'Queen', term: 'news of the world queen' },
  { slug: 'whos-next', prompt: COVER, correct: 'Who’s Next', incorrect: ['Quadrophenia', 'Tommy', 'My Generation'], difficulty: 'hard', artist: 'The Who', term: 'whos next the who' },
  { slug: 'quadrophenia', prompt: COVER, correct: 'Quadrophenia', incorrect: ['Tommy', 'Who’s Next', 'My Generation'], difficulty: 'hard', artist: 'The Who', term: 'quadrophenia the who' },
  { slug: 'exile-on-main-st', prompt: COVER, correct: 'Exile on Main St.', incorrect: ['Sticky Fingers', 'Let It Bleed', 'Some Girls'], difficulty: 'hard', artist: 'The Rolling Stones', term: 'exile on main street rolling stones' },
  { slug: 'let-it-bleed', prompt: COVER, correct: 'Let It Bleed', incorrect: ['Sticky Fingers', 'Beggars Banquet', 'Aftermath'], difficulty: 'hard', artist: 'The Rolling Stones', term: 'let it bleed rolling stones' },
  { slug: 'disintegration', prompt: COVER, correct: 'Disintegration', incorrect: ['Faith', 'Pornography', 'Wish'], difficulty: 'hard', artist: 'The Cure', term: 'disintegration the cure' },
  { slug: 'violator', prompt: COVER, correct: 'Violator', incorrect: ['Music for the Masses', 'Songs of Faith and Devotion', 'Black Celebration'], difficulty: 'hard', artist: 'Depeche Mode', term: 'violator depeche mode' },
  { slug: 'remain-in-light', prompt: COVER, correct: 'Remain in Light', incorrect: ['Fear of Music', 'Speaking in Tongues', 'More Songs About Buildings and Food'], difficulty: 'hard', artist: 'Talking Heads', term: 'remain in light talking heads' },
  { slug: 'great-escape', prompt: COVER, correct: 'The Great Escape', incorrect: ['Parklife', 'Modern Life Is Rubbish', '13'], difficulty: 'hard', artist: 'Blur', term: 'the great escape blur' },
  { slug: 'modern-life', prompt: COVER, correct: 'Modern Life Is Rubbish', incorrect: ['Parklife', 'The Great Escape', 'Leisure'], difficulty: 'hard', artist: 'Blur', term: 'modern life is rubbish blur' },
  { slug: 'blur-13', prompt: COVER, correct: '13', incorrect: ['Parklife', 'The Great Escape', 'Think Tank'], difficulty: 'hard', artist: 'Blur', term: '13 blur album' },
  { slug: 'be-here-now', prompt: COVER, correct: 'Be Here Now', incorrect: ['Definitely Maybe', '(What’s the Story) Morning Glory?', 'Heathen Chemistry'], difficulty: 'medium', artist: 'Oasis', term: 'be here now oasis' },
  { slug: 'origin-of-symmetry', prompt: COVER, correct: 'Origin of Symmetry', incorrect: ['Absolution', 'Black Holes and Revelations', 'Showbiz'], difficulty: 'hard', artist: 'Muse', term: 'origin of symmetry muse' },
  { slug: 'absolution', prompt: COVER, correct: 'Absolution', incorrect: ['Origin of Symmetry', 'Black Holes and Revelations', 'The Resistance'], difficulty: 'hard', artist: 'Muse', term: 'absolution muse' },
  { slug: 'hot-fuss', prompt: COVER, correct: 'Hot Fuss', incorrect: ['Sam’s Town', 'Day & Age', 'Battle Born'], difficulty: 'medium', artist: 'The Killers', term: 'hot fuss the killers' },
  { slug: 'sams-town', prompt: COVER, correct: 'Sam’s Town', incorrect: ['Hot Fuss', 'Day & Age', 'Wonderful Wonderful'], difficulty: 'medium', artist: 'The Killers', term: 'sams town the killers' },
  { slug: 'favourite-worst-nightmare', prompt: COVER, correct: 'Favourite Worst Nightmare', incorrect: ['AM', 'Whatever People Say I Am, That’s What I’m Not', 'Humbug'], difficulty: 'medium', artist: 'Arctic Monkeys', term: 'arctic monkeys favourite worst nightmare' },
  { slug: 'employment', prompt: COVER, correct: 'Employment', incorrect: ['Yours Truly, Angry Mob', 'Off With Their Heads', 'Education, Education, Education & War'], difficulty: 'hard', artist: 'Kaiser Chiefs', term: 'employment kaiser chiefs' },
  { slug: 'seldom-seen-kid', prompt: COVER, correct: 'The Seldom Seen Kid', incorrect: ['Cast of Thousands', 'Asleep in the Back', 'Build a Rocket Boys!'], difficulty: 'hard', artist: 'Elbow', term: 'the seldom seen kid elbow' },
  { slug: 'hopes-and-fears', prompt: COVER, correct: 'Hopes and Fears', incorrect: ['Under the Iron Sea', 'Perfect Symmetry', 'Strangeland'], difficulty: 'medium', artist: 'Keane', term: 'hopes and fears keane' },
  { slug: 'final-straw', prompt: COVER, correct: 'Final Straw', incorrect: ['Eyes Open', 'A Hundred Million Suns', 'Songs for Polarbears'], difficulty: 'medium', artist: 'Snow Patrol', term: 'snow patrol final straw' },
  { slug: 'everything-must-go', prompt: COVER, correct: 'Everything Must Go', incorrect: ['The Holy Bible', 'Generation Terrorists', 'This Is My Truth Tell Me Yours'], difficulty: 'hard', artist: 'Manic Street Preachers', term: 'everything must go manic street preachers' },
  { slug: 'dog-man-star', prompt: COVER, correct: 'Dog Man Star', incorrect: ['Suede', 'Coming Up', 'Head Music'], difficulty: 'hard', artist: 'Suede', term: 'dog man star suede' },
  { slug: 'the-man-who', prompt: COVER, correct: 'The Man Who', incorrect: ['The Invisible Band', 'Good Feeling', '12 Memories'], difficulty: 'hard', artist: 'Travis', term: 'the man who travis' },
  { slug: 'goodbye-yellow-brick', prompt: COVER, correct: 'Goodbye Yellow Brick Road', incorrect: ['Madman Across the Water', 'Honky Château', 'Captain Fantastic'], difficulty: 'medium', artist: 'Elton John', term: 'goodbye yellow brick road elton john' },
  { slug: 'brothers-in-arms', prompt: COVER, correct: 'Brothers in Arms', incorrect: ['Love Over Gold', 'Making Movies', 'Communiqué'], difficulty: 'medium', artist: 'Dire Straits', term: 'brothers in arms dire straits' },
  { slug: 'so-gabriel', prompt: COVER, correct: 'So', incorrect: ['Us', 'Peter Gabriel', 'Security'], difficulty: 'hard', artist: 'Peter Gabriel', term: 'so peter gabriel' },
  { slug: 'big-chair', prompt: COVER, correct: 'Songs from the Big Chair', incorrect: ['The Hurting', 'The Seeds of Love', 'Elemental'], difficulty: 'hard', artist: 'Tears for Fears', term: 'songs from the big chair tears for fears' },
  { slug: 'all-mod-cons', prompt: COVER, correct: 'All Mod Cons', incorrect: ['Sound Affects', 'Setting Sons', 'The Gift'], difficulty: 'hard', artist: 'The Jam', term: 'all mod cons the jam' },
  { slug: 'one-step-beyond', prompt: COVER, correct: 'One Step Beyond', incorrect: ['Absolutely', '7', 'The Rise & Fall'], difficulty: 'hard', artist: 'Madness', term: 'one step beyond madness' },
  { slug: 'original-pirate', prompt: COVER, correct: 'Original Pirate Material', incorrect: ['A Grand Don’t Come for Free', 'The Hardest Way to Make an Easy Living', 'Computers and Blues'], difficulty: 'hard', artist: 'The Streets', term: 'the streets original pirate material' },
  { slug: 'boy-in-da-corner', prompt: COVER, correct: 'Boy in da Corner', incorrect: ['Showtime', 'Maths + English', 'Tongue n’ Cheek'], difficulty: 'hard', artist: 'Dizzee Rascal', term: 'boy in da corner dizzee rascal' },
  { slug: 'frank-amy', prompt: COVER, correct: 'Frank', incorrect: ['Back to Black', 'Lioness: Hidden Treasures', 'At the BBC'], difficulty: 'hard', artist: 'Amy Winehouse', term: 'frank amy winehouse' },
  { slug: 'lungs', prompt: COVER, correct: 'Lungs', incorrect: ['Ceremonials', 'How Big, How Blue, How Beautiful', 'High as Hope'], difficulty: 'medium', artist: 'Florence + The Machine', term: 'lungs florence and the machine' },
  { slug: 'plus-ed', prompt: COVER, correct: '+', incorrect: ['x', '÷', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'plus ed sheeran' },
  { slug: 'divide-ed', prompt: COVER, correct: '÷', incorrect: ['+', 'x', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'divide ed sheeran' },
  { slug: 'after-hours', prompt: COVER, correct: 'After Hours', incorrect: ['Starboy', 'Beauty Behind the Madness', 'Dawn FM'], difficulty: 'medium', artist: 'The Weeknd', term: 'after hours the weeknd' },
  { slug: 'born-to-die', prompt: COVER, correct: 'Born to Die', incorrect: ['Ultraviolence', 'Honeymoon', 'Norman Fucking Rockwell!'], difficulty: 'medium', artist: 'Lana Del Rey', term: 'born to die lana del rey' },
  { slug: 'lemonade', prompt: COVER, correct: 'Lemonade', incorrect: ['Beyoncé', '4', 'B’Day'], difficulty: 'medium', artist: 'Beyoncé', term: 'beyonce lemonade album' },
  { slug: 'anti-rihanna', prompt: COVER, correct: 'Anti', incorrect: ['Good Girl Gone Bad', 'Loud', 'Unapologetic'], difficulty: 'medium', artist: 'Rihanna', term: 'anti rihanna' },
  { slug: 'purple-rain-album', prompt: COVER, correct: 'Purple Rain', incorrect: ['Sign o’ the Times', '1999', 'Around the World in a Day'], difficulty: 'medium', artist: 'Prince', term: 'purple rain prince' },
  { slug: 'off-the-wall', prompt: COVER, correct: 'Off the Wall', incorrect: ['Thriller', 'Bad', 'Dangerous'], difficulty: 'medium', artist: 'Michael Jackson', term: 'off the wall michael jackson' },
  { slug: 'bad-mj', prompt: COVER, correct: 'Bad', incorrect: ['Thriller', 'Off the Wall', 'Dangerous'], difficulty: 'medium', artist: 'Michael Jackson', term: 'bad michael jackson' },
  { slug: 'tusk', prompt: COVER, correct: 'Tusk', incorrect: ['Rumours', 'Fleetwood Mac', 'Mirage'], difficulty: 'hard', artist: 'Fleetwood Mac', term: 'tusk fleetwood mac' },
  { slug: 'the-long-run', prompt: COVER, correct: 'The Long Run', incorrect: ['Hotel California', 'One of These Nights', 'Desperado'], difficulty: 'hard', artist: 'Eagles', term: 'the long run eagles' },
  { slug: 'born-in-the-usa', prompt: COVER, correct: 'Born in the U.S.A.', incorrect: ['Born to Run', 'Nebraska', 'Darkness on the Edge of Town'], difficulty: 'medium', artist: 'Bruce Springsteen', term: 'born in the usa springsteen' },
  { slug: 'nebraska', prompt: COVER, correct: 'Nebraska', incorrect: ['Born to Run', 'Born in the U.S.A.', 'The River'], difficulty: 'hard', artist: 'Bruce Springsteen', term: 'nebraska springsteen' },
  { slug: 'master-of-puppets', prompt: COVER, correct: 'Master of Puppets', incorrect: ['Ride the Lightning', '…And Justice for All', 'Kill ’Em All'], difficulty: 'medium', artist: 'Metallica', term: 'metallica master of puppets' },
  { slug: 'ride-the-lightning', prompt: COVER, correct: 'Ride the Lightning', incorrect: ['Master of Puppets', 'Kill ’Em All', 'Load'], difficulty: 'hard', artist: 'Metallica', term: 'ride the lightning metallica' },
  { slug: 'highway-to-hell-album', prompt: COVER, correct: 'Highway to Hell', incorrect: ['Back in Black', 'The Razors Edge', 'Powerage'], difficulty: 'medium', artist: 'AC/DC', term: 'highway to hell acdc' },
  { slug: 'grace-buckley', prompt: COVER, correct: 'Grace', incorrect: ['Sketches for My Sweetheart the Drunk', 'Live at Sin-é', 'You and I'], difficulty: 'hard', artist: 'Jeff Buckley', term: 'grace jeff buckley' },
  { slug: 'funeral', prompt: COVER, correct: 'Funeral', incorrect: ['Neon Bible', 'The Suburbs', 'Reflektor'], difficulty: 'medium', artist: 'Arcade Fire', term: 'funeral arcade fire' },
  { slug: 'for-emma', prompt: COVER, correct: 'For Emma, Forever Ago', incorrect: ['Bon Iver', '22, A Million', 'i,i'], difficulty: 'hard', artist: 'Bon Iver', term: 'bon iver for emma forever ago' },
  { slug: 'currents', prompt: COVER, correct: 'Currents', incorrect: ['Lonerism', 'InnerSpeaker', 'The Slow Rush'], difficulty: 'medium', artist: 'Tame Impala', term: 'currents tame impala' },
  { slug: 'lonerism', prompt: COVER, correct: 'Lonerism', incorrect: ['Currents', 'InnerSpeaker', 'The Slow Rush'], difficulty: 'hard', artist: 'Tame Impala', term: 'lonerism tame impala' },
  { slug: 'demon-days', prompt: COVER, correct: 'Demon Days', incorrect: ['Gorillaz', 'Plastic Beach', 'Humanz'], difficulty: 'medium', artist: 'Gorillaz', term: 'demon days gorillaz' },
  { slug: 'dookie', prompt: COVER, correct: 'Dookie', incorrect: ['American Idiot', 'Nimrod', 'Insomniac'], difficulty: 'medium', artist: 'Green Day', term: 'green day dookie' },
  { slug: 'blood-sugar', prompt: COVER, correct: 'Blood Sugar Sex Magik', incorrect: ['Californication', 'By the Way', 'Stadium Arcadium'], difficulty: 'medium', artist: 'Red Hot Chili Peppers', term: 'red hot chili peppers blood sugar sex magik' },
  { slug: 'by-the-way', prompt: COVER, correct: 'By the Way', incorrect: ['Californication', 'Blood Sugar Sex Magik', 'One Hot Minute'], difficulty: 'hard', artist: 'Red Hot Chili Peppers', term: 'red hot chili peppers by the way' },
  { slug: 'enter-the-wu-tang', prompt: COVER, correct: 'Enter the Wu-Tang (36 Chambers)', incorrect: ['Illmatic', 'Ready to Die', 'The Chronic'], difficulty: 'hard', artist: 'Wu-Tang Clan', term: 'enter the wu tang 36 chambers' },
  { slug: 'the-chronic', prompt: COVER, correct: 'The Chronic', incorrect: ['2001', 'Illmatic', 'Ready to Die'], difficulty: 'hard', artist: 'Dr. Dre', term: 'dr dre the chronic' },
  { slug: 'ready-to-die', prompt: COVER, correct: 'Ready to Die', incorrect: ['Life After Death', 'Illmatic', 'The Chronic'], difficulty: 'hard', artist: 'The Notorious B.I.G.', term: 'ready to die notorious big' },
  { slug: 'pauls-boutique', prompt: COVER, correct: 'Paul’s Boutique', incorrect: ['Licensed to Ill', 'Check Your Head', 'Ill Communication'], difficulty: 'hard', artist: 'Beastie Boys', term: 'beastie boys pauls boutique' },
  { slug: 'third-portishead', prompt: COVER, correct: 'Third', incorrect: ['Dummy', 'Portishead', 'Roseland NYC Live'], difficulty: 'medium', artist: 'Portishead', term: 'third portishead' },
  { slug: 'selected-ambient', prompt: COVER, correct: 'Selected Ambient Works 85-92', incorrect: ['Richard D. James Album', 'Drukqs', 'Syro'], difficulty: 'hard', artist: 'Aphex Twin', term: 'selected ambient works aphex twin' },
  { slug: 'dig-your-own-hole', prompt: COVER, correct: 'Dig Your Own Hole', incorrect: ['Exit Planet Dust', 'Surrender', 'Come With Us'], difficulty: 'hard', artist: 'The Chemical Brothers', term: 'dig your own hole chemical brothers' },
  { slug: 'play-moby', prompt: COVER, correct: 'Play', incorrect: ['18', 'Everything Is Wrong', 'Animal Rights'], difficulty: 'medium', artist: 'Moby', term: 'play moby' },
  { slug: 'moon-safari', prompt: COVER, correct: 'Moon Safari', incorrect: ['Talkie Walkie', '10 000 Hz Legend', 'Premiers Symptômes'], difficulty: 'hard', artist: 'Air', term: 'moon safari air' },

  /*
    A second batch, 21 September 2026, after a person looked at the first.

    The audit cleared 37 and **eleven of them print their own title** in type
    Vision cannot read — letterspaced, scripted, or upside down in one tile of a
    grid. 26 survived both passes, against a floor of 36, so the list needed
    lengthening rather than the bar lowering.

    Weighted towards what actually survived the first round: designer-led
    sleeves (Saville, Hipgnosis, Vaughan Oliver), portraits where the artist is
    the image, and photographic covers from before a title on the front was the
    default. Still candidates, not keepers — the audit and then a person decide.
  */
  { slug: 'hail-to-the-thief', prompt: COVER, correct: 'Hail to the Thief', incorrect: ['Amnesiac', 'In Rainbows', 'A Moon Shaped Pool'], difficulty: 'hard', artist: 'Radiohead', term: 'radiohead hail to the thief' },
  { slug: 'pablo-honey', prompt: COVER, correct: 'Pablo Honey', incorrect: ['The Bends', 'Amnesiac', 'Kid A'], difficulty: 'hard', artist: 'Radiohead', term: 'radiohead pablo honey' },
  { slug: 'brotherhood-no', prompt: COVER, correct: 'Brotherhood', incorrect: ['Technique', 'Low-Life', 'Republic'], difficulty: 'hard', artist: 'New Order', term: 'new order brotherhood' },
  { slug: 'republic-no', prompt: COVER, correct: 'Republic', incorrect: ['Technique', 'Brotherhood', 'Low-Life'], difficulty: 'hard', artist: 'New Order', term: 'new order republic' },
  { slug: 'low-life', prompt: COVER, correct: 'Low-Life', incorrect: ['Technique', 'Brotherhood', 'Republic'], difficulty: 'hard', artist: 'New Order', term: 'new order low life' },
  { slug: 'meddle', prompt: COVER, correct: 'Meddle', incorrect: ['Animals', 'The Final Cut', 'Obscured by Clouds'], difficulty: 'medium', artist: 'Pink Floyd', term: 'pink floyd meddle' },
  { slug: 'atom-heart-mother', prompt: COVER, correct: 'Atom Heart Mother', incorrect: ['Meddle', 'Ummagumma', 'More'], difficulty: 'medium', artist: 'Pink Floyd', term: 'pink floyd atom heart mother' },
  { slug: 'presence-lz', prompt: COVER, correct: 'Presence', incorrect: ['Houses of the Holy', 'In Through the Out Door', 'Coda'], difficulty: 'hard', artist: 'Led Zeppelin', term: 'led zeppelin presence' },
  { slug: 'in-through-the-out-door', prompt: COVER, correct: 'In Through the Out Door', incorrect: ['Presence', 'Coda', 'Physical Graffiti'], difficulty: 'medium', artist: 'Led Zeppelin', term: 'led zeppelin in through the out door' },
  { slug: '19-adele', prompt: COVER, correct: '19', incorrect: ['21', '25', '30'], difficulty: 'medium', artist: 'Adele', term: 'adele 19' },
  { slug: '30-adele', prompt: COVER, correct: '30', incorrect: ['19', '21', '25'], difficulty: 'medium', artist: 'Adele', term: 'adele 30' },
  { slug: 'rubber-soul', prompt: COVER, correct: 'Rubber Soul', incorrect: ['Revolver', 'Help!', 'Beatles for Sale'], difficulty: 'medium', artist: 'The Beatles', term: 'beatles rubber soul' },
  { slug: 'help-beatles', prompt: COVER, correct: 'Help!', incorrect: ['Rubber Soul', 'Revolver', 'A Hard Day’s Night'], difficulty: 'medium', artist: 'The Beatles', term: 'beatles help' },
  { slug: 'hard-days-night', prompt: COVER, correct: 'A Hard Day’s Night', incorrect: ['Help!', 'Beatles for Sale', 'With the Beatles'], difficulty: 'hard', artist: 'The Beatles', term: 'beatles a hard days night' },
  { slug: 'diamond-life', prompt: COVER, correct: 'Diamond Life', incorrect: ['Promise', 'Stronger Than Pride', 'Love Deluxe'], difficulty: 'hard', artist: 'Sade', term: 'sade diamond life' },
  { slug: 'love-deluxe', prompt: COVER, correct: 'Love Deluxe', incorrect: ['Diamond Life', 'Promise', 'Lovers Rock'], difficulty: 'hard', artist: 'Sade', term: 'sade love deluxe' },
  { slug: 'come-away-with-me', prompt: COVER, correct: 'Come Away with Me', incorrect: ['Feels Like Home', 'Not Too Late', 'The Fall'], difficulty: 'medium', artist: 'Norah Jones', term: 'norah jones come away with me' },
  { slug: 'no-angel', prompt: COVER, correct: 'No Angel', incorrect: ['Life for Rent', 'Safe Trip Home', 'Girl Who Got Away'], difficulty: 'medium', artist: 'Dido', term: 'dido no angel' },
  { slug: 'jagged-little-pill', prompt: COVER, correct: 'Jagged Little Pill', incorrect: ['Supposed Former Infatuation Junkie', 'Under Rug Swept', 'Flavors of Entanglement'], difficulty: 'medium', artist: 'Alanis Morissette', term: 'alanis morissette jagged little pill' },
  { slug: 'tracy-chapman', prompt: COVER, correct: 'Tracy Chapman', incorrect: ['Crossroads', 'New Beginning', 'Matters of the Heart'], difficulty: 'hard', artist: 'Tracy Chapman', term: 'tracy chapman debut album' },
  { slug: 'the-kick-inside', prompt: COVER, correct: 'The Kick Inside', incorrect: ['Hounds of Love', 'The Dreaming', 'Never for Ever'], difficulty: 'hard', artist: 'Kate Bush', term: 'kate bush the kick inside' },
  { slug: 'the-dreaming', prompt: COVER, correct: 'The Dreaming', incorrect: ['Hounds of Love', 'The Kick Inside', 'Aerial'], difficulty: 'hard', artist: 'Kate Bush', term: 'kate bush the dreaming' },
  { slug: 'aerial-kb', prompt: COVER, correct: 'Aerial', incorrect: ['Hounds of Love', 'The Dreaming', '50 Words for Snow'], difficulty: 'hard', artist: 'Kate Bush', term: 'kate bush aerial' },
  { slug: 'diva-lennox', prompt: COVER, correct: 'Diva', incorrect: ['Medusa', 'Bare', 'Songs of Mass Destruction'], difficulty: 'hard', artist: 'Annie Lennox', term: 'annie lennox diva' },
  { slug: 'his-n-hers', prompt: COVER, correct: 'His ’n’ Hers', incorrect: ['Different Class', 'This Is Hardcore', 'We Love Life'], difficulty: 'hard', artist: 'Pulp', term: 'pulp his n hers' },
  { slug: 'this-is-hardcore', prompt: COVER, correct: 'This Is Hardcore', incorrect: ['Different Class', 'His ’n’ Hers', 'We Love Life'], difficulty: 'hard', artist: 'Pulp', term: 'pulp this is hardcore' },
  { slug: 'elastica-album', prompt: COVER, correct: 'Elastica', incorrect: ['The Menace', 'Six Track EP', 'Connection'], difficulty: 'hard', artist: 'Elastica', term: 'elastica debut album' },
  { slug: 'i-should-coco', prompt: COVER, correct: 'I Should Coco', incorrect: ['In It for the Money', 'Supergrass', 'Life on Other Planets'], difficulty: 'hard', artist: 'Supergrass', term: 'supergrass i should coco' },
  { slug: 'in-it-for-the-money', prompt: COVER, correct: 'In It for the Money', incorrect: ['I Should Coco', 'Supergrass', 'Road to Rouen'], difficulty: 'hard', artist: 'Supergrass', term: 'supergrass in it for the money' },
  { slug: 'a-northern-soul', prompt: COVER, correct: 'A Northern Soul', incorrect: ['Urban Hymns', 'A Storm in Heaven', 'Forth'], difficulty: 'hard', artist: 'The Verve', term: 'the verve a northern soul' },
  { slug: 'a-storm-in-heaven', prompt: COVER, correct: 'A Storm in Heaven', incorrect: ['Urban Hymns', 'A Northern Soul', 'Forth'], difficulty: 'hard', artist: 'The Verve', term: 'the verve a storm in heaven' },
  { slug: 'lost-souls', prompt: COVER, correct: 'Lost Souls', incorrect: ['The Last Broadcast', 'Some Cities', 'Kingdom of Rust'], difficulty: 'hard', artist: 'Doves', term: 'doves lost souls' },
  { slug: 'the-last-broadcast', prompt: COVER, correct: 'The Last Broadcast', incorrect: ['Lost Souls', 'Some Cities', 'Kingdom of Rust'], difficulty: 'hard', artist: 'Doves', term: 'doves the last broadcast' },
  { slug: 'asleep-in-the-back', prompt: COVER, correct: 'Asleep in the Back', incorrect: ['Cast of Thousands', 'The Seldom Seen Kid', 'Leaders of the Free World'], difficulty: 'hard', artist: 'Elbow', term: 'elbow asleep in the back' },
  { slug: 'cast-of-thousands', prompt: COVER, correct: 'Cast of Thousands', incorrect: ['Asleep in the Back', 'The Seldom Seen Kid', 'Build a Rocket Boys!'], difficulty: 'hard', artist: 'Elbow', term: 'elbow cast of thousands' },
  { slug: 'heathen-chemistry', prompt: COVER, correct: 'Heathen Chemistry', incorrect: ['Be Here Now', 'Standing on the Shoulder of Giants', 'Don’t Believe the Truth'], difficulty: 'hard', artist: 'Oasis', term: 'oasis heathen chemistry' },
  { slug: 'standing-on-the-shoulder', prompt: COVER, correct: 'Standing on the Shoulder of Giants', incorrect: ['Be Here Now', 'Heathen Chemistry', 'Dig Out Your Soul'], difficulty: 'hard', artist: 'Oasis', term: 'oasis standing on the shoulder of giants' },
  { slug: 'think-tank', prompt: COVER, correct: 'Think Tank', incorrect: ['13', 'Parklife', 'The Great Escape'], difficulty: 'hard', artist: 'Blur', term: 'blur think tank' },
  { slug: 'leisure-blur', prompt: COVER, correct: 'Leisure', incorrect: ['Modern Life Is Rubbish', 'Parklife', '13'], difficulty: 'hard', artist: 'Blur', term: 'blur leisure' },
  { slug: 'humbug', prompt: COVER, correct: 'Humbug', incorrect: ['AM', 'Favourite Worst Nightmare', 'Suck It and See'], difficulty: 'hard', artist: 'Arctic Monkeys', term: 'arctic monkeys humbug' },
  { slug: 'suck-it-and-see', prompt: COVER, correct: 'Suck It and See', incorrect: ['AM', 'Humbug', 'Tranquility Base Hotel & Casino'], difficulty: 'hard', artist: 'Arctic Monkeys', term: 'arctic monkeys suck it and see' },
  { slug: 'room-on-fire', prompt: COVER, correct: 'Room on Fire', incorrect: ['Is This It', 'First Impressions of Earth', 'Angles'], difficulty: 'hard', artist: 'The Strokes', term: 'the strokes room on fire' },
  { slug: 'turn-on-the-bright-lights', prompt: COVER, correct: 'Turn On the Bright Lights', incorrect: ['Antics', 'Our Love to Admire', 'Interpol'], difficulty: 'hard', artist: 'Interpol', term: 'interpol turn on the bright lights' },
  { slug: 'antics', prompt: COVER, correct: 'Antics', incorrect: ['Turn On the Bright Lights', 'Our Love to Admire', 'El Pintor'], difficulty: 'hard', artist: 'Interpol', term: 'interpol antics' },
  { slug: 'silent-alarm', prompt: COVER, correct: 'Silent Alarm', incorrect: ['A Weekend in the City', 'Intimacy', 'Four'], difficulty: 'hard', artist: 'Bloc Party', term: 'bloc party silent alarm' },
  { slug: 'mezzanine-ma', prompt: COVER, correct: 'Protection', incorrect: ['Blue Lines', 'Mezzanine', 'Heligoland'], difficulty: 'hard', artist: 'Massive Attack', term: 'massive attack protection' },
  { slug: 'heligoland', prompt: COVER, correct: 'Heligoland', incorrect: ['Mezzanine', 'Blue Lines', 'Protection'], difficulty: 'hard', artist: 'Massive Attack', term: 'massive attack heligoland' },
  { slug: 'dubnobass', prompt: COVER, correct: 'Dubnobasswithmyheadman', incorrect: ['Second Toughest in the Infants', 'Beaucoup Fish', 'Barbara Barbara'], difficulty: 'hard', artist: 'Underworld', term: 'underworld dubnobasswithmyheadman' },
  { slug: 'leftism', prompt: COVER, correct: 'Leftism', incorrect: ['Rhythm and Stealth', 'Alternative Light Source', 'Leftism 22'], difficulty: 'hard', artist: 'Leftfield', term: 'leftfield leftism' },
  { slug: 'exit-planet-dust', prompt: COVER, correct: 'Exit Planet Dust', incorrect: ['Dig Your Own Hole', 'Surrender', 'Come With Us'], difficulty: 'hard', artist: 'The Chemical Brothers', term: 'chemical brothers exit planet dust' },
  { slug: 'surrender-cb', prompt: COVER, correct: 'Surrender', incorrect: ['Exit Planet Dust', 'Dig Your Own Hole', 'Push the Button'], difficulty: 'hard', artist: 'The Chemical Brothers', term: 'chemical brothers surrender' },
  { slug: 'music-for-the-jilted', prompt: COVER, correct: 'Music for the Jilted Generation', incorrect: ['The Fat of the Land', 'Experience', 'Invaders Must Die'], difficulty: 'hard', artist: 'The Prodigy', term: 'prodigy music for the jilted generation' },
  { slug: 'experience-prodigy', prompt: COVER, correct: 'Experience', incorrect: ['Music for the Jilted Generation', 'The Fat of the Land', 'Always Outnumbered'], difficulty: 'hard', artist: 'The Prodigy', term: 'prodigy experience' },
  { slug: 'in-sides', prompt: COVER, correct: 'In Sides', incorrect: ['Orbital 2', 'Snivilisation', 'The Middle of Nowhere'], difficulty: 'hard', artist: 'Orbital', term: 'orbital in sides' },
  { slug: 'music-has-the-right', prompt: COVER, correct: 'Music Has the Right to Children', incorrect: ['Geogaddi', 'The Campfire Headphase', 'Tomorrow’s Harvest'], difficulty: 'hard', artist: 'Boards of Canada', term: 'boards of canada music has the right to children' },
  { slug: 'geogaddi', prompt: COVER, correct: 'Geogaddi', incorrect: ['Music Has the Right to Children', 'The Campfire Headphase', 'Tomorrow’s Harvest'], difficulty: 'hard', artist: 'Boards of Canada', term: 'boards of canada geogaddi' },
  { slug: 'untrue', prompt: COVER, correct: 'Untrue', incorrect: ['Burial', 'Tunes 2011-2019', 'Street Halo'], difficulty: 'hard', artist: 'Burial', term: 'burial untrue' },
  { slug: 'richard-d-james', prompt: COVER, correct: 'Richard D. James Album', incorrect: ['Drukqs', 'Syro', 'Come to Daddy'], difficulty: 'hard', artist: 'Aphex Twin', term: 'aphex twin richard d james album' },
  { slug: 'drukqs', prompt: COVER, correct: 'Drukqs', incorrect: ['Syro', 'Richard D. James Album', 'Collapse'], difficulty: 'hard', artist: 'Aphex Twin', term: 'aphex twin drukqs' },
  { slug: 'melody-am', prompt: COVER, correct: 'Melody A.M.', incorrect: ['The Understanding', 'Junior', 'Senior'], difficulty: 'hard', artist: 'Röyksopp', term: 'royksopp melody am' },
  { slug: 'talkie-walkie', prompt: COVER, correct: 'Talkie Walkie', incorrect: ['Moon Safari', '10 000 Hz Legend', 'Pocket Symphony'], difficulty: 'hard', artist: 'Air', term: 'air talkie walkie' },
  { slug: '808s', prompt: COVER, correct: '808s & Heartbreak', incorrect: ['Graduation', 'Late Registration', 'Yeezus'], difficulty: 'hard', artist: 'Kanye West', term: 'kanye west 808s and heartbreak' },
  { slug: 'graduation', prompt: COVER, correct: 'Graduation', incorrect: ['Late Registration', '808s & Heartbreak', 'The College Dropout'], difficulty: 'hard', artist: 'Kanye West', term: 'kanye west graduation' },
  { slug: 'late-registration', prompt: COVER, correct: 'Late Registration', incorrect: ['The College Dropout', 'Graduation', 'Yeezus'], difficulty: 'hard', artist: 'Kanye West', term: 'kanye west late registration' },
  { slug: 'the-blueprint', prompt: COVER, correct: 'The Blueprint', incorrect: ['Reasonable Doubt', 'The Black Album', '4:44'], difficulty: 'hard', artist: 'JAY-Z', term: 'jay z the blueprint' },
  { slug: 'reasonable-doubt', prompt: COVER, correct: 'Reasonable Doubt', incorrect: ['The Blueprint', 'The Black Album', 'Vol. 2… Hard Knock Life'], difficulty: 'medium', artist: 'JAY-Z', term: 'jay z reasonable doubt' },
  { slug: 'stankonia', prompt: COVER, correct: 'Stankonia', incorrect: ['Speakerboxxx/The Love Below', 'Aquemini', 'ATLiens'], difficulty: 'medium', artist: 'OutKast', term: 'outkast stankonia' },
  { slug: 'aquemini', prompt: COVER, correct: 'Aquemini', incorrect: ['Stankonia', 'ATLiens', 'Speakerboxxx/The Love Below'], difficulty: 'hard', artist: 'OutKast', term: 'outkast aquemini' },
  { slug: 'three-feet-high', prompt: COVER, correct: '3 Feet High and Rising', incorrect: ['De La Soul Is Dead', 'Buhloone Mindstate', 'Stakes Is High'], difficulty: 'hard', artist: 'De La Soul', term: 'de la soul 3 feet high and rising' },
  { slug: 'section-80', prompt: COVER, correct: 'Section.80', incorrect: ['good kid, m.A.A.d city', 'To Pimp a Butterfly', 'DAMN.'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'kendrick lamar section 80' },
  { slug: 'mr-morale', prompt: COVER, correct: 'Mr. Morale & the Big Steppers', incorrect: ['DAMN.', 'To Pimp a Butterfly', 'good kid, m.A.A.d city'], difficulty: 'medium', artist: 'Kendrick Lamar', term: 'kendrick lamar mr morale and the big steppers' },
  { slug: 'nostalgia-ultra', prompt: COVER, correct: 'Nostalgia, Ultra', incorrect: ['Channel Orange', 'Blonde', 'Endless'], difficulty: 'hard', artist: 'Frank Ocean', term: 'frank ocean nostalgia ultra' },
  { slug: 'starboy', prompt: COVER, correct: 'Starboy', incorrect: ['After Hours', 'Beauty Behind the Madness', 'Dawn FM'], difficulty: 'medium', artist: 'The Weeknd', term: 'the weeknd starboy' },
  { slug: 'dawn-fm', prompt: COVER, correct: 'Dawn FM', incorrect: ['After Hours', 'Starboy', 'Beauty Behind the Madness'], difficulty: 'medium', artist: 'The Weeknd', term: 'the weeknd dawn fm' },
  { slug: 'when-we-all-fall-asleep', prompt: COVER, correct: 'When We All Fall Asleep, Where Do We Go?', incorrect: ['Happier Than Ever', 'Hit Me Hard and Soft', 'Don’t Smile at Me'], difficulty: 'medium', artist: 'Billie Eilish', term: 'billie eilish when we all fall asleep where do we go' },
  { slug: 'happier-than-ever', prompt: COVER, correct: 'Happier Than Ever', incorrect: ['When We All Fall Asleep, Where Do We Go?', 'Hit Me Hard and Soft', 'Don’t Smile at Me'], difficulty: 'medium', artist: 'Billie Eilish', term: 'billie eilish happier than ever' },
  { slug: 'fine-line', prompt: COVER, correct: 'Fine Line', incorrect: ['Harry Styles', 'Harry’s House', 'Love On Tour'], difficulty: 'medium', artist: 'Harry Styles', term: 'harry styles fine line' },
  { slug: 'harrys-house', prompt: COVER, correct: 'Harry’s House', incorrect: ['Fine Line', 'Harry Styles', 'As It Was'], difficulty: 'medium', artist: 'Harry Styles', term: 'harry styles harrys house' },
  { slug: 'future-nostalgia', prompt: COVER, correct: 'Future Nostalgia', incorrect: ['Dua Lipa', 'Radical Optimism', 'Club Future Nostalgia'], difficulty: 'medium', artist: 'Dua Lipa', term: 'dua lipa future nostalgia' },
  { slug: 'ultraviolence', prompt: COVER, correct: 'Ultraviolence', incorrect: ['Born to Die', 'Honeymoon', 'Norman Fucking Rockwell!'], difficulty: 'hard', artist: 'Lana Del Rey', term: 'lana del rey ultraviolence' },
  { slug: 'honeymoon-ldr', prompt: COVER, correct: 'Honeymoon', incorrect: ['Born to Die', 'Ultraviolence', 'Lust for Life'], difficulty: 'hard', artist: 'Lana Del Rey', term: 'lana del rey honeymoon' },
  { slug: 'ceremonials', prompt: COVER, correct: 'Ceremonials', incorrect: ['Lungs', 'How Big, How Blue, How Beautiful', 'High as Hope'], difficulty: 'hard', artist: 'Florence + The Machine', term: 'florence and the machine ceremonials' },
  { slug: 'visions-of-a-life', prompt: COVER, correct: 'Visions of a Life', incorrect: ['My Love Is Cool', 'Blue Weekend', 'Clearing the Path'], difficulty: 'hard', artist: 'Wolf Alice', term: 'wolf alice visions of a life' },
  { slug: 'my-love-is-cool', prompt: COVER, correct: 'My Love Is Cool', incorrect: ['Visions of a Life', 'Blue Weekend', 'Clearing the Path'], difficulty: 'hard', artist: 'Wolf Alice', term: 'wolf alice my love is cool' },
  { slug: 'brutalism', prompt: COVER, correct: 'Brutalism', incorrect: ['Joy as an Act of Resistance', 'Ultra Mono', 'Crawler'], difficulty: 'hard', artist: 'IDLES', term: 'idles brutalism' },
  { slug: 'dogrel', prompt: COVER, correct: 'Dogrel', incorrect: ['A Hero’s Death', 'Skinty Fia', 'Romance'], difficulty: 'hard', artist: 'Fontaines D.C.', term: 'fontaines dc dogrel' },
  { slug: 'grey-area', prompt: COVER, correct: 'Grey Area', incorrect: ['Sometimes I Might Be Introvert', 'Stillness in Wonderland', 'No Thank You'], difficulty: 'hard', artist: 'Little Simz', term: 'little simz grey area' },
  { slug: 'collapsed-in-sunbeams', prompt: COVER, correct: 'Collapsed in Sunbeams', incorrect: ['My Soft Machine', 'Super Sad Generation', 'Softly'], difficulty: 'hard', artist: 'Arlo Parks', term: 'arlo parks collapsed in sunbeams' },
  { slug: 'hypersonic-missiles', prompt: COVER, correct: 'Hypersonic Missiles', incorrect: ['Seventeen Going Under', 'People Watching', 'Dead Boys'], difficulty: 'medium', artist: 'Sam Fender', term: 'sam fender hypersonic missiles' },
  { slug: 'the-doors-album', prompt: COVER, correct: 'The Doors', incorrect: ['Strange Days', 'L.A. Woman', 'Morrison Hotel'], difficulty: 'hard', artist: 'The Doors', term: 'the doors debut album' },
  { slug: 'strange-days', prompt: COVER, correct: 'Strange Days', incorrect: ['The Doors', 'L.A. Woman', 'Waiting for the Sun'], difficulty: 'medium', artist: 'The Doors', term: 'the doors strange days' },
  { slug: 'are-you-experienced', prompt: COVER, correct: 'Are You Experienced', incorrect: ['Axis: Bold as Love', 'Electric Ladyland', 'Band of Gypsys'], difficulty: 'hard', artist: 'Jimi Hendrix', term: 'jimi hendrix are you experienced' },
  { slug: 'disraeli-gears', prompt: COVER, correct: 'Disraeli Gears', incorrect: ['Fresh Cream', 'Wheels of Fire', 'Goodbye'], difficulty: 'hard', artist: 'Cream', term: 'cream disraeli gears' },
  { slug: 'music-from-big-pink', prompt: COVER, correct: 'Music from Big Pink', incorrect: ['The Band', 'Stage Fright', 'Northern Lights'], difficulty: 'medium', artist: 'The Band', term: 'the band music from big pink' },
  { slug: 'pet-sounds', prompt: COVER, correct: 'Pet Sounds', incorrect: ['Surf’s Up', 'Smiley Smile', 'Sunflower'], difficulty: 'medium', artist: 'The Beach Boys', term: 'beach boys pet sounds' },
  { slug: 'blue-joni', prompt: COVER, correct: 'Blue', incorrect: ['Court and Spark', 'Ladies of the Canyon', 'Hejira'], difficulty: 'hard', artist: 'Joni Mitchell', term: 'joni mitchell blue' },
  { slug: 'tapestry', prompt: COVER, correct: 'Tapestry', incorrect: ['Music', 'Rhymes & Reasons', 'Wrap Around Joy'], difficulty: 'hard', artist: 'Carole King', term: 'carole king tapestry' },
  { slug: 'bridge-over-troubled', prompt: COVER, correct: 'Bridge over Troubled Water', incorrect: ['Sounds of Silence', 'Bookends', 'Parsley, Sage, Rosemary and Thyme'], difficulty: 'medium', artist: 'Simon & Garfunkel', term: 'simon and garfunkel bridge over troubled water' },
  { slug: 'harvest-neil', prompt: COVER, correct: 'Harvest', incorrect: ['After the Gold Rush', 'On the Beach', 'Tonight’s the Night'], difficulty: 'hard', artist: 'Neil Young', term: 'neil young harvest' },
  { slug: 'after-the-gold-rush', prompt: COVER, correct: 'After the Gold Rush', incorrect: ['Harvest', 'On the Beach', 'Zuma'], difficulty: 'hard', artist: 'Neil Young', term: 'neil young after the gold rush' },
  { slug: 'blood-on-the-tracks', prompt: COVER, correct: 'Blood on the Tracks', incorrect: ['Highway 61 Revisited', 'Blonde on Blonde', 'Desire'], difficulty: 'hard', artist: 'Bob Dylan', term: 'bob dylan blood on the tracks' },
  { slug: 'highway-61', prompt: COVER, correct: 'Highway 61 Revisited', incorrect: ['Blonde on Blonde', 'Blood on the Tracks', 'Bringing It All Back Home'], difficulty: 'hard', artist: 'Bob Dylan', term: 'bob dylan highway 61 revisited' },
  { slug: 'violator-dm', prompt: COVER, correct: 'Music for the Masses', incorrect: ['Violator', 'Songs of Faith and Devotion', 'Black Celebration'], difficulty: 'hard', artist: 'Depeche Mode', term: 'depeche mode music for the masses' },
  { slug: 'black-celebration', prompt: COVER, correct: 'Black Celebration', incorrect: ['Violator', 'Music for the Masses', 'Some Great Reward'], difficulty: 'hard', artist: 'Depeche Mode', term: 'depeche mode black celebration' },
  { slug: 'faith-cure', prompt: COVER, correct: 'Faith', incorrect: ['Disintegration', 'Pornography', 'Seventeen Seconds'], difficulty: 'hard', artist: 'The Cure', term: 'the cure faith' },
  { slug: 'pornography-cure', prompt: COVER, correct: 'Pornography', incorrect: ['Disintegration', 'Faith', 'The Head on the Door'], difficulty: 'hard', artist: 'The Cure', term: 'the cure pornography' },
  { slug: 'doolittle', prompt: COVER, correct: 'Doolittle', incorrect: ['Surfer Rosa', 'Bossanova', 'Trompe le Monde'], difficulty: 'hard', artist: 'Pixies', term: 'pixies doolittle' },
  { slug: 'surfer-rosa', prompt: COVER, correct: 'Surfer Rosa', incorrect: ['Doolittle', 'Bossanova', 'Trompe le Monde'], difficulty: 'medium', artist: 'Pixies', term: 'pixies surfer rosa' },
  { slug: 'heaven-or-las-vegas', prompt: COVER, correct: 'Heaven or Las Vegas', incorrect: ['Treasure', 'Blue Bell Knoll', 'Victorialand'], difficulty: 'hard', artist: 'Cocteau Twins', term: 'cocteau twins heaven or las vegas' },
  { slug: 'treasure-ct', prompt: COVER, correct: 'Treasure', incorrect: ['Heaven or Las Vegas', 'Blue Bell Knoll', 'Garlands'], difficulty: 'hard', artist: 'Cocteau Twins', term: 'cocteau twins treasure' },
];
