import type { Difficulty } from '../src/questions/types';

export interface TuneSpec {
  slug: string;
  prompt: string;
  correct: string;
  incorrect: string[];
  difficulty: Difficulty;
  artist: string;
  term: string;
  /** Both measured by `npm run tune-audit`, not guessed. See `tunes-round.md`. */
  previewStart?: number;
  previewSeconds?: number;
}

export const TUNES_ROUND_LENGTH = 15;
export const TUNES_MIN_PACK = TUNES_ROUND_LENGTH * 3;

const NAME = 'Name this tune.';

/**
 * UK-office karaoke, not the iTunes chart. Distractors are other artists — the
 * Bach-four problem from the synth pack. Titles only, unless two famous songs
 * share a name.
 */
export const TUNE_SPECS: TuneSpec[] = [
  { slug: 'mr-brightside', prompt: NAME, correct: 'Mr. Brightside', incorrect: ['Take Me Out', 'Last Nite', 'Somebody Told Me'], difficulty: 'easy', artist: 'The Killers', term: 'mr brightside killers' },
  { slug: 'wonderwall', prompt: NAME, correct: 'Wonderwall', incorrect: ['Champagne Supernova', 'Parklife', 'Yellow'], difficulty: 'easy', artist: 'Oasis', term: 'wonderwall oasis' },
  { slug: 'dont-look-back-in-anger', prompt: NAME, correct: "Don't Look Back in Anger", incorrect: ['Wonderwall', 'Common People', 'Song 2'], difficulty: 'easy', artist: 'Oasis', term: "don't look back in anger oasis" },
  { slug: 'bohemian-rhapsody', prompt: NAME, correct: 'Bohemian Rhapsody', incorrect: ['We Are the Champions', 'Piano Man', 'Tiny Dancer'], difficulty: 'easy', artist: 'Queen', term: 'bohemian rhapsody queen' },
  { slug: 'we-will-rock-you', prompt: NAME, correct: 'We Will Rock You', incorrect: ['We Are the Champions', 'Seven Nation Army', 'Song 2'], difficulty: 'easy', artist: 'Queen', term: 'we will rock you queen' },
  { slug: 'hey-jude', prompt: NAME, correct: 'Hey Jude', incorrect: ['Let It Be', 'Sweet Caroline', 'Angels'], difficulty: 'easy', artist: 'The Beatles', term: 'hey jude beatles' },
  { slug: 'sweet-caroline', prompt: NAME, correct: 'Sweet Caroline', incorrect: ['Delilah', "I'm a Believer", 'Build Me Up Buttercup'], difficulty: 'easy', artist: 'Neil Diamond', term: 'sweet caroline neil diamond' },
  { slug: 'angels', prompt: NAME, correct: 'Angels', incorrect: ['Wonderwall', "She's the One", 'Let Me Entertain You'], difficulty: 'easy', artist: 'Robbie Williams', term: 'angels robbie williams' },
  { slug: 'come-on-eileen', prompt: NAME, correct: 'Come On Eileen', incorrect: ['Baggy Trousers', 'Our House', 'Town Called Malice'], difficulty: 'easy', artist: 'Dexys', term: 'come on eileen dexys' },
  { slug: 'livin-on-a-prayer', prompt: NAME, correct: "Livin' on a Prayer", incorrect: ["Sweet Child o' Mine", "Summer of '69", "Don't Stop Believin'"], difficulty: 'easy', artist: 'Bon Jovi', term: "livin on a prayer bon jovi" },
  { slug: 'summer-of-69', prompt: NAME, correct: "Summer of '69", incorrect: ['Run to You', 'Born to Run', 'Glory Days'], difficulty: 'easy', artist: 'Bryan Adams', term: "summer of 69 bryan adams" },
  { slug: 'dancing-queen', prompt: NAME, correct: 'Dancing Queen', incorrect: ['Waterloo', 'Mamma Mia', "I Wanna Dance with Somebody"], difficulty: 'easy', artist: 'ABBA', term: 'dancing queen abba' },
  { slug: 'wannabe', prompt: NAME, correct: 'Wannabe', incorrect: ['2 Become 1', '...Baby One More Time', 'Genie in a Bottle'], difficulty: 'easy', artist: 'Spice Girls', term: 'wannabe spice girls' },
  { slug: 'dont-stop-believin', prompt: NAME, correct: "Don't Stop Believin'", incorrect: ['Livin on a Prayer', 'Sweet Caroline', 'Mr. Brightside'], difficulty: 'easy', artist: 'Journey', term: "don't stop believin journey" },
  { slug: 'song-2', prompt: NAME, correct: 'Song 2', incorrect: ['Parklife', 'Seven Nation Army', 'Smells Like Teen Spirit'], difficulty: 'easy', artist: 'Blur', term: 'song 2 blur' },
  { slug: 'common-people', prompt: NAME, correct: 'Common People', incorrect: ['Disco 2000', 'Country House', "Don't Look Back in Anger"], difficulty: 'easy', artist: 'Pulp', term: 'common people pulp' },
  { slug: 'take-me-out', prompt: NAME, correct: 'Take Me Out', incorrect: ['Mr. Brightside', 'I Bet You Look Good on the Dancefloor', 'Last Nite'], difficulty: 'easy', artist: 'Franz Ferdinand', term: 'take me out franz ferdinand' },
  { slug: 'seven-nation-army', prompt: NAME, correct: 'Seven Nation Army', incorrect: ['Song 2', 'We Will Rock You', 'Chelsea Dagger'], difficulty: 'easy', artist: 'The White Stripes', term: 'seven nation army white stripes' },
  { slug: 'rolling-in-the-deep', prompt: NAME, correct: 'Rolling in the Deep', incorrect: ['Someone Like You', 'Set Fire to the Rain', 'Halo'], difficulty: 'easy', artist: 'Adele', term: 'rolling in the deep adele' },
  { slug: 'shape-of-you', prompt: NAME, correct: 'Shape of You', incorrect: ['Thinking Out Loud', 'Uptown Funk', 'Happy'], difficulty: 'easy', artist: 'Ed Sheeran', term: 'shape of you ed sheeran' },
  { slug: 'uptown-funk', prompt: NAME, correct: 'Uptown Funk', incorrect: ['Happy', 'Get Lucky', 'Treasure'], difficulty: 'easy', artist: 'Mark Ronson', term: 'uptown funk mark ronson' },
  { slug: 'billie-jean', prompt: NAME, correct: 'Billie Jean', incorrect: ['Thriller', 'Beat It', 'Superstition'], difficulty: 'easy', artist: 'Michael Jackson', term: 'billie jean michael jackson' },
  { slug: 'hotel-california', prompt: NAME, correct: 'Hotel California', incorrect: ['Stairway to Heaven', 'Wish You Were Here', 'Go Your Own Way'], difficulty: 'easy', artist: 'Eagles', term: 'hotel california eagles', previewStart: 8 },
  { slug: 'sweet-child', prompt: NAME, correct: "Sweet Child o' Mine", incorrect: ["Livin' on a Prayer", 'Welcome to the Jungle', 'November Rain'], difficulty: 'easy', artist: "Guns N' Roses", term: 'sweet child o mine guns' },
  { slug: 'delilah', prompt: NAME, correct: 'Delilah', incorrect: ["It's Not Unusual", 'Sweet Caroline', 'Green Green Grass of Home'], difficulty: 'easy', artist: 'Tom Jones', term: 'delilah tom jones' },
  { slug: 'yellow', prompt: NAME, correct: 'Yellow', incorrect: ['The Scientist', 'Wonderwall', 'Chasing Cars'], difficulty: 'easy', artist: 'Coldplay', term: 'yellow coldplay' },
  { slug: 'chasing-cars', prompt: NAME, correct: 'Chasing Cars', incorrect: ['Run', 'Yellow', 'Fix You'], difficulty: 'easy', artist: 'Snow Patrol', term: 'chasing cars snow patrol' },
  { slug: 'i-bet-you-look-good', prompt: NAME, correct: 'I Bet You Look Good on the Dancefloor', incorrect: ['When the Sun Goes Down', 'Take Me Out', 'Fluorescent Adolescent'], difficulty: 'easy', artist: 'Arctic Monkeys', term: 'i bet you look good on the dancefloor' },
  { slug: 'sex-on-fire', prompt: NAME, correct: 'Sex on Fire', incorrect: ['Use Somebody', 'Mr. Brightside', 'Take Me Out'], difficulty: 'easy', artist: 'Kings of Leon', term: 'sex on fire kings of leon' },
  { slug: 'take-on-me', prompt: NAME, correct: 'Take On Me', incorrect: ['The Sun Always Shines on TV', 'Wake Me Up Before You Go-Go', 'Girls Just Want to Have Fun'], difficulty: 'easy', artist: 'a-ha', term: 'take on me a-ha' },
  { slug: 'careless-whisper', prompt: NAME, correct: 'Careless Whisper', incorrect: ['Last Christmas', 'Wake Me Up Before You Go-Go', 'Faith'], difficulty: 'easy', artist: 'George Michael', term: 'careless whisper george michael' },
  { slug: 'your-song', prompt: NAME, correct: 'Your Song', incorrect: ['Rocket Man', 'Tiny Dancer', "Don't Let the Sun Go Down on Me"], difficulty: 'easy', artist: 'Elton John', term: 'your song elton john' },
  { slug: 'tainted-love', prompt: NAME, correct: 'Tainted Love', incorrect: ["Don't You Want Me", 'Sweet Dreams (Are Made of This)', 'Blue Monday'], difficulty: 'medium', artist: 'Soft Cell', term: 'tainted love soft cell' },
  { slug: 'dont-you-want-me', prompt: NAME, correct: "Don't You Want Me", incorrect: ['Tainted Love', 'The Model', 'Vienna'], difficulty: 'medium', artist: 'The Human League', term: "don't you want me human league" },
  { slug: 'blue-monday', prompt: NAME, correct: 'Blue Monday', incorrect: ['Love Will Tear Us Apart', 'Temptation', 'Bizarre Love Triangle'], difficulty: 'medium', artist: 'New Order', term: 'blue monday new order' },
  { slug: 'heroes', prompt: NAME, correct: 'Heroes', incorrect: ["Let's Dance", 'Starman', 'Under Pressure'], difficulty: 'medium', artist: 'David Bowie', term: 'heroes david bowie' },
  { slug: 'under-pressure', prompt: NAME, correct: 'Under Pressure', incorrect: ['Another One Bites the Dust', 'Heroes', 'Ice Ice Baby'], difficulty: 'medium', artist: 'Queen', term: 'under pressure queen bowie' },
  { slug: 'creep', prompt: NAME, correct: 'Creep', incorrect: ['Karma Police', 'Wonderwall', 'Losing My Religion'], difficulty: 'medium', artist: 'Radiohead', term: 'creep radiohead' },
  { slug: 'parklife', prompt: NAME, correct: 'Parklife', incorrect: ['Country House', 'Common People', 'Song 2'], difficulty: 'medium', artist: 'Blur', term: 'parklife blur' },
  { slug: 'bittersweet-symphony', prompt: NAME, correct: 'Bitter Sweet Symphony', incorrect: ['The Drugs Don’t Work', 'Lucky Man', 'Why Does It Always Rain on Me?'], difficulty: 'medium', artist: 'The Verve', term: 'bitter sweet symphony verve' },
  { slug: 'why-does-it-always-rain', prompt: NAME, correct: 'Why Does It Always Rain on Me?', incorrect: ["She's the One", 'Mambo No. 5', 'Flying Without Wings'], difficulty: 'medium', artist: 'Travis', term: 'why does it always rain on me travis' },
  { slug: 'torn', prompt: NAME, correct: 'Torn', incorrect: ['...Baby One More Time', 'Genie in a Bottle', 'Believe'], difficulty: 'medium', artist: 'Natalie Imbruglia', term: 'torn natalie imbruglia' },
  { slug: 'believe', prompt: NAME, correct: 'Believe', incorrect: ['If I Could Turn Back Time', 'Heart of Glass', 'Hung Up'], difficulty: 'medium', artist: 'Cher', term: 'believe cher' },
  { slug: 'africa', prompt: NAME, correct: 'Africa', incorrect: ['Hold the Line', 'Rosanna', 'Everybody Wants to Rule the World'], difficulty: 'medium', artist: 'Toto', term: 'africa toto' },
  { slug: 'everybody-wants-to-rule', prompt: NAME, correct: 'Everybody Wants to Rule the World', incorrect: ['Shout', 'Mad World', 'Africa'], difficulty: 'medium', artist: 'Tears for Fears', term: 'everybody wants to rule the world' },
  { slug: 'sweet-dreams', prompt: NAME, correct: 'Sweet Dreams (Are Made of This)', incorrect: ['Tainted Love', 'Here Comes the Rain Again', 'Relax'], difficulty: 'medium', artist: 'Eurythmics', term: 'sweet dreams eurythmics' },
  { slug: 'relax', prompt: NAME, correct: 'Relax', incorrect: ['Two Tribes', 'The Power of Love', 'Welcome to the Pleasuredome'], difficulty: 'medium', artist: 'Frankie Goes to Hollywood', term: 'relax frankie goes to hollywood' },
  { slug: 'vienna', prompt: NAME, correct: 'Vienna', incorrect: ['Fade to Grey', "Don't You Want Me", 'Cars'], difficulty: 'medium', artist: 'Ultravox', term: 'vienna ultravox' },
  { slug: 'whole-of-the-moon', prompt: NAME, correct: 'The Whole of the Moon', incorrect: ['This Is the Sea', 'Purple Rain', "Don't You (Forget About Me)"], difficulty: 'medium', artist: 'The Waterboys', term: 'the whole of the moon waterboys' },
  { slug: 'purple-rain', prompt: NAME, correct: 'Purple Rain', incorrect: ['Kiss', 'When Doves Cry', '1999'], difficulty: 'medium', artist: 'Prince', term: 'purple rain prince' },
  { slug: 'smells-like-teen-spirit', prompt: NAME, correct: 'Smells Like Teen Spirit', incorrect: ['Come as You Are', 'Even Flow', 'Lithium'], difficulty: 'medium', artist: 'Nirvana', term: 'smells like teen spirit nirvana' },
  { slug: 'losing-my-religion', prompt: NAME, correct: 'Losing My Religion', incorrect: ['Everybody Hurts', 'Creep', 'Zombie'], difficulty: 'medium', artist: 'R.E.M.', term: 'losing my religion rem' },
  { slug: 'zombie', prompt: NAME, correct: 'Zombie', incorrect: ['Linger', 'Dreams', 'Nothing Compares 2 U'], difficulty: 'medium', artist: 'The Cranberries', term: 'zombie cranberries' },
  { slug: 'nothing-compares', prompt: NAME, correct: 'Nothing Compares 2 U', incorrect: ['Zombie', 'I Will Always Love You', 'Hero'], difficulty: 'medium', artist: 'Sinéad O’Connor', term: 'nothing compares 2 u sinead' },
  { slug: 'i-will-always-love-you', prompt: NAME, correct: 'I Will Always Love You', incorrect: ['My Heart Will Go On', 'Hero', 'Without You'], difficulty: 'easy', artist: 'Whitney Houston', term: 'i will always love you whitney houston' },
  { slug: 'my-heart-will-go-on', prompt: NAME, correct: 'My Heart Will Go On', incorrect: ['I Will Always Love You', 'Think Twice', 'Eternal Flame'], difficulty: 'easy', artist: 'Celine Dion', term: 'my heart will go on celine dion' },
  { slug: 'think-twice', prompt: NAME, correct: 'Think Twice', incorrect: ['Without You', 'Love Is All Around', 'Stay Another Day'], difficulty: 'medium', artist: 'Celine Dion', term: 'think twice celine dion' },
  { slug: 'love-is-all-around', prompt: NAME, correct: 'Love Is All Around', incorrect: ["You're the One That I Want", 'Stay Another Day', 'Angels'], difficulty: 'medium', artist: 'Wet Wet Wet', term: 'love is all around wet wet wet' },
  { slug: 'stay-another-day', prompt: NAME, correct: 'Stay Another Day', incorrect: ['Love Is All Around', 'Fairytale of New York', 'Last Christmas'], difficulty: 'medium', artist: 'East 17', term: 'stay another day east 17' },
  { slug: 'last-christmas', prompt: NAME, correct: 'Last Christmas', incorrect: ['Stay Another Day', 'Fairytale of New York', 'Merry Christmas Everyone'], difficulty: 'easy', artist: 'Wham!', term: 'last christmas wham' },
  { slug: 'fairytale-of-new-york', prompt: NAME, correct: 'Fairytale of New York', incorrect: ['Last Christmas', 'A Spaceman Came Travelling', 'Stop the Cavalry'], difficulty: 'easy', artist: 'The Pogues', term: 'fairytale of new york pogues' },
  { slug: 'do-i-wanna-know', prompt: NAME, correct: 'Do I Wanna Know?', incorrect: ['R U Mine?', 'Fluorescent Adolescent', 'Use Somebody'], difficulty: 'medium', artist: 'Arctic Monkeys', term: 'do i wanna know arctic monkeys' },
  { slug: 'use-somebody', prompt: NAME, correct: 'Use Somebody', incorrect: ['Sex on Fire', 'Mr. Brightside', 'Somebody Told Me'], difficulty: 'medium', artist: 'Kings of Leon', term: 'use somebody kings of leon' },
  { slug: 'somebody-told-me', prompt: NAME, correct: 'Somebody Told Me', incorrect: ['Mr. Brightside', 'Human', 'When You Were Young'], difficulty: 'medium', artist: 'The Killers', term: 'somebody told me killers' },
  { slug: 'human', prompt: NAME, correct: 'Human', incorrect: ['Somebody Told Me', 'Mr. Brightside', "Don't Stop Believin'"], difficulty: 'hard', artist: 'The Killers', term: 'human the killers' },
  { slug: 'fluorescent-adolescent', prompt: NAME, correct: 'Fluorescent Adolescent', incorrect: ['I Bet You Look Good on the Dancefloor', 'Do I Wanna Know?', 'Teddy Picker'], difficulty: 'hard', artist: 'Arctic Monkeys', term: 'fluorescent adolescent arctic monkeys' },
  { slug: 'country-house', prompt: NAME, correct: 'Country House', incorrect: ['Parklife', 'Common People', 'Charmless Man'], difficulty: 'hard', artist: 'Blur', term: 'country house blur' },
  { slug: 'disco-2000', prompt: NAME, correct: 'Disco 2000', incorrect: ['Common People', 'Sorted for E’s & Wizz', 'Parklife'], difficulty: 'hard', artist: 'Pulp', term: 'disco 2000 pulp' },
  { slug: 'karma-police', prompt: NAME, correct: 'Karma Police', incorrect: ['Creep', 'No Surprises', 'Paranoid Android'], difficulty: 'hard', artist: 'Radiohead', term: 'karma police radiohead' },
  { slug: 'no-surprises', prompt: NAME, correct: 'No Surprises', incorrect: ['Karma Police', 'Street Spirit (Fade Out)', 'Fake Plastic Trees'], difficulty: 'hard', artist: 'Radiohead', term: 'no surprises radiohead' },
  { slug: 'love-will-tear-us-apart', prompt: NAME, correct: 'Love Will Tear Us Apart', incorrect: ['Blue Monday', "She's Lost Control", 'Transmission'], difficulty: 'hard', artist: 'Joy Division', term: 'love will tear us apart joy division' },
  { slug: 'mad-world', prompt: NAME, correct: 'Mad World', incorrect: ['Everybody Wants to Rule the World', 'Pale Shelter', 'True'], difficulty: 'hard', artist: 'Tears for Fears', term: 'mad world tears for fears' },
  { slug: 'baggy-trousers', prompt: NAME, correct: 'Baggy Trousers', incorrect: ['Our House', 'Come On Eileen', 'House of Fun'], difficulty: 'hard', artist: 'Madness', term: 'baggy trousers madness' },
  { slug: 'our-house', prompt: NAME, correct: 'Our House', incorrect: ['Baggy Trousers', 'Driving in My Car', 'House of Fun'], difficulty: 'hard', artist: 'Madness', term: 'our house madness' },
  { slug: 'town-called-malice', prompt: NAME, correct: 'A Town Called Malice', incorrect: ["That's Entertainment", 'Going Underground', 'Come On Eileen'], difficulty: 'hard', artist: 'The Jam', term: 'town called malice jam' },
  { slug: 'going-underground', prompt: NAME, correct: 'Going Underground', incorrect: ['A Town Called Malice', "That's Entertainment", 'Down in the Tube Station at Midnight'], difficulty: 'hard', artist: 'The Jam', term: 'going underground jam' },
  { slug: 'there-she-goes', prompt: NAME, correct: 'There She Goes', incorrect: ['Waterfall', 'She Bangs the Drums', 'I Am the Resurrection'], difficulty: 'hard', artist: 'The La’s', term: 'there she goes the las' },
  { slug: 'she-bangs-the-drums', prompt: NAME, correct: 'She Bangs the Drums', incorrect: ['I Wanna Be Adored', 'Waterfall', 'There She Goes'], difficulty: 'hard', artist: 'The Stone Roses', term: 'she bangs the drums stone roses' },
  { slug: 'step-on', prompt: NAME, correct: 'Step On', incorrect: ['She Bangs the Drums', 'Written in Red', 'Kinky Afro'], difficulty: 'hard', artist: 'Happy Mondays', term: 'step on happy mondays' },

  /*
    Added 10 September 2026, after the first iTunes round played. The first
    seventy-nine were britpop, indie and eighties — one office's taste, and
    fifteen questions a round meant five rounds before the pack came back
    round. These widen it rather than deepen it: Motown, disco, stadium rock,
    nineties dance, and enough of the last fifteen years that somebody under
    thirty gets a question they know.

    Weighted towards `hard` on purpose. `HANDOVER.md` has the Ladder stalling
    once a thin bucket is spent, and `hard` was the thinnest at fifteen.
  */
  { slug: 'superstition', prompt: NAME, correct: 'Superstition', incorrect: ["Let's Stay Together", "Papa Was a Rollin' Stone", 'Get Down on It'], difficulty: 'medium', artist: 'Stevie Wonder', term: 'superstition stevie wonder' },
  { slug: 'i-heard-it-through-the-grapevine', prompt: NAME, correct: 'I Heard It Through the Grapevine', incorrect: ['My Girl', 'Dancing in the Street', "Reach Out I'll Be There"], difficulty: 'medium', artist: 'Marvin Gaye', term: 'i heard it through the grapevine marvin gaye' },
  { slug: 'my-girl', prompt: NAME, correct: 'My Girl', incorrect: ['I Heard It Through the Grapevine', "Ain't No Mountain High Enough", 'Stand by Me'], difficulty: 'medium', artist: 'The Temptations', term: 'my girl temptations' },
  { slug: 'aint-no-mountain-high-enough', prompt: NAME, correct: "Ain't No Mountain High Enough", incorrect: ['I Will Survive', 'My Girl', 'Dancing in the Street'], difficulty: 'medium', artist: 'Diana Ross', term: "ain't no mountain high enough diana ross" },
  { slug: 'stayin-alive', prompt: NAME, correct: "Stayin' Alive", incorrect: ['Le Freak', 'September', 'Y.M.C.A.'], difficulty: 'easy', artist: 'Bee Gees', term: 'stayin alive bee gees' },
  { slug: 'i-will-survive', prompt: NAME, correct: 'I Will Survive', incorrect: ['Dancing Queen', "It's Raining Men", "Stayin' Alive"], difficulty: 'easy', artist: 'Gloria Gaynor', term: 'i will survive gloria gaynor' },
  { slug: 'september', prompt: NAME, correct: 'September', incorrect: ['Le Freak', 'Good Times', "Stayin' Alive"], difficulty: 'easy', artist: 'Earth, Wind & Fire', term: 'september earth wind fire' },
  { slug: 'le-freak', prompt: NAME, correct: 'Le Freak', incorrect: ['September', 'Y.M.C.A.', 'Boogie Wonderland'], difficulty: 'hard', artist: 'Chic', term: 'le freak chic' },
  { slug: 'ymca', prompt: NAME, correct: 'Y.M.C.A.', incorrect: ["Stayin' Alive", 'In the Navy', 'September'], difficulty: 'easy', artist: 'Village People', term: 'ymca village people' },
  { slug: 'dancing-in-the-moonlight', prompt: NAME, correct: 'Dancing in the Moonlight', incorrect: ['Chasing Cars', 'Sun Is Shining', "She's the One"], difficulty: 'medium', artist: 'Toploader', term: 'dancing in the moonlight toploader' },
  { slug: 'valerie', prompt: NAME, correct: 'Valerie', incorrect: ['Rehab', 'Crazy', 'Put Your Records On'], difficulty: 'medium', artist: 'Mark Ronson', term: 'valerie mark ronson amy winehouse' },
  { slug: 'rehab', prompt: NAME, correct: 'Rehab', incorrect: ['Valerie', 'Crazy', 'American Boy'], difficulty: 'medium', artist: 'Amy Winehouse', term: 'rehab amy winehouse' },
  { slug: 'sweet-home-alabama', prompt: NAME, correct: 'Sweet Home Alabama', incorrect: ['Hotel California', 'Free Bird', 'Take It Easy'], difficulty: 'medium', artist: 'Lynyrd Skynyrd', term: 'sweet home alabama lynyrd skynyrd' },
  { slug: 'back-in-black', prompt: NAME, correct: 'Back in Black', incorrect: ['Enter Sandman', 'Paranoid', 'Smoke on the Water'], difficulty: 'easy', artist: 'AC/DC', term: 'back in black acdc' },
  { slug: 'highway-to-hell', prompt: NAME, correct: 'Highway to Hell', incorrect: ['Paranoid', 'Ace of Spades', 'Enter Sandman'], difficulty: 'medium', artist: 'AC/DC', term: 'highway to hell acdc' },
  { slug: 'enter-sandman', prompt: NAME, correct: 'Enter Sandman', incorrect: ['Back in Black', 'Paranoid', 'Smells Like Teen Spirit'], difficulty: 'medium', artist: 'Metallica', term: 'enter sandman metallica' },
  { slug: 'smoke-on-the-water', prompt: NAME, correct: 'Smoke on the Water', incorrect: ['Whole Lotta Love', 'Paranoid', 'Back in Black'], difficulty: 'medium', artist: 'Deep Purple', term: 'smoke on the water deep purple' },
  { slug: 'paranoid', prompt: NAME, correct: 'Paranoid', incorrect: ['Smoke on the Water', 'Whole Lotta Love', 'Highway to Hell'], difficulty: 'hard', artist: 'Black Sabbath', term: 'paranoid black sabbath' },
  { slug: 'whole-lotta-love', prompt: NAME, correct: 'Whole Lotta Love', incorrect: ['Smoke on the Water', 'Paranoid', 'Sunshine of Your Love'], difficulty: 'medium', artist: 'Led Zeppelin', term: 'whole lotta love led zeppelin' },
  { slug: 'stairway-to-heaven', prompt: NAME, correct: 'Stairway to Heaven', incorrect: ['Hotel California', 'Wish You Were Here', 'Free Bird'], difficulty: 'medium', artist: 'Led Zeppelin', term: 'stairway to heaven led zeppelin' },
  { slug: 'born-to-run', prompt: NAME, correct: 'Born to Run', incorrect: ['Sweet Home Alabama', 'Hungry Heart', 'Glory Days'], difficulty: 'hard', artist: 'Bruce Springsteen', term: 'born to run bruce springsteen' },
  { slug: 'baba-oriley', prompt: NAME, correct: "Baba O'Riley", incorrect: ['My Generation', 'Whole Lotta Love', "Won't Get Fooled Again"], difficulty: 'hard', artist: 'The Who', term: "baba o'riley the who" },
  { slug: 'wish-you-were-here', prompt: NAME, correct: 'Wish You Were Here', incorrect: ['Stairway to Heaven', 'Hotel California', 'Comfortably Numb'], difficulty: 'medium', artist: 'Pink Floyd', term: 'wish you were here pink floyd' },
  { slug: 'another-brick-in-the-wall', prompt: NAME, correct: 'Another Brick in the Wall', incorrect: ['Comfortably Numb', 'Wish You Were Here', 'Money'], difficulty: 'medium', artist: 'Pink Floyd', term: 'another brick in the wall pink floyd' },
  { slug: 'more-than-a-feeling', prompt: NAME, correct: 'More Than a Feeling', incorrect: ['Sweet Home Alabama', 'Carry On Wayward Son', 'Africa'], difficulty: 'hard', artist: 'Boston', term: 'more than a feeling boston' },
  { slug: 'eye-of-the-tiger', prompt: NAME, correct: 'Eye of the Tiger', incorrect: ['The Final Countdown', "Livin' on a Prayer", 'We Will Rock You'], difficulty: 'easy', artist: 'Survivor', term: 'eye of the tiger survivor' },
  { slug: 'dont-stop-me-now', prompt: NAME, correct: "Don't Stop Me Now", incorrect: ["Livin' on a Prayer", 'Mr. Blue Sky', 'Dancing Queen'], difficulty: 'easy', artist: 'Queen', term: "don't stop me now queen" },
  { slug: 'mr-blue-sky', prompt: NAME, correct: 'Mr. Blue Sky', incorrect: ["Don't Stop Me Now", 'Dancing Queen', 'Waterloo'], difficulty: 'easy', artist: 'Electric Light Orchestra', term: 'mr blue sky electric light orchestra' },
  { slug: 'the-final-countdown', prompt: NAME, correct: 'The Final Countdown', incorrect: ['Eye of the Tiger', "Livin' on a Prayer", 'Jump'], difficulty: 'easy', artist: 'Europe', term: 'the final countdown europe' },
  { slug: 'never-gonna-give-you-up', prompt: NAME, correct: 'Never Gonna Give You Up', incorrect: ['Together in Electric Dreams', 'Karma Chameleon', 'Wake Me Up Before You Go-Go'], difficulty: 'easy', artist: 'Rick Astley', term: 'never gonna give you up rick astley' },
  { slug: 'girls-just-want-to-have-fun', prompt: NAME, correct: 'Girls Just Want to Have Fun', incorrect: ['Like a Prayer', 'I Wanna Dance with Somebody', 'Take On Me'], difficulty: 'easy', artist: 'Cyndi Lauper', term: 'girls just want to have fun cyndi lauper' },
  { slug: 'like-a-prayer', prompt: NAME, correct: 'Like a Prayer', incorrect: ['Girls Just Want to Have Fun', 'I Wanna Dance with Somebody', 'Total Eclipse of the Heart'], difficulty: 'medium', artist: 'Madonna', term: 'like a prayer madonna' },
  { slug: 'wake-me-up-before-you-go-go', prompt: NAME, correct: 'Wake Me Up Before You Go-Go', incorrect: ['Karma Chameleon', 'Never Gonna Give You Up', 'Take On Me'], difficulty: 'easy', artist: 'Wham!', term: 'wake me up before you go go wham' },
  { slug: 'i-wanna-dance-with-somebody', prompt: NAME, correct: 'I Wanna Dance with Somebody', incorrect: ['Girls Just Want to Have Fun', 'Like a Prayer', 'Believe'], difficulty: 'easy', artist: 'Whitney Houston', term: 'i wanna dance with somebody whitney houston' },
  { slug: 'total-eclipse-of-the-heart', prompt: NAME, correct: 'Total Eclipse of the Heart', incorrect: ['Holding Out for a Hero', 'The Power of Love', 'I Will Always Love You'], difficulty: 'medium', artist: 'Bonnie Tyler', term: 'total eclipse of the heart bonnie tyler' },
  { slug: 'dont-you-forget-about-me', prompt: NAME, correct: "Don't You (Forget About Me)", incorrect: ['Total Eclipse of the Heart', 'The Whole of the Moon', 'Alive and Kicking'], difficulty: 'medium', artist: 'Simple Minds', term: "don't you forget about me simple minds" },
  { slug: 'baker-street', prompt: NAME, correct: 'Baker Street', incorrect: ['Vienna', 'Africa', 'Careless Whisper'], difficulty: 'hard', artist: 'Gerry Rafferty', term: 'baker street gerry rafferty' },
  { slug: 'hungry-like-the-wolf', prompt: NAME, correct: 'Hungry Like the Wolf', incorrect: ['Rio', 'Karma Chameleon', 'West End Girls'], difficulty: 'hard', artist: 'Duran Duran', term: 'hungry like the wolf duran duran' },
  { slug: 'west-end-girls', prompt: NAME, correct: 'West End Girls', incorrect: ['Blue Monday', 'Vienna', 'Fade to Grey'], difficulty: 'hard', artist: 'Pet Shop Boys', term: 'west end girls pet shop boys' },
  { slug: 'karma-chameleon', prompt: NAME, correct: 'Karma Chameleon', incorrect: ['Wake Me Up Before You Go-Go', 'Hungry Like the Wolf', 'Take On Me'], difficulty: 'medium', artist: 'Culture Club', term: 'karma chameleon culture club' },
  { slug: 'thriller', prompt: NAME, correct: 'Thriller', incorrect: ['Beat It', 'Superstition', 'Billie Jean'], difficulty: 'easy', artist: 'Michael Jackson', term: 'thriller michael jackson' },
  { slug: 'things-can-only-get-better', prompt: NAME, correct: 'Things Can Only Get Better', incorrect: ['Rhythm Is a Dancer', 'Insomnia', 'Saturday Night'], difficulty: 'hard', artist: 'D:Ream', term: 'things can only get better dream' },
  { slug: 'rhythm-is-a-dancer', prompt: NAME, correct: 'Rhythm Is a Dancer', incorrect: ['Insomnia', 'Saturday Night', 'Things Can Only Get Better'], difficulty: 'hard', artist: 'Snap!', term: 'rhythm is a dancer snap' },
  { slug: 'firestarter', prompt: NAME, correct: 'Firestarter', incorrect: ['Born Slippy', "Block Rockin' Beats", 'Insomnia'], difficulty: 'medium', artist: 'The Prodigy', term: 'firestarter the prodigy' },
  { slug: 'born-slippy', prompt: NAME, correct: 'Born Slippy', incorrect: ['Firestarter', 'Praise You', 'Insomnia'], difficulty: 'hard', artist: 'Underworld', term: 'born slippy underworld' },
  { slug: 'praise-you', prompt: NAME, correct: 'Praise You', incorrect: ['Born Slippy', 'Firestarter', 'Insomnia'], difficulty: 'hard', artist: 'Fatboy Slim', term: 'praise you fatboy slim' },
  { slug: 'insomnia', prompt: NAME, correct: 'Insomnia', incorrect: ['Rhythm Is a Dancer', 'Praise You', 'Born Slippy'], difficulty: 'hard', artist: 'Faithless', term: 'insomnia faithless' },
  { slug: 'back-for-good', prompt: NAME, correct: 'Back for Good', incorrect: ['Never Ever', 'Stay Another Day', 'Love Is All Around'], difficulty: 'medium', artist: 'Take That', term: 'back for good take that' },
  { slug: 'never-ever', prompt: NAME, correct: 'Never Ever', incorrect: ['Back for Good', '2 Become 1', 'Torn'], difficulty: 'hard', artist: 'All Saints', term: 'never ever all saints' },
  { slug: 'baby-one-more-time', prompt: NAME, correct: '...Baby One More Time', incorrect: ['Genie in a Bottle', 'Torn', 'Wannabe'], difficulty: 'easy', artist: 'Britney Spears', term: 'baby one more time britney spears' },
  { slug: 'genie-in-a-bottle', prompt: NAME, correct: 'Genie in a Bottle', incorrect: ['...Baby One More Time', 'Torn', '2 Become 1'], difficulty: 'hard', artist: 'Christina Aguilera', term: 'genie in a bottle christina aguilera' },
  { slug: 'barbie-girl', prompt: NAME, correct: 'Barbie Girl', incorrect: ['Saturday Night', 'Cotton Eye Joe', 'Macarena'], difficulty: 'easy', artist: 'Aqua', term: 'barbie girl aqua' },
  { slug: 'mmmbop', prompt: NAME, correct: 'MMMBop', incorrect: ['Barbie Girl', 'Wannabe', 'Torn'], difficulty: 'hard', artist: 'Hanson', term: 'mmmbop hanson' },
  { slug: 'everybody-hurts', prompt: NAME, correct: 'Everybody Hurts', incorrect: ['Fix You', 'Chasing Cars', 'The Scientist'], difficulty: 'medium', artist: 'R.E.M.', term: 'everybody hurts rem' },
  { slug: 'fast-car', prompt: NAME, correct: 'Fast Car', incorrect: ['Torn', 'Nothing Compares 2 U', 'Zombie'], difficulty: 'medium', artist: 'Tracy Chapman', term: 'fast car tracy chapman' },
  { slug: 'ice-ice-baby', prompt: NAME, correct: 'Ice Ice Baby', incorrect: ["U Can't Touch This", "Gangsta's Paradise", 'Under Pressure'], difficulty: 'easy', artist: 'Vanilla Ice', term: 'ice ice baby vanilla ice' },
  { slug: 'u-cant-touch-this', prompt: NAME, correct: "U Can't Touch This", incorrect: ['Ice Ice Baby', "Gangsta's Paradise", 'Superstition'], difficulty: 'medium', artist: 'MC Hammer', term: "u can't touch this mc hammer" },
  { slug: 'gangstas-paradise', prompt: NAME, correct: "Gangsta's Paradise", incorrect: ['Killing Me Softly', 'Ice Ice Baby', 'No Diggity'], difficulty: 'medium', artist: 'Coolio', term: "gangsta's paradise coolio" },
  { slug: 'killing-me-softly', prompt: NAME, correct: 'Killing Me Softly With His Song', incorrect: ["Gangsta's Paradise", 'No Diggity', 'Nothing Compares 2 U'], difficulty: 'hard', artist: 'Fugees', term: 'killing me softly fugees' },
  { slug: 'cotton-eye-joe', prompt: NAME, correct: 'Cotton Eye Joe', incorrect: ['Barbie Girl', 'Saturday Night', 'Macarena'], difficulty: 'hard', artist: 'Rednex', term: 'cotton eye joe rednex' },
  { slug: 'crazy-in-love', prompt: NAME, correct: 'Crazy in Love', incorrect: ['Umbrella', 'Hey Ya!', 'Crazy'], difficulty: 'easy', artist: 'Beyoncé', term: 'crazy in love beyonce' },
  { slug: 'toxic', prompt: NAME, correct: 'Toxic', incorrect: ['Umbrella', "Hips Don't Lie", 'Poker Face'], difficulty: 'easy', artist: 'Britney Spears', term: 'toxic britney spears' },
  { slug: 'hey-ya', prompt: NAME, correct: 'Hey Ya!', incorrect: ['Crazy in Love', 'Crazy', "Hips Don't Lie"], difficulty: 'medium', artist: 'OutKast', term: 'hey ya outkast' },
  { slug: 'chelsea-dagger', prompt: NAME, correct: 'Chelsea Dagger', incorrect: ['Ruby', 'Naive', 'Golden Skans'], difficulty: 'medium', artist: 'The Fratellis', term: 'chelsea dagger fratellis' },
  { slug: 'dry-your-eyes', prompt: NAME, correct: 'Dry Your Eyes', incorrect: ['Naive', 'Ruby', 'American Boy'], difficulty: 'hard', artist: 'The Streets', term: 'dry your eyes the streets' },
  { slug: 'naive', prompt: NAME, correct: 'Naive', incorrect: ['Chelsea Dagger', 'Ruby', 'Grace Kelly'], difficulty: 'hard', artist: 'The Kooks', term: 'naive the kooks' },
  { slug: 'grace-kelly', prompt: NAME, correct: 'Grace Kelly', incorrect: ['Naive', 'Chelsea Dagger', 'Ruby'], difficulty: 'hard', artist: 'Mika', term: 'grace kelly mika' },
  { slug: 'ruby', prompt: NAME, correct: 'Ruby', incorrect: ['Chelsea Dagger', 'I Predict a Riot', 'Naive'], difficulty: 'medium', artist: 'Kaiser Chiefs', term: 'ruby kaiser chiefs' },
  { slug: 'dakota', prompt: NAME, correct: 'Dakota', incorrect: ['Ruby', 'Chasing Cars', 'Naive'], difficulty: 'hard', artist: 'Stereophonics', term: 'dakota stereophonics' },
  { slug: 'crazy', prompt: NAME, correct: 'Crazy', incorrect: ['Hey Ya!', 'Rehab', 'Valerie'], difficulty: 'medium', artist: 'Gnarls Barkley', term: 'crazy gnarls barkley' },
  { slug: 'umbrella', prompt: NAME, correct: 'Umbrella', incorrect: ['Poker Face', 'Toxic', 'Crazy in Love'], difficulty: 'easy', artist: 'Rihanna', term: 'umbrella rihanna' },
  { slug: 'bad-romance', prompt: NAME, correct: 'Bad Romance', incorrect: ['Umbrella', 'Toxic', "Hips Don't Lie"], difficulty: 'medium', artist: 'Lady Gaga', term: 'bad romance lady gaga' },
  { slug: 'viva-la-vida', prompt: NAME, correct: 'Viva la Vida', incorrect: ['Pompeii', 'Fix You', 'Counting Stars'], difficulty: 'easy', artist: 'Coldplay', term: 'viva la vida coldplay' },
  { slug: 'hips-dont-lie', prompt: NAME, correct: "Hips Don't Lie", incorrect: ['Crazy in Love', 'Umbrella', 'Toxic'], difficulty: 'hard', artist: 'Shakira', term: "hips don't lie shakira" },
  { slug: 'american-boy', prompt: NAME, correct: 'American Boy', incorrect: ['Rehab', 'Valerie', 'Crazy'], difficulty: 'hard', artist: 'Estelle', term: 'american boy estelle' },
  { slug: 'get-lucky', prompt: NAME, correct: 'Get Lucky', incorrect: ['Happy', 'Uptown Funk', 'Rather Be'], difficulty: 'easy', artist: 'Daft Punk', term: 'get lucky daft punk' },
  { slug: 'happy', prompt: NAME, correct: 'Happy', incorrect: ['Get Lucky', 'Uptown Funk', "Can't Stop the Feeling!"], difficulty: 'easy', artist: 'Pharrell Williams', term: 'happy pharrell williams' },
  { slug: 'cant-stop-the-feeling', prompt: NAME, correct: "Can't Stop the Feeling!", incorrect: ['Happy', 'Get Lucky', 'Shake It Off'], difficulty: 'medium', artist: 'Justin Timberlake', term: "can't stop the feeling justin timberlake" },
  { slug: 'blinding-lights', prompt: NAME, correct: 'Blinding Lights', incorrect: ['Levitating', 'As It Was', "Don't Start Now"], difficulty: 'easy', artist: 'The Weeknd', term: 'blinding lights the weeknd' },
  { slug: 'dont-start-now', prompt: NAME, correct: "Don't Start Now", incorrect: ['Blinding Lights', 'As It Was', 'Levitating'], difficulty: 'hard', artist: 'Dua Lipa', term: "don't start now dua lipa" },
  { slug: 'as-it-was', prompt: NAME, correct: 'As It Was', incorrect: ['Blinding Lights', 'Bad Habits', "Don't Start Now"], difficulty: 'easy', artist: 'Harry Styles', term: 'as it was harry styles' },
  { slug: 'bad-guy', prompt: NAME, correct: 'Bad Guy', incorrect: ['Blinding Lights', 'Dance Monkey', 'Bad Habits'], difficulty: 'easy', artist: 'Billie Eilish', term: 'bad guy billie eilish' },
  { slug: 'shake-it-off', prompt: NAME, correct: 'Shake It Off', incorrect: ["Can't Stop the Feeling!", 'Happy', 'Uptown Funk'], difficulty: 'easy', artist: 'Taylor Swift', term: 'shake it off taylor swift' },
  { slug: 'someone-you-loved', prompt: NAME, correct: 'Someone You Loved', incorrect: ['Say Something', 'Stay with Me', 'Photograph'], difficulty: 'easy', artist: 'Lewis Capaldi', term: 'someone you loved lewis capaldi' },
  { slug: 'dance-monkey', prompt: NAME, correct: 'Dance Monkey', incorrect: ['Bad Guy', 'Blinding Lights', 'Shotgun'], difficulty: 'easy', artist: 'Tones and I', term: 'dance monkey tones and i' },
  { slug: 'shotgun', prompt: NAME, correct: 'Shotgun', incorrect: ['Riptide', 'Ho Hey', 'Rather Be'], difficulty: 'hard', artist: 'George Ezra', term: 'shotgun george ezra' },
  { slug: 'thinking-out-loud', prompt: NAME, correct: 'Thinking Out Loud', incorrect: ['Someone You Loved', 'Say Something', 'All of Me'], difficulty: 'medium', artist: 'Ed Sheeran', term: 'thinking out loud ed sheeran' },
  { slug: 'rather-be', prompt: NAME, correct: 'Rather Be', incorrect: ['Get Lucky', 'Happy', 'Shotgun'], difficulty: 'hard', artist: 'Clean Bandit', term: 'rather be clean bandit' },
  { slug: 'hello-adele', prompt: NAME, correct: 'Hello', incorrect: ['Someone Like You', 'Set Fire to the Rain', 'Stay with Me'], difficulty: 'easy', artist: 'Adele', term: 'hello adele' },
  { slug: 'counting-stars', prompt: NAME, correct: 'Counting Stars', incorrect: ['Pompeii', 'Viva la Vida', 'Ho Hey'], difficulty: 'medium', artist: 'OneRepublic', term: 'counting stars onerepublic' },
  { slug: 'pompeii', prompt: NAME, correct: 'Pompeii', incorrect: ['Counting Stars', 'Viva la Vida', 'Riptide'], difficulty: 'medium', artist: 'Bastille', term: 'pompeii bastille' },
  { slug: 'riptide', prompt: NAME, correct: 'Riptide', incorrect: ['Ho Hey', 'Shotgun', 'Budapest'], difficulty: 'hard', artist: 'Vance Joy', term: 'riptide vance joy' },
  { slug: 'ho-hey', prompt: NAME, correct: 'Ho Hey', incorrect: ['Riptide', 'Shotgun', 'Little Talks'], difficulty: 'hard', artist: 'The Lumineers', term: 'ho hey the lumineers' },
  { slug: 'stay-with-me', prompt: NAME, correct: 'Stay with Me', incorrect: ['Someone You Loved', 'Say Something', 'Hello'], difficulty: 'hard', artist: 'Sam Smith', term: 'stay with me sam smith' },
  { slug: 'old-town-road', prompt: NAME, correct: 'Old Town Road', incorrect: ['Sunflower', 'One Dance', 'Bad Guy'], difficulty: 'easy', artist: 'Lil Nas X', term: 'old town road lil nas x' },
  { slug: 'sunflower', prompt: NAME, correct: 'Sunflower', incorrect: ['Old Town Road', 'One Dance', 'Blinding Lights'], difficulty: 'hard', artist: 'Post Malone', term: 'sunflower post malone' },
  { slug: 'wake-me-up', prompt: NAME, correct: 'Wake Me Up', incorrect: ['Titanium', 'Rather Be', 'Get Lucky'], difficulty: 'easy', artist: 'Avicii', term: 'wake me up avicii' },
  { slug: 'titanium', prompt: NAME, correct: 'Titanium', incorrect: ['Wake Me Up', 'We Found Love', 'Rather Be'], difficulty: 'hard', artist: 'David Guetta', term: 'titanium david guetta' },
];
