import type { Difficulty } from '../src/questions/types';

export interface ScreenSpec {
  slug: string;
  prompt: string;
  correct: string;
  incorrect: string[];
  difficulty: Difficulty;
  kind: 'movie' | 'tv';
  query: string;
  year: number;
  /** TMDB `origin_country`, when the title collides (The Office UK vs US). */
  originCountry?: string;
}

const FILM = 'Which film is this?';
const SHOW = 'Which TV show is this?';

/**
 * On the box. Mix of eras for a 2026 UK office — not a wall of 1960s–80s
 * “classics”. Fine Art already did that: PD-Art / Commons selected 15th–1930s
 * paintings because those stills were legal to hash, not because the room would
 * know them. Untitled TMDB backdrops (stills, then a cropped poster) must not
 * make the same call.
 */
export const SCREEN_SPECS: ScreenSpec[] = [
  // A few stills everyone has actually seen.
  { slug: 'jaws', prompt: FILM, correct: 'Jaws', incorrect: ['Jurassic Park', 'The Meg', 'Open Water'], difficulty: 'easy', kind: 'movie', query: 'Jaws', year: 1975 },
  { slug: 'star-wars', prompt: FILM, correct: 'Star Wars', incorrect: ['Star Trek', 'Dune', 'Guardians of the Galaxy'], difficulty: 'easy', kind: 'movie', query: 'Star Wars', year: 1977 },
  { slug: 'back-to-the-future', prompt: FILM, correct: 'Back to the Future', incorrect: ['Bill & Ted’s Excellent Adventure', 'Hot Tub Time Machine', 'Peggy Sue Got Married'], difficulty: 'easy', kind: 'movie', query: 'Back to the Future', year: 1985 },
  { slug: 'home-alone', prompt: FILM, correct: 'Home Alone', incorrect: ['Mrs. Doubtfire', 'Elf', 'The Santa Clause'], difficulty: 'easy', kind: 'movie', query: 'Home Alone', year: 1990 },
  { slug: 'jurassic-park', prompt: FILM, correct: 'Jurassic Park', incorrect: ['Jaws', 'King Kong', 'Godzilla'], difficulty: 'easy', kind: 'movie', query: 'Jurassic Park', year: 1993 },
  { slug: 'lion-king', prompt: FILM, correct: 'The Lion King', incorrect: ['The Jungle Book', 'Madagascar', 'Tarzan'], difficulty: 'easy', kind: 'movie', query: 'The Lion King', year: 1994 },
  { slug: 'toy-story', prompt: FILM, correct: 'Toy Story', incorrect: ['A Bug’s Life', 'Monsters, Inc.', 'Shrek'], difficulty: 'easy', kind: 'movie', query: 'Toy Story', year: 1995 },
  { slug: 'titanic', prompt: FILM, correct: 'Titanic', incorrect: ['The Notebook', 'Pearl Harbor', 'Atonement'], difficulty: 'easy', kind: 'movie', query: 'Titanic', year: 1997 },
  { slug: 'matrix', prompt: FILM, correct: 'The Matrix', incorrect: ['Inception', 'Blade Runner', 'Tron'], difficulty: 'easy', kind: 'movie', query: 'The Matrix', year: 1999 },
  { slug: 'harry-potter', prompt: FILM, correct: 'Harry Potter and the Philosopher’s Stone', incorrect: ['The Lord of the Rings: The Fellowship of the Ring', 'The Chronicles of Narnia', 'Percy Jackson & the Olympians'], difficulty: 'easy', kind: 'movie', query: 'Harry Potter and the Philosopher\'s Stone', year: 2001 },
  { slug: 'lotr', prompt: FILM, correct: 'The Lord of the Rings: The Fellowship of the Ring', incorrect: ['Harry Potter and the Philosopher’s Stone', 'The Hobbit: An Unexpected Journey', 'Willow'], difficulty: 'easy', kind: 'movie', query: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001 },
  { slug: 'shrek', prompt: FILM, correct: 'Shrek', incorrect: ['Shrek 2', 'Monsters, Inc.', 'Ice Age'], difficulty: 'easy', kind: 'movie', query: 'Shrek', year: 2001 },
  { slug: 'love-actually', prompt: FILM, correct: 'Love Actually', incorrect: ['Notting Hill', 'Bridget Jones’s Diary', 'Four Weddings and a Funeral'], difficulty: 'easy', kind: 'movie', query: 'Love Actually', year: 2003 },
  { slug: 'finding-nemo', prompt: FILM, correct: 'Finding Nemo', incorrect: ['Shark Tale', 'The Little Mermaid', 'Happy Feet'], difficulty: 'easy', kind: 'movie', query: 'Finding Nemo', year: 2003 },
  { slug: 'mean-girls', prompt: FILM, correct: 'Mean Girls', incorrect: ['Clueless', '10 Things I Hate About You', 'Legally Blonde'], difficulty: 'medium', kind: 'movie', query: 'Mean Girls', year: 2004 },
  { slug: 'casino-royale', prompt: FILM, correct: 'Casino Royale', incorrect: ['Skyfall', 'Quantum of Solace', 'Die Another Day'], difficulty: 'medium', kind: 'movie', query: 'Casino Royale', year: 2006 },
  { slug: 'mamma-mia', prompt: FILM, correct: 'Mamma Mia!', incorrect: ['Mamma Mia! Here We Go Again', 'Grease', 'The Greatest Showman'], difficulty: 'easy', kind: 'movie', query: 'Mamma Mia', year: 2008 },
  { slug: 'dark-knight', prompt: FILM, correct: 'The Dark Knight', incorrect: ['Batman Begins', 'Joker', 'The Batman'], difficulty: 'easy', kind: 'movie', query: 'The Dark Knight', year: 2008 },
  { slug: 'avatar', prompt: FILM, correct: 'Avatar', incorrect: ['Avatar: The Way of Water', 'Dune', 'Guardians of the Galaxy'], difficulty: 'easy', kind: 'movie', query: 'Avatar', year: 2009 },
  { slug: 'inception', prompt: FILM, correct: 'Inception', incorrect: ['The Matrix', 'Interstellar', 'Tenet'], difficulty: 'easy', kind: 'movie', query: 'Inception', year: 2010 },
  { slug: 'skyfall', prompt: FILM, correct: 'Skyfall', incorrect: ['Casino Royale', 'Spectre', 'No Time to Die'], difficulty: 'medium', kind: 'movie', query: 'Skyfall', year: 2012 },
  { slug: 'hunger-games', prompt: FILM, correct: 'The Hunger Games', incorrect: ['Divergent', 'The Maze Runner', 'Twilight'], difficulty: 'easy', kind: 'movie', query: 'The Hunger Games', year: 2012 },
  { slug: 'frozen', prompt: FILM, correct: 'Frozen', incorrect: ['Tangled', 'Brave', 'Moana'], difficulty: 'easy', kind: 'movie', query: 'Frozen', year: 2013 },
  { slug: 'guardians', prompt: FILM, correct: 'Guardians of the Galaxy', incorrect: ['Thor: Ragnarok', 'Ant-Man', 'The Avengers'], difficulty: 'easy', kind: 'movie', query: 'Guardians of the Galaxy', year: 2014 },
  { slug: 'deadpool', prompt: FILM, correct: 'Deadpool', incorrect: ['Deadpool 2', 'Logan', 'Venom'], difficulty: 'easy', kind: 'movie', query: 'Deadpool', year: 2016 },
  { slug: 'get-out', prompt: FILM, correct: 'Get Out', incorrect: ['Us', 'Nope', 'The Invisible Man'], difficulty: 'medium', kind: 'movie', query: 'Get Out', year: 2017 },
  { slug: 'paddington-2', prompt: FILM, correct: 'Paddington 2', incorrect: ['Paddington', 'Christopher Robin', 'Ted'], difficulty: 'easy', kind: 'movie', query: 'Paddington 2', year: 2017 },
  { slug: 'coco', prompt: FILM, correct: 'Coco', incorrect: ['Encanto', 'The Book of Life', 'Soul'], difficulty: 'easy', kind: 'movie', query: 'Coco', year: 2017 },
  { slug: 'black-panther', prompt: FILM, correct: 'Black Panther', incorrect: ['Black Panther: Wakanda Forever', 'Captain America: Civil War', 'Doctor Strange'], difficulty: 'easy', kind: 'movie', query: 'Black Panther', year: 2018 },
  { slug: 'joker', prompt: FILM, correct: 'Joker', incorrect: ['The Dark Knight', 'The Batman', 'Joker: Folie à Deux'], difficulty: 'medium', kind: 'movie', query: 'Joker', year: 2019 },
  { slug: 'endgame', prompt: FILM, correct: 'Avengers: Endgame', incorrect: ['Avengers: Infinity War', 'The Avengers', 'Spider-Man: No Way Home'], difficulty: 'easy', kind: 'movie', query: 'Avengers Endgame', year: 2019 },
  { slug: 'dune', prompt: FILM, correct: 'Dune', incorrect: ['Dune: Part Two', 'Star Wars', 'Avatar'], difficulty: 'medium', kind: 'movie', query: 'Dune', year: 2021 },
  { slug: 'no-way-home', prompt: FILM, correct: 'Spider-Man: No Way Home', incorrect: ['Spider-Man: Far From Home', 'Avengers: Endgame', 'The Amazing Spider-Man'], difficulty: 'easy', kind: 'movie', query: 'Spider-Man No Way Home', year: 2021 },
  { slug: 'top-gun-maverick', prompt: FILM, correct: 'Top Gun: Maverick', incorrect: ['Top Gun', 'Days of Thunder', 'Mission: Impossible – Fallout'], difficulty: 'easy', kind: 'movie', query: 'Top Gun Maverick', year: 2022 },
  { slug: 'barbie', prompt: FILM, correct: 'Barbie', incorrect: ['Barbie as The Princess and the Pauper', 'The Lego Movie', 'Wicked'], difficulty: 'easy', kind: 'movie', query: 'Barbie', year: 2023 },
  { slug: 'oppenheimer', prompt: FILM, correct: 'Oppenheimer', incorrect: ['The Imitation Game', 'Dunkirk', 'Napoleon'], difficulty: 'medium', kind: 'movie', query: 'Oppenheimer', year: 2023 },

  { slug: 'friends', prompt: SHOW, correct: 'Friends', incorrect: ['How I Met Your Mother', 'Seinfeld', 'The Big Bang Theory'], difficulty: 'easy', kind: 'tv', query: 'Friends', year: 1994 },
  { slug: 'the-office-uk', prompt: SHOW, correct: 'The Office', incorrect: ['Peep Show', 'The Inbetweeners', 'Parks and Recreation'], difficulty: 'medium', kind: 'tv', query: 'The Office', year: 2001, originCountry: 'GB' },
  { slug: 'doctor-who', prompt: SHOW, correct: 'Doctor Who', incorrect: ['Torchwood', 'Sherlock', 'Merlin'], difficulty: 'easy', kind: 'tv', query: 'Doctor Who', year: 2005 },
  { slug: 'gavin-and-stacey', prompt: SHOW, correct: 'Gavin & Stacey', incorrect: ['Gimme Gimme Gimme', 'This Country', 'The Inbetweeners'], difficulty: 'medium', kind: 'tv', query: 'Gavin & Stacey', year: 2007 },
  { slug: 'breaking-bad', prompt: SHOW, correct: 'Breaking Bad', incorrect: ['Better Call Saul', 'The Wire', 'Ozark'], difficulty: 'easy', kind: 'tv', query: 'Breaking Bad', year: 2008 },
  { slug: 'sherlock', prompt: SHOW, correct: 'Sherlock', incorrect: ['Elementary', 'Luther', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Sherlock', year: 2010 },
  { slug: 'downton', prompt: SHOW, correct: 'Downton Abbey', incorrect: ['The Crown', 'Bridgerton', 'Upstairs, Downstairs'], difficulty: 'medium', kind: 'tv', query: 'Downton Abbey', year: 2010 },
  { slug: 'game-of-thrones', prompt: SHOW, correct: 'Game of Thrones', incorrect: ['The Witcher', 'House of the Dragon', 'Vikings'], difficulty: 'easy', kind: 'tv', query: 'Game of Thrones', year: 2011 },
  { slug: 'line-of-duty', prompt: SHOW, correct: 'Line of Duty', incorrect: ['Bodyguard', 'Happy Valley', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Line of Duty', year: 2012 },
  { slug: 'peaky-blinders', prompt: SHOW, correct: 'Peaky Blinders', incorrect: ['Boardwalk Empire', 'Gangs of London', 'Taboo'], difficulty: 'medium', kind: 'tv', query: 'Peaky Blinders', year: 2013 },
  { slug: 'happy-valley', prompt: SHOW, correct: 'Happy Valley', incorrect: ['Line of Duty', 'Broadchurch', 'Scott & Bailey'], difficulty: 'hard', kind: 'tv', query: 'Happy Valley', year: 2014 },
  { slug: 'stranger-things', prompt: SHOW, correct: 'Stranger Things', incorrect: ['Dark', 'The OA', 'Wednesday'], difficulty: 'easy', kind: 'tv', query: 'Stranger Things', year: 2016 },
  { slug: 'fleabag', prompt: SHOW, correct: 'Fleabag', incorrect: ['Killing Eve', 'Catastrophe', 'I May Destroy You'], difficulty: 'medium', kind: 'tv', query: 'Fleabag', year: 2016 },
  { slug: 'the-crown', prompt: SHOW, correct: 'The Crown', incorrect: ['Downton Abbey', 'The Queen', 'Victoria'], difficulty: 'medium', kind: 'tv', query: 'The Crown', year: 2016 },
  { slug: 'succession', prompt: SHOW, correct: 'Succession', incorrect: ['Billions', 'Industry', 'The White Lotus'], difficulty: 'medium', kind: 'tv', query: 'Succession', year: 2018 },
  { slug: 'bridgerton', prompt: SHOW, correct: 'Bridgerton', incorrect: ['Downton Abbey', 'The Crown', 'Sanditon'], difficulty: 'easy', kind: 'tv', query: 'Bridgerton', year: 2020 },
  { slug: 'squid-game', prompt: SHOW, correct: 'Squid Game', incorrect: ['Alice in Borderland', 'The Traitors', 'Money Heist'], difficulty: 'easy', kind: 'tv', query: 'Squid Game', year: 2021 },
  { slug: 'wednesday', prompt: SHOW, correct: 'Wednesday', incorrect: ['Stranger Things', 'The Addams Family', 'Locke & Key'], difficulty: 'easy', kind: 'tv', query: 'Wednesday', year: 2022 },

  // Second harvest, 24 September 2026. The first 54 were played out in four
  // rounds and were 37 easy to 1 hard, so this half leans medium and hard, and
  // pairs each title with the films it is most easily mistaken for.
  { slug: 'gladiator', prompt: FILM, correct: 'Gladiator', incorrect: ['Troy', 'Kingdom of Heaven', 'Ben-Hur'], difficulty: 'medium', kind: 'movie', query: 'Gladiator', year: 2000 },
  { slug: 'notting-hill', prompt: FILM, correct: 'Notting Hill', incorrect: ['Four Weddings and a Funeral', 'Love Actually', 'About Time'], difficulty: 'medium', kind: 'movie', query: 'Notting Hill', year: 1999 },
  { slug: 'four-weddings', prompt: FILM, correct: 'Four Weddings and a Funeral', incorrect: ['Notting Hill', 'Bridget Jones’s Diary', 'About Time'], difficulty: 'hard', kind: 'movie', query: 'Four Weddings and a Funeral', year: 1994 },
  { slug: 'hot-fuzz', prompt: FILM, correct: 'Hot Fuzz', incorrect: ['Shaun of the Dead', 'The World’s End', 'Paul'], difficulty: 'medium', kind: 'movie', query: 'Hot Fuzz', year: 2007 },
  { slug: 'shaun-of-the-dead', prompt: FILM, correct: 'Shaun of the Dead', incorrect: ['Hot Fuzz', '28 Days Later', 'Zombieland'], difficulty: 'medium', kind: 'movie', query: 'Shaun of the Dead', year: 2004 },
  { slug: 'full-monty', prompt: FILM, correct: 'The Full Monty', incorrect: ['Brassed Off', 'Calendar Girls', 'Billy Elliot'], difficulty: 'hard', kind: 'movie', query: 'The Full Monty', year: 1997 },
  { slug: 'billy-elliot', prompt: FILM, correct: 'Billy Elliot', incorrect: ['Brassed Off', 'Pride', 'The Full Monty'], difficulty: 'hard', kind: 'movie', query: 'Billy Elliot', year: 2000 },
  { slug: 'trainspotting', prompt: FILM, correct: 'Trainspotting', incorrect: ['Human Traffic', 'Lock, Stock and Two Smoking Barrels', 'Shallow Grave'], difficulty: 'medium', kind: 'movie', query: 'Trainspotting', year: 1996 },
  { slug: 'lock-stock', prompt: FILM, correct: 'Lock, Stock and Two Smoking Barrels', incorrect: ['Snatch', 'Layer Cake', 'RocknRolla'], difficulty: 'hard', kind: 'movie', query: 'Lock, Stock and Two Smoking Barrels', year: 1998 },
  { slug: 'snatch', prompt: FILM, correct: 'Snatch', incorrect: ['Lock, Stock and Two Smoking Barrels', 'The Gentlemen', 'RocknRolla'], difficulty: 'medium', kind: 'movie', query: 'Snatch', year: 2000 },
  { slug: 'pulp-fiction', prompt: FILM, correct: 'Pulp Fiction', incorrect: ['Reservoir Dogs', 'Jackie Brown', 'True Romance'], difficulty: 'medium', kind: 'movie', query: 'Pulp Fiction', year: 1994 },
  { slug: 'forrest-gump', prompt: FILM, correct: 'Forrest Gump', incorrect: ['Big', 'Cast Away', 'The Green Mile'], difficulty: 'easy', kind: 'movie', query: 'Forrest Gump', year: 1994 },
  { slug: 'shawshank', prompt: FILM, correct: 'The Shawshank Redemption', incorrect: ['The Green Mile', 'Escape from Alcatraz', 'The Great Escape'], difficulty: 'medium', kind: 'movie', query: 'The Shawshank Redemption', year: 1994 },
  { slug: 'pretty-woman', prompt: FILM, correct: 'Pretty Woman', incorrect: ['Runaway Bride', 'Notting Hill', 'Maid in Manhattan'], difficulty: 'medium', kind: 'movie', query: 'Pretty Woman', year: 1990 },
  { slug: 'mrs-doubtfire', prompt: FILM, correct: 'Mrs. Doubtfire', incorrect: ['Tootsie', 'Hook', 'Jumanji'], difficulty: 'medium', kind: 'movie', query: 'Mrs. Doubtfire', year: 1993 },
  { slug: 'men-in-black', prompt: FILM, correct: 'Men in Black', incorrect: ['Independence Day', 'Galaxy Quest', 'Ghostbusters'], difficulty: 'medium', kind: 'movie', query: 'Men in Black', year: 1997 },
  { slug: 'independence-day', prompt: FILM, correct: 'Independence Day', incorrect: ['Armageddon', 'Men in Black', 'War of the Worlds'], difficulty: 'medium', kind: 'movie', query: 'Independence Day', year: 1996 },
  { slug: 'saving-private-ryan', prompt: FILM, correct: 'Saving Private Ryan', incorrect: ['Dunkirk', 'Fury', 'Black Hawk Down'], difficulty: 'medium', kind: 'movie', query: 'Saving Private Ryan', year: 1998 },
  { slug: 'film-1917', prompt: FILM, correct: '1917', incorrect: ['Dunkirk', 'Saving Private Ryan', 'All Quiet on the Western Front'], difficulty: 'hard', kind: 'movie', query: '1917', year: 2019 },
  { slug: 'dunkirk', prompt: FILM, correct: 'Dunkirk', incorrect: ['1917', 'Darkest Hour', 'Atonement'], difficulty: 'hard', kind: 'movie', query: 'Dunkirk', year: 2017 },
  { slug: 'devil-wears-prada', prompt: FILM, correct: 'The Devil Wears Prada', incorrect: ['The Intern', 'Legally Blonde', 'Confessions of a Shopaholic'], difficulty: 'medium', kind: 'movie', query: 'The Devil Wears Prada', year: 2006 },
  { slug: 'pirates-caribbean', prompt: FILM, correct: 'Pirates of the Caribbean: The Curse of the Black Pearl', incorrect: ['Hook', 'Master and Commander: The Far Side of the World', 'Treasure Planet'], difficulty: 'easy', kind: 'movie', query: 'Pirates of the Caribbean: The Curse of the Black Pearl', year: 2003 },
  { slug: 'gravity', prompt: FILM, correct: 'Gravity', incorrect: ['Interstellar', 'The Martian', 'Apollo 13'], difficulty: 'medium', kind: 'movie', query: 'Gravity', year: 2013 },
  { slug: 'interstellar', prompt: FILM, correct: 'Interstellar', incorrect: ['Gravity', 'The Martian', 'Arrival'], difficulty: 'medium', kind: 'movie', query: 'Interstellar', year: 2014 },
  { slug: 'the-martian', prompt: FILM, correct: 'The Martian', incorrect: ['Gravity', 'Interstellar', 'Moon'], difficulty: 'medium', kind: 'movie', query: 'The Martian', year: 2015 },
  { slug: 'la-la-land', prompt: FILM, correct: 'La La Land', incorrect: ['The Greatest Showman', 'Whiplash', 'A Star Is Born'], difficulty: 'medium', kind: 'movie', query: 'La La Land', year: 2016 },
  { slug: 'greatest-showman', prompt: FILM, correct: 'The Greatest Showman', incorrect: ['La La Land', 'Moulin Rouge!', 'Chicago'], difficulty: 'medium', kind: 'movie', query: 'The Greatest Showman', year: 2017 },
  { slug: 'bohemian-rhapsody-film', prompt: FILM, correct: 'Bohemian Rhapsody', incorrect: ['Rocketman', 'Elvis', 'Walk the Line'], difficulty: 'medium', kind: 'movie', query: 'Bohemian Rhapsody', year: 2018 },
  { slug: 'mad-max-fury-road', prompt: FILM, correct: 'Mad Max: Fury Road', incorrect: ['Waterworld', 'The Book of Eli', 'Dredd'], difficulty: 'medium', kind: 'movie', query: 'Mad Max: Fury Road', year: 2015 },
  { slug: 'parasite', prompt: FILM, correct: 'Parasite', incorrect: ['Oldboy', 'Shoplifters', 'Burning'], difficulty: 'hard', kind: 'movie', query: 'Parasite', year: 2019 },
  { slug: 'everything-everywhere', prompt: FILM, correct: 'Everything Everywhere All at Once', incorrect: ['Crouching Tiger, Hidden Dragon', 'Shang-Chi and the Legend of the Ten Rings', 'The Farewell'], difficulty: 'hard', kind: 'movie', query: 'Everything Everywhere All at Once', year: 2022 },
  { slug: 'knives-out', prompt: FILM, correct: 'Knives Out', incorrect: ['Glass Onion: A Knives Out Mystery', 'Murder on the Orient Express', 'Death on the Nile'], difficulty: 'medium', kind: 'movie', query: 'Knives Out', year: 2019 },
  { slug: 'wicked', prompt: FILM, correct: 'Wicked', incorrect: ['The Wizard of Oz', 'Into the Woods', 'Enchanted'], difficulty: 'medium', kind: 'movie', query: 'Wicked', year: 2024 },
  { slug: 'inside-out', prompt: FILM, correct: 'Inside Out', incorrect: ['Soul', 'Up', 'Elemental'], difficulty: 'medium', kind: 'movie', query: 'Inside Out', year: 2015 },
  { slug: 'up', prompt: FILM, correct: 'Up', incorrect: ['Ratatouille', 'WALL·E', 'Inside Out'], difficulty: 'easy', kind: 'movie', query: 'Up', year: 2009 },
  { slug: 'the-incredibles', prompt: FILM, correct: 'The Incredibles', incorrect: ['Megamind', 'Despicable Me', 'Big Hero 6'], difficulty: 'medium', kind: 'movie', query: 'The Incredibles', year: 2004 },
  { slug: 'despicable-me', prompt: FILM, correct: 'Despicable Me', incorrect: ['Megamind', 'The Incredibles', 'Madagascar'], difficulty: 'easy', kind: 'movie', query: 'Despicable Me', year: 2010 },
  { slug: 'were-rabbit', prompt: FILM, correct: 'Wallace & Gromit: The Curse of the Were-Rabbit', incorrect: ['Chicken Run', 'Flushed Away', 'Shaun the Sheep Movie'], difficulty: 'medium', kind: 'movie', query: 'Wallace & Gromit: The Curse of the Were-Rabbit', year: 2005 },
  { slug: 'chicken-run', prompt: FILM, correct: 'Chicken Run', incorrect: ['Wallace & Gromit: The Curse of the Were-Rabbit', 'Flushed Away', 'Shaun the Sheep Movie'], difficulty: 'medium', kind: 'movie', query: 'Chicken Run', year: 2000 },
  { slug: 'slumdog-millionaire', prompt: FILM, correct: 'Slumdog Millionaire', incorrect: ['Life of Pi', 'Lion', 'The Best Exotic Marigold Hotel'], difficulty: 'medium', kind: 'movie', query: 'Slumdog Millionaire', year: 2008 },
  { slug: 'kings-speech', prompt: FILM, correct: 'The King’s Speech', incorrect: ['Darkest Hour', 'The Queen', 'Mrs Brown'], difficulty: 'hard', kind: 'movie', query: 'The King\'s Speech', year: 2010 },
  { slug: 'darkest-hour', prompt: FILM, correct: 'Darkest Hour', incorrect: ['The King’s Speech', 'Dunkirk', 'The Imitation Game'], difficulty: 'hard', kind: 'movie', query: 'Darkest Hour', year: 2017 },
  { slug: 'imitation-game', prompt: FILM, correct: 'The Imitation Game', incorrect: ['The Theory of Everything', 'Enigma', 'A Beautiful Mind'], difficulty: 'hard', kind: 'movie', query: 'The Imitation Game', year: 2014 },
  { slug: 'theory-of-everything', prompt: FILM, correct: 'The Theory of Everything', incorrect: ['The Imitation Game', 'A Beautiful Mind', 'Good Will Hunting'], difficulty: 'hard', kind: 'movie', query: 'The Theory of Everything', year: 2014 },
  { slug: 'kingsman', prompt: FILM, correct: 'Kingsman: The Secret Service', incorrect: ['The Man from U.N.C.L.E.', 'Johnny English', 'Spectre'], difficulty: 'medium', kind: 'movie', query: 'Kingsman: The Secret Service', year: 2014 },
  { slug: 'johnny-english', prompt: FILM, correct: 'Johnny English', incorrect: ['Mr. Bean’s Holiday', 'Kingsman: The Secret Service', 'Austin Powers: International Man of Mystery'], difficulty: 'hard', kind: 'movie', query: 'Johnny English', year: 2003 },
  { slug: 'mr-beans-holiday', prompt: FILM, correct: 'Mr. Bean’s Holiday', incorrect: ['Johnny English', 'Bean', 'Hot Fuzz'], difficulty: 'medium', kind: 'movie', query: 'Mr. Bean\'s Holiday', year: 2007 },
  { slug: 'gone-girl', prompt: FILM, correct: 'Gone Girl', incorrect: ['The Girl on the Train', 'Prisoners', 'Zodiac'], difficulty: 'hard', kind: 'movie', query: 'Gone Girl', year: 2014 },
  { slug: 'social-network', prompt: FILM, correct: 'The Social Network', incorrect: ['The Big Short', 'Steve Jobs', 'Moneyball'], difficulty: 'hard', kind: 'movie', query: 'The Social Network', year: 2010 },
  { slug: 'wolf-of-wall-street', prompt: FILM, correct: 'The Wolf of Wall Street', incorrect: ['The Big Short', 'Wall Street', 'Catch Me If You Can'], difficulty: 'medium', kind: 'movie', query: 'The Wolf of Wall Street', year: 2013 },
  { slug: 'catch-me-if-you-can', prompt: FILM, correct: 'Catch Me If You Can', incorrect: ['The Wolf of Wall Street', 'The Talented Mr. Ripley', 'Ocean’s Eleven'], difficulty: 'hard', kind: 'movie', query: 'Catch Me If You Can', year: 2002 },
  { slug: 'oceans-eleven', prompt: FILM, correct: 'Ocean’s Eleven', incorrect: ['The Italian Job', 'Now You See Me', 'Ocean’s Twelve'], difficulty: 'medium', kind: 'movie', query: 'Ocean\'s Eleven', year: 2001 },
  { slug: 'elf', prompt: FILM, correct: 'Elf', incorrect: ['Home Alone', 'The Santa Clause', 'Jingle All the Way'], difficulty: 'easy', kind: 'movie', query: 'Elf', year: 2003 },
  { slug: 'the-holiday', prompt: FILM, correct: 'The Holiday', incorrect: ['Love Actually', 'The Family Stone', 'Last Christmas'], difficulty: 'hard', kind: 'movie', query: 'The Holiday', year: 2006 },
  { slug: 'about-time', prompt: FILM, correct: 'About Time', incorrect: ['Notting Hill', 'Love Actually', 'The Time Traveler’s Wife'], difficulty: 'hard', kind: 'movie', query: 'About Time', year: 2013 },
  { slug: 'legally-blonde', prompt: FILM, correct: 'Legally Blonde', incorrect: ['Clueless', 'Mean Girls', 'The Devil Wears Prada'], difficulty: 'medium', kind: 'movie', query: 'Legally Blonde', year: 2001 },
  { slug: 'clueless', prompt: FILM, correct: 'Clueless', incorrect: ['Mean Girls', 'Legally Blonde', '10 Things I Hate About You'], difficulty: 'medium', kind: 'movie', query: 'Clueless', year: 1995 },
  { slug: 'pitch-perfect', prompt: FILM, correct: 'Pitch Perfect', incorrect: ['Bring It On', 'Step Up', 'High School Musical'], difficulty: 'medium', kind: 'movie', query: 'Pitch Perfect', year: 2012 },
  { slug: 'fast-and-furious', prompt: FILM, correct: 'The Fast and the Furious', incorrect: ['Gone in 60 Seconds', 'Need for Speed', 'Drive'], difficulty: 'medium', kind: 'movie', query: 'The Fast and the Furious', year: 2001 },
  { slug: 'john-wick', prompt: FILM, correct: 'John Wick', incorrect: ['The Equalizer', 'Taken', 'Nobody'], difficulty: 'medium', kind: 'movie', query: 'John Wick', year: 2014 },
  { slug: 'braveheart', prompt: FILM, correct: 'Braveheart', incorrect: ['Rob Roy', 'Gladiator', 'Outlaw King'], difficulty: 'medium', kind: 'movie', query: 'Braveheart', year: 1995 },
  { slug: 'moana', prompt: FILM, correct: 'Moana', incorrect: ['Frozen', 'Tangled', 'Encanto'], difficulty: 'easy', kind: 'movie', query: 'Moana', year: 2016 },
  { slug: 'encanto', prompt: FILM, correct: 'Encanto', incorrect: ['Coco', 'Moana', 'Luca'], difficulty: 'medium', kind: 'movie', query: 'Encanto', year: 2021 },
  { slug: 'tangled', prompt: FILM, correct: 'Tangled', incorrect: ['Frozen', 'Brave', 'Enchanted'], difficulty: 'medium', kind: 'movie', query: 'Tangled', year: 2010 },
  { slug: 'aladdin', prompt: FILM, correct: 'Aladdin', incorrect: ['Hercules', 'The Jungle Book', 'Sinbad: Legend of the Seven Seas'], difficulty: 'easy', kind: 'movie', query: 'Aladdin', year: 1992 },
  { slug: 'beauty-and-the-beast', prompt: FILM, correct: 'Beauty and the Beast', incorrect: ['The Little Mermaid', 'Cinderella', 'Aladdin'], difficulty: 'medium', kind: 'movie', query: 'Beauty and the Beast', year: 1991 },
  { slug: 'poor-things', prompt: FILM, correct: 'Poor Things', incorrect: ['The Favourite', 'The Shape of Water', 'Edward Scissorhands'], difficulty: 'hard', kind: 'movie', query: 'Poor Things', year: 2023 },
  { slug: 'saltburn', prompt: FILM, correct: 'Saltburn', incorrect: ['The Talented Mr. Ripley', 'Brideshead Revisited', 'Promising Young Woman'], difficulty: 'hard', kind: 'movie', query: 'Saltburn', year: 2023 },
  { slug: 'bend-it-like-beckham', prompt: FILM, correct: 'Bend It Like Beckham', incorrect: ['Goal!', 'Fever Pitch', 'Bhaji on the Beach'], difficulty: 'medium', kind: 'movie', query: 'Bend It Like Beckham', year: 2002 },
  { slug: 'inbetweeners-movie', prompt: FILM, correct: 'The Inbetweeners Movie', incorrect: ['Kevin & Perry Go Large', 'Superbad', 'Project X'], difficulty: 'medium', kind: 'movie', query: 'The Inbetweeners Movie', year: 2011 },
  { slug: 'die-hard', prompt: FILM, correct: 'Die Hard', incorrect: ['Lethal Weapon', 'Speed', 'Under Siege'], difficulty: 'medium', kind: 'movie', query: 'Die Hard', year: 1988 },
  { slug: 'only-fools', prompt: SHOW, correct: 'Only Fools and Horses', incorrect: ['Open All Hours', 'Minder', 'Still Game'], difficulty: 'easy', kind: 'tv', query: 'Only Fools and Horses', year: 1981, originCountry: 'GB' },
  { slug: 'fawlty-towers', prompt: SHOW, correct: 'Fawlty Towers', incorrect: ['Hi-de-Hi!', 'Are You Being Served?', 'The Good Life'], difficulty: 'medium', kind: 'tv', query: 'Fawlty Towers', year: 1975, originCountry: 'GB' },
  { slug: 'mr-bean', prompt: SHOW, correct: 'Mr. Bean', incorrect: ['The Thin Blue Line', 'Only Fools and Horses', 'Blackadder'], difficulty: 'easy', kind: 'tv', query: 'Mr. Bean', year: 1990 },
  { slug: 'fresh-prince', prompt: SHOW, correct: 'The Fresh Prince of Bel-Air', incorrect: ['Family Matters', 'Everybody Hates Chris', 'Saved by the Bell'], difficulty: 'easy', kind: 'tv', query: 'The Fresh Prince of Bel-Air', year: 1990 },
  { slug: 'inbetweeners', prompt: SHOW, correct: 'The Inbetweeners', incorrect: ['Skins', 'Friday Night Dinner', 'Bad Education'], difficulty: 'medium', kind: 'tv', query: 'The Inbetweeners', year: 2008, originCountry: 'GB' },
  { slug: 'peep-show', prompt: SHOW, correct: 'Peep Show', incorrect: ['The IT Crowd', 'Green Wing', 'Spaced'], difficulty: 'medium', kind: 'tv', query: 'Peep Show', year: 2003, originCountry: 'GB' },
  { slug: 'it-crowd', prompt: SHOW, correct: 'The IT Crowd', incorrect: ['Black Books', 'Peep Show', 'Silicon Valley'], difficulty: 'medium', kind: 'tv', query: 'The IT Crowd', year: 2006, originCountry: 'GB' },
  { slug: 'strictly', prompt: SHOW, correct: 'Strictly Come Dancing', incorrect: ['Dancing on Ice', 'The X Factor', 'Britain’s Got Talent'], difficulty: 'easy', kind: 'tv', query: 'Strictly Come Dancing', year: 2004 },
  { slug: 'bake-off', prompt: SHOW, correct: 'The Great British Bake Off', incorrect: ['MasterChef', 'The Great Pottery Throw Down', 'Kitchen Nightmares'], difficulty: 'easy', kind: 'tv', query: 'The Great British Bake Off', year: 2010 },
  { slug: 'top-gear', prompt: SHOW, correct: 'Top Gear', incorrect: ['The Grand Tour', 'Fifth Gear', 'Wheeler Dealers'], difficulty: 'easy', kind: 'tv', query: 'Top Gear', year: 2002, originCountry: 'GB' },
  { slug: 'the-traitors', prompt: SHOW, correct: 'The Traitors', incorrect: ['The Mole', 'Survivor', 'Race Across the World'], difficulty: 'medium', kind: 'tv', query: 'The Traitors', year: 2022, originCountry: 'GB' },
  { slug: 'love-island', prompt: SHOW, correct: 'Love Island', incorrect: ['Big Brother', 'The Only Way Is Essex', 'Too Hot to Handle'], difficulty: 'easy', kind: 'tv', query: 'Love Island', year: 2015, originCountry: 'GB' },
  { slug: 'gogglebox', prompt: SHOW, correct: 'Gogglebox', incorrect: ['The Royle Family', 'Married at First Sight', 'Big Brother'], difficulty: 'medium', kind: 'tv', query: 'Gogglebox', year: 2013, originCountry: 'GB' },
  { slug: 'royle-family', prompt: SHOW, correct: 'The Royle Family', incorrect: ['Gogglebox', 'Early Doors', 'Mrs Brown’s Boys'], difficulty: 'hard', kind: 'tv', query: 'The Royle Family', year: 1998 },
  { slug: 'father-ted', prompt: SHOW, correct: 'Father Ted', incorrect: ['Derry Girls', 'The Vicar of Dibley', 'Black Books'], difficulty: 'medium', kind: 'tv', query: 'Father Ted', year: 1995 },
  { slug: 'derry-girls', prompt: SHOW, correct: 'Derry Girls', incorrect: ['Father Ted', 'The Young Offenders', 'Sex Education'], difficulty: 'medium', kind: 'tv', query: 'Derry Girls', year: 2018 },
  { slug: 'vicar-of-dibley', prompt: SHOW, correct: 'The Vicar of Dibley', incorrect: ['Father Ted', 'Rev.', 'Keeping Up Appearances'], difficulty: 'medium', kind: 'tv', query: 'The Vicar of Dibley', year: 1994 },
  { slug: 'sex-education', prompt: SHOW, correct: 'Sex Education', incorrect: ['Heartstopper', 'Skins', 'The Inbetweeners'], difficulty: 'medium', kind: 'tv', query: 'Sex Education', year: 2019 },
  { slug: 'normal-people', prompt: SHOW, correct: 'Normal People', incorrect: ['Conversations with Friends', 'Heartstopper', 'One Day'], difficulty: 'hard', kind: 'tv', query: 'Normal People', year: 2020 },
  { slug: 'bodyguard', prompt: SHOW, correct: 'Bodyguard', incorrect: ['Line of Duty', 'The Night Manager', 'Vigil'], difficulty: 'medium', kind: 'tv', query: 'Bodyguard', year: 2018, originCountry: 'GB' },
  { slug: 'night-manager', prompt: SHOW, correct: 'The Night Manager', incorrect: ['Bodyguard', 'The Little Drummer Girl', 'Killing Eve'], difficulty: 'hard', kind: 'tv', query: 'The Night Manager', year: 2016 },
  { slug: 'killing-eve', prompt: SHOW, correct: 'Killing Eve', incorrect: ['The Night Manager', 'Luther', 'Slow Horses'], difficulty: 'medium', kind: 'tv', query: 'Killing Eve', year: 2018 },
  { slug: 'luther', prompt: SHOW, correct: 'Luther', incorrect: ['Line of Duty', 'Bodyguard', 'Top Boy'], difficulty: 'medium', kind: 'tv', query: 'Luther', year: 2010 },
  { slug: 'slow-horses', prompt: SHOW, correct: 'Slow Horses', incorrect: ['The Night Manager', 'Spooks', 'Killing Eve'], difficulty: 'hard', kind: 'tv', query: 'Slow Horses', year: 2022 },
  { slug: 'broadchurch', prompt: SHOW, correct: 'Broadchurch', incorrect: ['Happy Valley', 'Line of Duty', 'Shetland'], difficulty: 'medium', kind: 'tv', query: 'Broadchurch', year: 2013 },
  { slug: 'call-the-midwife', prompt: SHOW, correct: 'Call the Midwife', incorrect: ['Downton Abbey', 'All Creatures Great and Small', 'Heartbeat'], difficulty: 'medium', kind: 'tv', query: 'Call the Midwife', year: 2012 },
  { slug: 'death-in-paradise', prompt: SHOW, correct: 'Death in Paradise', incorrect: ['Midsomer Murders', 'Doc Martin', 'Bergerac'], difficulty: 'medium', kind: 'tv', query: 'Death in Paradise', year: 2011 },
  { slug: 'midsomer', prompt: SHOW, correct: 'Midsomer Murders', incorrect: ['Death in Paradise', 'Inspector Morse', 'Vera'], difficulty: 'hard', kind: 'tv', query: 'Midsomer Murders', year: 1997 },
  { slug: 'vera', prompt: SHOW, correct: 'Vera', incorrect: ['Shetland', 'Midsomer Murders', 'Scott & Bailey'], difficulty: 'hard', kind: 'tv', query: 'Vera', year: 2011, originCountry: 'GB' },
  { slug: 'walking-dead', prompt: SHOW, correct: 'The Walking Dead', incorrect: ['The Last of Us', 'Z Nation', 'Fear the Walking Dead'], difficulty: 'easy', kind: 'tv', query: 'The Walking Dead', year: 2010 },
  { slug: 'last-of-us', prompt: SHOW, correct: 'The Last of Us', incorrect: ['The Walking Dead', 'Station Eleven', 'The Rain'], difficulty: 'medium', kind: 'tv', query: 'The Last of Us', year: 2023 },
  { slug: 'mandalorian', prompt: SHOW, correct: 'The Mandalorian', incorrect: ['Andor', 'The Book of Boba Fett', 'Obi-Wan Kenobi'], difficulty: 'medium', kind: 'tv', query: 'The Mandalorian', year: 2019 },
  { slug: 'the-boys', prompt: SHOW, correct: 'The Boys', incorrect: ['Invincible', 'Gen V', 'Watchmen'], difficulty: 'medium', kind: 'tv', query: 'The Boys', year: 2019 },
  { slug: 'family-guy', prompt: SHOW, correct: 'Family Guy', incorrect: ['American Dad!', 'The Simpsons', 'Bob’s Burgers'], difficulty: 'easy', kind: 'tv', query: 'Family Guy', year: 1999 },
  { slug: 'big-bang-theory', prompt: SHOW, correct: 'The Big Bang Theory', incorrect: ['Young Sheldon', 'How I Met Your Mother', 'The IT Crowd'], difficulty: 'easy', kind: 'tv', query: 'The Big Bang Theory', year: 2007 },
  { slug: 'himym', prompt: SHOW, correct: 'How I Met Your Mother', incorrect: ['Friends', 'The Big Bang Theory', 'New Girl'], difficulty: 'medium', kind: 'tv', query: 'How I Met Your Mother', year: 2005 },
  { slug: 'modern-family', prompt: SHOW, correct: 'Modern Family', incorrect: ['Arrested Development', 'The Middle', 'Parenthood'], difficulty: 'medium', kind: 'tv', query: 'Modern Family', year: 2009 },
  { slug: 'brooklyn-99', prompt: SHOW, correct: 'Brooklyn Nine-Nine', incorrect: ['Parks and Recreation', 'Superstore', 'Reno 911!'], difficulty: 'medium', kind: 'tv', query: 'Brooklyn Nine-Nine', year: 2013 },
  { slug: 'ted-lasso', prompt: SHOW, correct: 'Ted Lasso', incorrect: ['Mike Bassett: England Manager', 'Sunderland ’Til I Die', 'Welcome to Wrexham'], difficulty: 'medium', kind: 'tv', query: 'Ted Lasso', year: 2020 },
  { slug: 'white-lotus', prompt: SHOW, correct: 'The White Lotus', incorrect: ['Nine Perfect Strangers', 'Big Little Lies', 'Industry'], difficulty: 'medium', kind: 'tv', query: 'The White Lotus', year: 2021 },
  { slug: 'sopranos', prompt: SHOW, correct: 'The Sopranos', incorrect: ['Boardwalk Empire', 'The Wire', 'Gomorrah'], difficulty: 'medium', kind: 'tv', query: 'The Sopranos', year: 1999 },
  { slug: 'the-wire', prompt: SHOW, correct: 'The Wire', incorrect: ['The Sopranos', 'Oz', 'Top Boy'], difficulty: 'hard', kind: 'tv', query: 'The Wire', year: 2002 },
  { slug: 'mad-men', prompt: SHOW, correct: 'Mad Men', incorrect: ['Boardwalk Empire', 'Suits', 'Masters of Sex'], difficulty: 'hard', kind: 'tv', query: 'Mad Men', year: 2007 },
  { slug: 'suits', prompt: SHOW, correct: 'Suits', incorrect: ['The Good Wife', 'Billions', 'Silk'], difficulty: 'medium', kind: 'tv', query: 'Suits', year: 2011 },
  { slug: 'greys-anatomy', prompt: SHOW, correct: 'Grey’s Anatomy', incorrect: ['ER', 'Chicago Med', 'Scrubs'], difficulty: 'medium', kind: 'tv', query: 'Grey\'s Anatomy', year: 2005 },
  { slug: 'ghosts-bbc', prompt: SHOW, correct: 'Ghosts', incorrect: ['Being Human', 'The League of Gentlemen', 'Inside No. 9'], difficulty: 'medium', kind: 'tv', query: 'Ghosts', year: 2019, originCountry: 'GB' },
  { slug: 'inside-no-9', prompt: SHOW, correct: 'Inside No. 9', incorrect: ['The League of Gentlemen', 'Black Mirror', 'Psychoville'], difficulty: 'hard', kind: 'tv', query: 'Inside No. 9', year: 2014 },
  { slug: 'black-mirror', prompt: SHOW, correct: 'Black Mirror', incorrect: ['Inside No. 9', 'The Twilight Zone', 'Years and Years'], difficulty: 'medium', kind: 'tv', query: 'Black Mirror', year: 2011 },
  { slug: 'taskmaster', prompt: SHOW, correct: 'Taskmaster', incorrect: ['Would I Lie to You?', '8 Out of 10 Cats Does Countdown', 'QI'], difficulty: 'medium', kind: 'tv', query: 'Taskmaster', year: 2015, originCountry: 'GB' },
  { slug: 'apprentice-uk', prompt: SHOW, correct: 'The Apprentice', incorrect: ['Dragons’ Den', 'Undercover Boss', 'Secret Millionaire'], difficulty: 'medium', kind: 'tv', query: 'The Apprentice', year: 2005, originCountry: 'GB' },
  { slug: 'dragons-den', prompt: SHOW, correct: 'Dragons’ Den', incorrect: ['The Apprentice', 'Shark Tank', 'Undercover Boss'], difficulty: 'hard', kind: 'tv', query: 'Dragons\' Den', year: 2005, originCountry: 'GB' },
  { slug: 'shameless-uk', prompt: SHOW, correct: 'Shameless', incorrect: ['Benidorm', 'The Royle Family', 'This Is England ’86'], difficulty: 'medium', kind: 'tv', query: 'Shameless', year: 2004, originCountry: 'GB' },
  { slug: 'friday-night-dinner', prompt: SHOW, correct: 'Friday Night Dinner', incorrect: ['Outnumbered', 'The Inbetweeners', 'Not Going Out'], difficulty: 'medium', kind: 'tv', query: 'Friday Night Dinner', year: 2011 },
  { slug: 'outnumbered', prompt: SHOW, correct: 'Outnumbered', incorrect: ['Motherland', 'My Family', 'Not Going Out'], difficulty: 'hard', kind: 'tv', query: 'Outnumbered', year: 2007, originCountry: 'GB' },
  { slug: 'baby-reindeer', prompt: SHOW, correct: 'Baby Reindeer', incorrect: ['I May Destroy You', 'Adolescence', 'Eric'], difficulty: 'hard', kind: 'tv', query: 'Baby Reindeer', year: 2024 },
  { slug: 'adolescence', prompt: SHOW, correct: 'Adolescence', incorrect: ['Baby Reindeer', 'Mr Bates vs The Post Office', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Adolescence', year: 2025 },
  { slug: 'severance', prompt: SHOW, correct: 'Severance', incorrect: ['Black Mirror', 'Silo', 'Mr. Robot'], difficulty: 'medium', kind: 'tv', query: 'Severance', year: 2022 },
  { slug: 'the-bear', prompt: SHOW, correct: 'The Bear', incorrect: ['Boiling Point', 'Hell’s Kitchen', 'Kitchen Confidential'], difficulty: 'medium', kind: 'tv', query: 'The Bear', year: 2022 },
  { slug: 'house-of-the-dragon', prompt: SHOW, correct: 'House of the Dragon', incorrect: ['Game of Thrones', 'The Witcher', 'Vikings'], difficulty: 'medium', kind: 'tv', query: 'House of the Dragon', year: 2022 },
  { slug: 'the-witcher', prompt: SHOW, correct: 'The Witcher', incorrect: ['House of the Dragon', 'Game of Thrones', 'Shadow and Bone'], difficulty: 'medium', kind: 'tv', query: 'The Witcher', year: 2019 },
  { slug: 'band-of-brothers', prompt: SHOW, correct: 'Band of Brothers', incorrect: ['The Pacific', 'Masters of the Air', 'Generation Kill'], difficulty: 'hard', kind: 'tv', query: 'Band of Brothers', year: 2001 },
  { slug: 'chernobyl', prompt: SHOW, correct: 'Chernobyl', incorrect: ['The Salisbury Poisonings', 'Years and Years', 'The Terror'], difficulty: 'hard', kind: 'tv', query: 'Chernobyl', year: 2019 },
  // Third harvest, 26 September 2026. The fresh easy bucket was down to 9, so this leans easy,
  // and still keeps to the eight-title cap on anything first shown before 1990:
  // stills most of a UK office would place, then a medium and hard tail for the ladder.
  { slug: 'terminator-2', prompt: FILM, correct: 'Terminator 2: Judgment Day', incorrect: ['RoboCop', 'Total Recall', 'Predator'], difficulty: 'easy', kind: 'movie', query: 'Terminator 2 Judgment Day', year: 1991 },
  { slug: 'monsters-inc', prompt: FILM, correct: 'Monsters, Inc.', incorrect: ['Toy Story', 'A Bug’s Life', 'Hotel Transylvania'], difficulty: 'easy', kind: 'movie', query: 'Monsters, Inc.', year: 2001 },
  { slug: 'cars-pixar', prompt: FILM, correct: 'Cars', incorrect: ['Planes', 'Turbo', 'Toy Story 2'], difficulty: 'easy', kind: 'movie', query: 'Cars', year: 2006 },
  { slug: 'ratatouille', prompt: FILM, correct: 'Ratatouille', incorrect: ['Flushed Away', 'Chef', 'The Rescuers'], difficulty: 'easy', kind: 'movie', query: 'Ratatouille', year: 2007 },
  { slug: 'kung-fu-panda', prompt: FILM, correct: 'Kung Fu Panda', incorrect: ['Mulan', 'Madagascar', 'The Karate Kid'], difficulty: 'easy', kind: 'movie', query: 'Kung Fu Panda', year: 2008 },
  { slug: 'ice-age', prompt: FILM, correct: 'Ice Age', incorrect: ['The Land Before Time', 'Madagascar', 'Dinosaur'], difficulty: 'easy', kind: 'movie', query: 'Ice Age', year: 2002 },
  { slug: 'madagascar', prompt: FILM, correct: 'Madagascar', incorrect: ['The Wild', 'Ice Age', 'Zootropolis'], difficulty: 'easy', kind: 'movie', query: 'Madagascar', year: 2005 },
  { slug: 'zootropolis', prompt: FILM, correct: 'Zootropolis', incorrect: ['Robin Hood', 'Sing', 'The Secret Life of Pets'], difficulty: 'easy', kind: 'movie', query: 'Zootopia', year: 2016 },
  { slug: 'twilight', prompt: FILM, correct: 'Twilight', incorrect: ['Warm Bodies', 'Beautiful Creatures', 'Vampire Academy'], difficulty: 'easy', kind: 'movie', query: 'Twilight', year: 2008 },
  { slug: 'avengers', prompt: FILM, correct: 'The Avengers', incorrect: ['Justice League', 'X-Men', 'Fantastic Four'], difficulty: 'easy', kind: 'movie', query: 'The Avengers', year: 2012 },
  { slug: 'iron-man', prompt: FILM, correct: 'Iron Man', incorrect: ['Captain America: The First Avenger', 'RoboCop', 'Ant-Man'], difficulty: 'easy', kind: 'movie', query: 'Iron Man', year: 2008 },
  { slug: 'wonka', prompt: FILM, correct: 'Wonka', incorrect: ['Charlie and the Chocolate Factory', 'Matilda the Musical', 'The Greatest Showman'], difficulty: 'easy', kind: 'movie', query: 'Wonka', year: 2023 },
  { slug: 'matilda', prompt: FILM, correct: 'Matilda', incorrect: ['Mrs. Doubtfire', 'Harriet the Spy', 'The Witches'], difficulty: 'easy', kind: 'movie', query: 'Matilda', year: 1996 },
  { slug: 'night-at-the-museum', prompt: FILM, correct: 'Night at the Museum', incorrect: ['Jumanji', 'Paul Blart: Mall Cop', 'Zathura'], difficulty: 'easy', kind: 'movie', query: 'Night at the Museum', year: 2006 },
  { slug: 'lego-movie', prompt: FILM, correct: 'The Lego Movie', incorrect: ['Toy Story 3', 'Wreck-It Ralph', 'The Emoji Movie'], difficulty: 'easy', kind: 'movie', query: 'The Lego Movie', year: 2014 },
  { slug: 'wonder-woman', prompt: FILM, correct: 'Wonder Woman', incorrect: ['Captain Marvel', 'Black Widow', 'Thor'], difficulty: 'easy', kind: 'movie', query: 'Wonder Woman', year: 2017 },
  { slug: 'how-to-train-your-dragon', prompt: FILM, correct: 'How to Train Your Dragon', incorrect: ['Brave', 'Shrek', 'Kung Fu Panda'], difficulty: 'easy', kind: 'movie', query: 'How to Train Your Dragon', year: 2010 },
  { slug: 'transformers', prompt: FILM, correct: 'Transformers', incorrect: ['Pacific Rim', 'Real Steel', 'Battleship'], difficulty: 'easy', kind: 'movie', query: 'Transformers', year: 2007 },
  { slug: 'mulan', prompt: FILM, correct: 'Mulan', incorrect: ['Pocahontas', 'Kung Fu Panda', 'Hercules'], difficulty: 'easy', kind: 'movie', query: 'Mulan', year: 1998 },
  { slug: 'lilo-and-stitch', prompt: FILM, correct: 'Lilo & Stitch', incorrect: ['Moana', 'Brother Bear', 'Chicken Little'], difficulty: 'easy', kind: 'movie', query: 'Lilo & Stitch', year: 2002 },
  { slug: 'sonic', prompt: FILM, correct: 'Sonic the Hedgehog', incorrect: ['Pokémon Detective Pikachu', 'Hop', 'Peter Rabbit'], difficulty: 'easy', kind: 'movie', query: 'Sonic the Hedgehog', year: 2020 },
  { slug: 'super-mario', prompt: FILM, correct: 'The Super Mario Bros. Movie', incorrect: ['Wreck-It Ralph', 'Sonic the Hedgehog', 'The Angry Birds Movie'], difficulty: 'easy', kind: 'movie', query: 'The Super Mario Bros. Movie', year: 2023 },
  { slug: 'minecraft', prompt: FILM, correct: 'A Minecraft Movie', incorrect: ['The Lego Movie', 'Jumanji: Welcome to the Jungle', 'Free Guy'], difficulty: 'easy', kind: 'movie', query: 'A Minecraft Movie', year: 2025 },
  { slug: 'grinch', prompt: FILM, correct: 'How the Grinch Stole Christmas', incorrect: ['Elf', 'The Santa Clause', 'Jingle All the Way'], difficulty: 'easy', kind: 'movie', query: 'How the Grinch Stole Christmas', year: 2000 },
  { slug: 'the-mask', prompt: FILM, correct: 'The Mask', incorrect: ['Ace Ventura: Pet Detective', 'Liar Liar', 'Dumb and Dumber'], difficulty: 'easy', kind: 'movie', query: 'The Mask', year: 1994 },
  { slug: 'space-jam', prompt: FILM, correct: 'Space Jam', incorrect: ['Who Framed Roger Rabbit', 'Looney Tunes: Back in Action', 'Cool World'], difficulty: 'easy', kind: 'movie', query: 'Space Jam', year: 1996 },
  { slug: 'simpsons', prompt: SHOW, correct: 'The Simpsons', incorrect: ['Family Guy', 'Futurama', 'King of the Hill'], difficulty: 'easy', kind: 'tv', query: 'The Simpsons', year: 1989 },
  { slug: 'bluey', prompt: SHOW, correct: 'Bluey', incorrect: ['Peppa Pig', 'Hey Duggee', 'PAW Patrol'], difficulty: 'easy', kind: 'tv', query: 'Bluey', year: 2018 },
  { slug: 'peppa-pig', prompt: SHOW, correct: 'Peppa Pig', incorrect: ['Ben & Holly’s Little Kingdom', 'Bluey', 'Hey Duggee'], difficulty: 'easy', kind: 'tv', query: 'Peppa Pig', year: 2004 },
  { slug: 'spongebob', prompt: SHOW, correct: 'SpongeBob SquarePants', incorrect: ['The Fairly OddParents', 'Rugrats', 'Adventure Time'], difficulty: 'easy', kind: 'tv', query: 'SpongeBob SquarePants', year: 1999 },
  { slug: 'south-park', prompt: SHOW, correct: 'South Park', incorrect: ['Family Guy', 'The Simpsons', 'Beavis and Butt-Head'], difficulty: 'easy', kind: 'tv', query: 'South Park', year: 1997 },
  { slug: 'teletubbies', prompt: SHOW, correct: 'Teletubbies', incorrect: ['In the Night Garden', 'Tweenies', 'The Fimbles'], difficulty: 'easy', kind: 'tv', query: 'Teletubbies', year: 1997 },
  { slug: 'the-notebook', prompt: FILM, correct: 'The Notebook', incorrect: ['A Walk to Remember', 'Dear John', 'The Lucky One'], difficulty: 'medium', kind: 'movie', query: 'The Notebook', year: 2004 },
  { slug: 'bridesmaids', prompt: FILM, correct: 'Bridesmaids', incorrect: ['The Hangover', 'Bad Moms', 'Pitch Perfect'], difficulty: 'medium', kind: 'movie', query: 'Bridesmaids', year: 2011 },
  { slug: 'sister-act', prompt: FILM, correct: 'Sister Act', incorrect: ['The Bodyguard', 'Ghost', 'Mrs. Doubtfire'], difficulty: 'medium', kind: 'movie', query: 'Sister Act', year: 1992 },
  { slug: 'edward-scissorhands', prompt: FILM, correct: 'Edward Scissorhands', incorrect: ['Beetlejuice', 'Sleepy Hollow', 'Corpse Bride'], difficulty: 'medium', kind: 'movie', query: 'Edward Scissorhands', year: 1990 },
  { slug: 'nightmare-before-christmas', prompt: FILM, correct: 'The Nightmare Before Christmas', incorrect: ['Corpse Bride', 'Coraline', 'Frankenweenie'], difficulty: 'medium', kind: 'movie', query: 'The Nightmare Before Christmas', year: 1993 },
  { slug: 'muppet-christmas-carol', prompt: FILM, correct: 'The Muppet Christmas Carol', incorrect: ['Muppet Treasure Island', 'The Muppets', 'Scrooged'], difficulty: 'medium', kind: 'movie', query: 'The Muppet Christmas Carol', year: 1992 },
  { slug: 'pride-and-prejudice', prompt: FILM, correct: 'Pride & Prejudice', incorrect: ['Sense and Sensibility', 'Emma.', 'Atonement'], difficulty: 'medium', kind: 'movie', query: 'Pride & Prejudice', year: 2005 },
  { slug: 'les-miserables', prompt: FILM, correct: 'Les Misérables', incorrect: ['The Phantom of the Opera', 'Sweeney Todd: The Demon Barber of Fleet Street', 'Oliver!'], difficulty: 'medium', kind: 'movie', query: 'Les Misérables', year: 2012 },
  { slug: 'truman-show', prompt: FILM, correct: 'The Truman Show', incorrect: ['Pleasantville', 'Edtv', 'The Majestic'], difficulty: 'medium', kind: 'movie', query: 'The Truman Show', year: 1998 },
  { slug: 'cast-away', prompt: FILM, correct: 'Cast Away', incorrect: ['The Beach', 'Life of Pi', 'All Is Lost'], difficulty: 'medium', kind: 'movie', query: 'Cast Away', year: 2000 },
  { slug: 'fight-club', prompt: FILM, correct: 'Fight Club', incorrect: ['Se7en', 'American Psycho', 'Memento'], difficulty: 'medium', kind: 'movie', query: 'Fight Club', year: 1999 },
  { slug: 'kill-bill', prompt: FILM, correct: 'Kill Bill: Vol. 1', incorrect: ['Lady Snowblood', 'Django Unchained', 'Sin City'], difficulty: 'medium', kind: 'movie', query: 'Kill Bill Vol. 1', year: 2003 },
  { slug: 'rocketman', prompt: FILM, correct: 'Rocketman', incorrect: ['Bohemian Rhapsody', 'Elvis', 'A Complete Unknown'], difficulty: 'medium', kind: 'movie', query: 'Rocketman', year: 2019 },
  { slug: 'spider-verse', prompt: FILM, correct: 'Spider-Man: Into the Spider-Verse', incorrect: ['Spider-Man: No Way Home', 'The Mitchells vs. the Machines', 'Teenage Mutant Ninja Turtles: Mutant Mayhem'], difficulty: 'medium', kind: 'movie', query: 'Spider-Man: Into the Spider-Verse', year: 2018 },
  { slug: 'spirited-away', prompt: FILM, correct: 'Spirited Away', incorrect: ['My Neighbour Totoro', 'Howl’s Moving Castle', 'Ponyo'], difficulty: 'medium', kind: 'movie', query: 'Spirited Away', year: 2001 },
  { slug: 'big-hero-6', prompt: FILM, correct: 'Big Hero 6', incorrect: ['The Incredibles', 'Megamind', 'Bolt'], difficulty: 'medium', kind: 'movie', query: 'Big Hero 6', year: 2014 },
  { slug: 'absolutely-fabulous', prompt: SHOW, correct: 'Absolutely Fabulous', incorrect: ['French and Saunders', 'Keeping Up Appearances', 'Miranda'], difficulty: 'medium', kind: 'tv', query: 'Absolutely Fabulous', year: 1992 },
  { slug: 'keeping-up-appearances', prompt: SHOW, correct: 'Keeping Up Appearances', incorrect: ['One Foot in the Grave', 'Last of the Summer Wine', 'The Good Life'], difficulty: 'medium', kind: 'tv', query: 'Keeping Up Appearances', year: 1990 },
  { slug: 'frasier', prompt: SHOW, correct: 'Frasier', incorrect: ['Cheers', 'Seinfeld', 'Everybody Loves Raymond'], difficulty: 'medium', kind: 'tv', query: 'Frasier', year: 1993 },
  { slug: 'lost-tv', prompt: SHOW, correct: 'Lost', incorrect: ['Manifest', 'Yellowjackets', 'The Leftovers'], difficulty: 'medium', kind: 'tv', query: 'Lost', year: 2004 },
  { slug: 'dexter', prompt: SHOW, correct: 'Dexter', incorrect: ['Hannibal', 'Mindhunter', 'You'], difficulty: 'medium', kind: 'tv', query: 'Dexter', year: 2006 },
  { slug: 'x-files', prompt: SHOW, correct: 'The X-Files', incorrect: ['Fringe', 'Twin Peaks', 'Millennium'], difficulty: 'medium', kind: 'tv', query: 'The X-Files', year: 1993 },
  { slug: 'gossip-girl', prompt: SHOW, correct: 'Gossip Girl', incorrect: ['The O.C.', 'Pretty Little Liars', 'One Tree Hill'], difficulty: 'medium', kind: 'tv', query: 'Gossip Girl', year: 2007 },
  { slug: 'desperate-housewives', prompt: SHOW, correct: 'Desperate Housewives', incorrect: ['Big Little Lies', 'Devious Maids', 'Sex and the City'], difficulty: 'medium', kind: 'tv', query: 'Desperate Housewives', year: 2004 },
  { slug: 'sex-and-the-city', prompt: SHOW, correct: 'Sex and the City', incorrect: ['Girls', 'Ally McBeal', 'Desperate Housewives'], difficulty: 'medium', kind: 'tv', query: 'Sex and the City', year: 1998 },
  { slug: 'queens-gambit', prompt: SHOW, correct: 'The Queen’s Gambit', incorrect: ['Mrs. America', 'Mad Men', 'The Marvelous Mrs. Maisel'], difficulty: 'medium', kind: 'tv', query: 'The Queen\'s Gambit', year: 2020 },
  { slug: 'money-heist', prompt: SHOW, correct: 'Money Heist', incorrect: ['Narcos', 'Elite', 'Lupin'], difficulty: 'medium', kind: 'tv', query: 'Money Heist', year: 2017 },
  { slug: 'heartstopper', prompt: SHOW, correct: 'Heartstopper', incorrect: ['Sex Education', 'Never Have I Ever', 'Young Royals'], difficulty: 'medium', kind: 'tv', query: 'Heartstopper', year: 2022 },
  { slug: 'skins', prompt: SHOW, correct: 'Skins', incorrect: ['The Inbetweeners', 'Misfits', 'Hollyoaks'], difficulty: 'medium', kind: 'tv', query: 'Skins', year: 2007 },
  { slug: 'merlin', prompt: SHOW, correct: 'Merlin', incorrect: ['Atlantis', 'Robin Hood', 'Legend of the Seeker'], difficulty: 'medium', kind: 'tv', query: 'Merlin', year: 2008 },
  { slug: 'doc-martin', prompt: SHOW, correct: 'Doc Martin', incorrect: ['Heartbeat', 'All Creatures Great and Small', 'Death in Paradise'], difficulty: 'medium', kind: 'tv', query: 'Doc Martin', year: 2004 },
  { slug: 'miranda', prompt: SHOW, correct: 'Miranda', incorrect: ['Not Going Out', 'Green Wing', 'Motherland'], difficulty: 'medium', kind: 'tv', query: 'Miranda', year: 2009 },
  { slug: 'little-britain', prompt: SHOW, correct: 'Little Britain', incorrect: ['The Catherine Tate Show', 'The League of Gentlemen', 'Come Fly with Me'], difficulty: 'medium', kind: 'tv', query: 'Little Britain', year: 2003 },
  { slug: 'alan-partridge', prompt: SHOW, correct: 'I’m Alan Partridge', incorrect: ['The Day Today', 'Knowing Me, Knowing You', 'People Just Do Nothing'], difficulty: 'medium', kind: 'tv', query: 'I\'m Alan Partridge', year: 1997 },
  { slug: 'futurama', prompt: SHOW, correct: 'Futurama', incorrect: ['The Simpsons', 'Rick and Morty', 'Solar Opposites'], difficulty: 'medium', kind: 'tv', query: 'Futurama', year: 1999 },
  { slug: 'fallout-tv', prompt: SHOW, correct: 'Fallout', incorrect: ['The Last of Us', 'Station Eleven', 'Silo'], difficulty: 'medium', kind: 'tv', query: 'Fallout', year: 2024 },
  { slug: 'mrs-browns-boys', prompt: SHOW, correct: 'Mrs Brown’s Boys', incorrect: ['Still Game', 'Benidorm', 'Two Doors Down'], difficulty: 'medium', kind: 'tv', query: 'Mrs. Brown\'s Boys', year: 2011 },
  { slug: 'whiplash', prompt: FILM, correct: 'Whiplash', incorrect: ['La La Land', 'Black Swan', 'Birdman'], difficulty: 'hard', kind: 'movie', query: 'Whiplash', year: 2014 },
  { slug: 'baby-driver', prompt: FILM, correct: 'Baby Driver', incorrect: ['Drive', 'The Driver', 'Gone in 60 Seconds'], difficulty: 'hard', kind: 'movie', query: 'Baby Driver', year: 2017 },
  { slug: 'little-women', prompt: FILM, correct: 'Little Women', incorrect: ['Pride & Prejudice', 'Lady Bird', 'Emma.'], difficulty: 'hard', kind: 'movie', query: 'Little Women', year: 2019 },
  { slug: 'atonement', prompt: FILM, correct: 'Atonement', incorrect: ['The English Patient', 'Pride & Prejudice', 'Brideshead Revisited'], difficulty: 'hard', kind: 'movie', query: 'Atonement', year: 2007 },
  { slug: 'iron-giant', prompt: FILM, correct: 'The Iron Giant', incorrect: ['WALL·E', 'Robots', 'Big Hero 6'], difficulty: 'hard', kind: 'movie', query: 'The Iron Giant', year: 1999 },
  { slug: 'phoenix-nights', prompt: SHOW, correct: 'Phoenix Nights', incorrect: ['The Royle Family', 'Early Doors', 'Benidorm'], difficulty: 'hard', kind: 'tv', query: 'Phoenix Nights', year: 2001 },
  { slug: 'detectorists', prompt: SHOW, correct: 'Detectorists', incorrect: ['This Country', 'Toast of London', 'The Outlaws'], difficulty: 'hard', kind: 'tv', query: 'Detectorists', year: 2014 },
  { slug: 'twin-peaks', prompt: SHOW, correct: 'Twin Peaks', incorrect: ['The X-Files', 'Northern Exposure', 'True Detective'], difficulty: 'hard', kind: 'tv', query: 'Twin Peaks', year: 1990 },
  { slug: 'thick-of-it', prompt: SHOW, correct: 'The Thick of It', incorrect: ['Yes Minister', 'W1A', 'Veep'], difficulty: 'hard', kind: 'tv', query: 'The Thick of It', year: 2005 },
  { slug: 'top-boy', prompt: SHOW, correct: 'Top Boy', incorrect: ['Gangs of London', 'Kiri', 'The Wire'], difficulty: 'hard', kind: 'tv', query: 'Top Boy', year: 2011 },
  { slug: 'school-of-rock', prompt: FILM, correct: 'School of Rock', incorrect: ['Mr. Holland’s Opus', 'Sister Act 2: Back in the Habit', 'Bad Teacher'], difficulty: 'easy', kind: 'movie', query: 'School of Rock', year: 2003 },
  { slug: 'happy-feet', prompt: FILM, correct: 'Happy Feet', incorrect: ['Surf’s Up', 'Madagascar', 'Ice Age'], difficulty: 'easy', kind: 'movie', query: 'Happy Feet', year: 2006 },
  { slug: 'the-hangover', prompt: FILM, correct: 'The Hangover', incorrect: ['Bridesmaids', 'Old School', 'Step Brothers'], difficulty: 'easy', kind: 'movie', query: 'The Hangover', year: 2009 },
  { slug: 'brave', prompt: FILM, correct: 'Brave', incorrect: ['Tangled', 'Frozen', 'How to Train Your Dragon'], difficulty: 'easy', kind: 'movie', query: 'Brave', year: 2012 },
  { slug: 'sing-film', prompt: FILM, correct: 'Sing', incorrect: ['Zootropolis', 'The Secret Life of Pets', 'Trolls'], difficulty: 'easy', kind: 'movie', query: 'Sing', year: 2016 },
  { slug: 'kpop-demon-hunters', prompt: FILM, correct: 'KPop Demon Hunters', incorrect: ['Spider-Man: Into the Spider-Verse', 'Turning Red', 'Wish'], difficulty: 'easy', kind: 'movie', query: 'KPop Demon Hunters', year: 2025 },
  { slug: 'austin-powers', prompt: FILM, correct: 'Austin Powers: International Man of Mystery', incorrect: ['Johnny English', 'The Pink Panther', 'Spy'], difficulty: 'easy', kind: 'movie', query: 'Austin Powers: International Man of Mystery', year: 1997 },
  { slug: 'hey-duggee', prompt: SHOW, correct: 'Hey Duggee', incorrect: ['Bluey', 'Peppa Pig', 'Ben & Holly’s Little Kingdom'], difficulty: 'easy', kind: 'tv', query: 'Hey Duggee', year: 2014 },
  { slug: 'paw-patrol', prompt: SHOW, correct: 'PAW Patrol', incorrect: ['Bluey', 'Fireman Sam', 'Thomas & Friends'], difficulty: 'easy', kind: 'tv', query: 'PAW Patrol', year: 2013 },
  { slug: 'in-the-night-garden', prompt: SHOW, correct: 'In the Night Garden', incorrect: ['Teletubbies', 'Waybuloo', 'Tweenies'], difficulty: 'easy', kind: 'tv', query: 'In the Night Garden', year: 2007 },
  { slug: 'one-foot-in-the-grave', prompt: SHOW, correct: 'One Foot in the Grave', incorrect: ['Keeping Up Appearances', 'Last of the Summer Wine', 'Waiting for God'], difficulty: 'medium', kind: 'tv', query: 'One Foot in the Grave', year: 1990 },
  { slug: 'horrible-histories', prompt: SHOW, correct: 'Horrible Histories', incorrect: ['Blue Peter', 'Maid Marian and Her Merry Men', 'Operation Ouch!'], difficulty: 'medium', kind: 'tv', query: 'Horrible Histories', year: 2009 },
  { slug: 'parent-trap', prompt: FILM, correct: 'The Parent Trap', incorrect: ['Freaky Friday', 'It Takes Two', 'Mrs. Doubtfire'], difficulty: 'medium', kind: 'movie', query: 'The Parent Trap', year: 1998 },
  { slug: 'hook-film', prompt: FILM, correct: 'Hook', incorrect: ['Peter Pan', 'Jumanji', 'The Goonies'], difficulty: 'medium', kind: 'movie', query: 'Hook', year: 1991 },
  { slug: 'scream-film', prompt: FILM, correct: 'Scream', incorrect: ['I Know What You Did Last Summer', 'Urban Legend', 'Halloween'], difficulty: 'medium', kind: 'movie', query: 'Scream', year: 1996 },
  { slug: 'enchanted', prompt: FILM, correct: 'Enchanted', incorrect: ['Ella Enchanted', 'Mirror Mirror', 'Into the Woods'], difficulty: 'medium', kind: 'movie', query: 'Enchanted', year: 2007 },
  { slug: 'a-quiet-place', prompt: FILM, correct: 'A Quiet Place', incorrect: ['Bird Box', 'Signs', 'Don’t Breathe'], difficulty: 'medium', kind: 'movie', query: 'A Quiet Place', year: 2018 },
  { slug: 'soul-pixar', prompt: FILM, correct: 'Soul', incorrect: ['Inside Out', 'Coco', 'Onward'], difficulty: 'medium', kind: 'movie', query: 'Soul', year: 2020 },
  { slug: 'turning-red', prompt: FILM, correct: 'Turning Red', incorrect: ['Luca', 'Encanto', 'Elemental'], difficulty: 'medium', kind: 'movie', query: 'Turning Red', year: 2022 },
  { slug: 'meet-the-parents', prompt: FILM, correct: 'Meet the Parents', incorrect: ['Along Came Polly', 'The Wedding Singer', 'Zoolander'], difficulty: 'medium', kind: 'movie', query: 'Meet the Parents', year: 2000 },
  { slug: 'napoleon-dynamite', prompt: FILM, correct: 'Napoleon Dynamite', incorrect: ['Nacho Libre', 'Superbad', 'Rushmore'], difficulty: 'hard', kind: 'movie', query: 'Napoleon Dynamite', year: 2004 },
  { slug: 'juno', prompt: FILM, correct: 'Juno', incorrect: ['Lady Bird', 'Little Miss Sunshine', 'Easy A'], difficulty: 'hard', kind: 'movie', query: 'Juno', year: 2007 },
  { slug: 'little-miss-sunshine', prompt: FILM, correct: 'Little Miss Sunshine', incorrect: ['Juno', 'The Royal Tenenbaums', 'Captain Fantastic'], difficulty: 'hard', kind: 'movie', query: 'Little Miss Sunshine', year: 2006 },
  { slug: 'ex-machina', prompt: FILM, correct: 'Ex Machina', incorrect: ['Her', 'Annihilation', 'Upgrade'], difficulty: 'hard', kind: 'movie', query: 'Ex Machina', year: 2014 },
  { slug: 'the-favourite', prompt: FILM, correct: 'The Favourite', incorrect: ['Mary Queen of Scots', 'Poor Things', 'Victoria & Abdul'], difficulty: 'hard', kind: 'movie', query: 'The Favourite', year: 2018 },
  { slug: 'men-behaving-badly', prompt: SHOW, correct: 'Men Behaving Badly', incorrect: ['Game On', 'Coupling', 'The Royle Family'], difficulty: 'hard', kind: 'tv', query: 'Men Behaving Badly', year: 1992 },
  { slug: 'spaced', prompt: SHOW, correct: 'Spaced', incorrect: ['Black Books', 'Peep Show', 'The IT Crowd'], difficulty: 'hard', kind: 'tv', query: 'Spaced', year: 1999 },
  { slug: 'this-country', prompt: SHOW, correct: 'This Country', incorrect: ['Detectorists', 'Man Like Mobeen', 'Stath Lets Flats'], difficulty: 'hard', kind: 'tv', query: 'This Country', year: 2017 },
  { slug: 'curb', prompt: SHOW, correct: 'Curb Your Enthusiasm', incorrect: ['Seinfeld', 'Arrested Development', 'Veep'], difficulty: 'hard', kind: 'tv', query: 'Curb Your Enthusiasm', year: 2000 },
  { slug: 'true-detective', prompt: SHOW, correct: 'True Detective', incorrect: ['Mindhunter', 'Fargo', 'The Killing'], difficulty: 'hard', kind: 'tv', query: 'True Detective', year: 2014 },
  // Fourth batch, 5–6 October 2026: 296 → about 450 (docs/decisions/screens-growth.md).
  // All first shown in 1990 or later, so the eight-title cap on pre-1990 holds; leans medium.
  { slug: 'the-silence-of-the-lambs', prompt: FILM, correct: 'The Silence of the Lambs', incorrect: ['Se7en', 'Hannibal', 'Zodiac'], difficulty: 'medium', kind: 'movie', query: 'The Silence of the Lambs', year: 1991 },
  { slug: 'sleepless-in-seattle', prompt: FILM, correct: 'Sleepless in Seattle', incorrect: ['You’ve Got Mail', 'When Harry Met Sally...', 'The Holiday'], difficulty: 'medium', kind: 'movie', query: 'Sleepless in Seattle', year: 1993 },
  { slug: 'youve-got-mail', prompt: FILM, correct: 'You’ve Got Mail', incorrect: ['Sleepless in Seattle', 'Notting Hill', 'Serendipity'], difficulty: 'medium', kind: 'movie', query: 'You\'ve Got Mail', year: 1998 },
  { slug: 'jerry-maguire', prompt: FILM, correct: 'Jerry Maguire', incorrect: ['Any Given Sunday', 'Moneyball', 'The Blind Side'], difficulty: 'medium', kind: 'movie', query: 'Jerry Maguire', year: 1996 },
  { slug: 'good-will-hunting', prompt: FILM, correct: 'Good Will Hunting', incorrect: ['Dead Poets Society', 'A Beautiful Mind', 'Finding Forrester'], difficulty: 'medium', kind: 'movie', query: 'Good Will Hunting', year: 1997 },
  { slug: 'the-sixth-sense', prompt: FILM, correct: 'The Sixth Sense', incorrect: ['The Others', 'Signs', 'Unbreakable'], difficulty: 'medium', kind: 'movie', query: 'The Sixth Sense', year: 1999 },
  { slug: 'se7en', prompt: FILM, correct: 'Se7en', incorrect: ['The Silence of the Lambs', 'Zodiac', 'Prisoners'], difficulty: 'hard', kind: 'movie', query: 'Se7en', year: 1995 },
  { slug: 'goodfellas', prompt: FILM, correct: 'Goodfellas', incorrect: ['Casino', 'The Departed', 'The Irishman'], difficulty: 'medium', kind: 'movie', query: 'Goodfellas', year: 1990 },
  { slug: 'reservoir-dogs', prompt: FILM, correct: 'Reservoir Dogs', incorrect: ['Pulp Fiction', 'Jackie Brown', 'The Usual Suspects'], difficulty: 'medium', kind: 'movie', query: 'Reservoir Dogs', year: 1992 },
  { slug: 'speed', prompt: FILM, correct: 'Speed', incorrect: ['Con Air', 'Die Hard with a Vengeance', 'Unstoppable'], difficulty: 'medium', kind: 'movie', query: 'Speed', year: 1994 },
  { slug: 'mission-impossible', prompt: FILM, correct: 'Mission: Impossible', incorrect: ['The Bourne Identity', 'Ronin', 'The Saint'], difficulty: 'easy', kind: 'movie', query: 'Mission: Impossible', year: 1996 },
  { slug: 'armageddon', prompt: FILM, correct: 'Armageddon', incorrect: ['Deep Impact', 'The Core', 'Independence Day'], difficulty: 'medium', kind: 'movie', query: 'Armageddon', year: 1998 },
  { slug: 'the-mummy', prompt: FILM, correct: 'The Mummy', incorrect: ['Indiana Jones and the Kingdom of the Crystal Skull', 'The Scorpion King', 'Tomb Raider'], difficulty: 'medium', kind: 'movie', query: 'The Mummy', year: 1999 },
  { slug: 'the-princess-diaries', prompt: FILM, correct: 'The Princess Diaries', incorrect: ['Ella Enchanted', 'What a Girl Wants', '13 Going on 30'], difficulty: 'medium', kind: 'movie', query: 'The Princess Diaries', year: 2001 },
  { slug: '13-going-on-30', prompt: FILM, correct: '13 Going on 30', incorrect: ['Big', 'The Princess Diaries', '17 Again'], difficulty: 'medium', kind: 'movie', query: '13 Going on 30', year: 2004 },
  { slug: 'the-proposal', prompt: FILM, correct: 'The Proposal', incorrect: ['27 Dresses', 'Two Weeks Notice', 'Leap Year'], difficulty: 'medium', kind: 'movie', query: 'The Proposal', year: 2009 },
  { slug: '10-things-i-hate-about-you', prompt: FILM, correct: '10 Things I Hate About You', incorrect: ['She’s All That', 'Clueless', 'Never Been Kissed'], difficulty: 'medium', kind: 'movie', query: '10 Things I Hate About You', year: 1999 },
  { slug: 'anchorman-the-legend-of-ron-burgundy', prompt: FILM, correct: 'Anchorman: The Legend of Ron Burgundy', incorrect: ['Talladega Nights', 'Step Brothers', 'Zoolander'], difficulty: 'medium', kind: 'movie', query: 'Anchorman: The Legend of Ron Burgundy', year: 2004 },
  { slug: 'zoolander', prompt: FILM, correct: 'Zoolander', incorrect: ['Anchorman: The Legend of Ron Burgundy', 'Dodgeball', 'Meet the Parents'], difficulty: 'medium', kind: 'movie', query: 'Zoolander', year: 2001 },
  { slug: 'dodgeball-a-true-underdog-story', prompt: FILM, correct: 'Dodgeball: A True Underdog Story', incorrect: ['Zoolander', 'Blades of Glory', 'Anchorman: The Legend of Ron Burgundy'], difficulty: 'hard', kind: 'movie', query: 'Dodgeball: A True Underdog Story', year: 2004 },
  { slug: 'hocus-pocus', prompt: FILM, correct: 'Hocus Pocus', incorrect: ['The Addams Family', 'The Craft', 'Practical Magic'], difficulty: 'medium', kind: 'movie', query: 'Hocus Pocus', year: 1993 },
  { slug: 'the-addams-family', prompt: FILM, correct: 'The Addams Family', incorrect: ['Hocus Pocus', 'Beetlejuice', 'Casper'], difficulty: 'medium', kind: 'movie', query: 'The Addams Family', year: 1991 },
  { slug: 'babe', prompt: FILM, correct: 'Babe', incorrect: ['Charlotte’s Web', 'Stuart Little', 'Chicken Run'], difficulty: 'medium', kind: 'movie', query: 'Babe', year: 1995 },
  { slug: 'stuart-little', prompt: FILM, correct: 'Stuart Little', incorrect: ['Babe', 'Ratatouille', 'Garfield'], difficulty: 'medium', kind: 'movie', query: 'Stuart Little', year: 1999 },
  { slug: 'luca', prompt: FILM, correct: 'Luca', incorrect: ['Turning Red', 'Coco', 'Elemental'], difficulty: 'medium', kind: 'movie', query: 'Luca', year: 2021 },
  { slug: 'wreck-it-ralph', prompt: FILM, correct: 'Wreck-It Ralph', incorrect: ['Big Hero 6', 'Zootropolis', 'Bolt'], difficulty: 'medium', kind: 'movie', query: 'Wreck-It Ralph', year: 2012 },
  { slug: 'minions', prompt: FILM, correct: 'Minions', incorrect: ['Despicable Me', 'The Secret Life of Pets', 'Sing'], difficulty: 'easy', kind: 'movie', query: 'Minions', year: 2015 },
  { slug: 'the-secret-life-of-pets', prompt: FILM, correct: 'The Secret Life of Pets', incorrect: ['Minions', 'Bolt', 'Zootropolis'], difficulty: 'medium', kind: 'movie', query: 'The Secret Life of Pets', year: 2016 },
  { slug: 'trolls', prompt: FILM, correct: 'Trolls', incorrect: ['Smurfs: The Lost Village', 'Sing', 'Hotel Transylvania'], difficulty: 'medium', kind: 'movie', query: 'Trolls', year: 2016 },
  { slug: 'hotel-transylvania', prompt: FILM, correct: 'Hotel Transylvania', incorrect: ['The Addams Family', 'Monster House', 'Trolls'], difficulty: 'medium', kind: 'movie', query: 'Hotel Transylvania', year: 2012 },
  { slug: 'cloudy-with-a-chance-of-meatballs', prompt: FILM, correct: 'Cloudy with a Chance of Meatballs', incorrect: ['Meet the Robinsons', 'Megamind', 'Hotel Transylvania'], difficulty: 'medium', kind: 'movie', query: 'Cloudy with a Chance of Meatballs', year: 2009 },
  { slug: 'shaun-the-sheep-movie', prompt: FILM, correct: 'Shaun the Sheep Movie', incorrect: ['Chicken Run', 'Early Man', 'Wallace & Gromit: The Curse of the Were-Rabbit'], difficulty: 'medium', kind: 'movie', query: 'Shaun the Sheep Movie', year: 2015 },
  { slug: 'arthur-christmas', prompt: FILM, correct: 'Arthur Christmas', incorrect: ['The Polar Express', 'Klaus', 'Elf'], difficulty: 'hard', kind: 'movie', query: 'Arthur Christmas', year: 2011 },
  { slug: 'fantastic-beasts-and-where-to-find-them', prompt: FILM, correct: 'Fantastic Beasts and Where to Find Them', incorrect: ['Harry Potter and the Philosopher’s Stone', 'The Golden Compass', 'The Chronicles of Narnia'], difficulty: 'medium', kind: 'movie', query: 'Fantastic Beasts and Where to Find Them', year: 2016 },
  { slug: 'the-hobbit-an-unexpected-journey', prompt: FILM, correct: 'The Hobbit: An Unexpected Journey', incorrect: ['The Lord of the Rings: The Fellowship of the Ring', 'The Chronicles of Narnia', 'Willow'], difficulty: 'medium', kind: 'movie', query: 'The Hobbit: An Unexpected Journey', year: 2012 },
  { slug: 'pearl-harbor', prompt: FILM, correct: 'Pearl Harbor', incorrect: ['Saving Private Ryan', 'Midway', 'Dunkirk'], difficulty: 'medium', kind: 'movie', query: 'Pearl Harbor', year: 2001 },
  { slug: 'the-departed', prompt: FILM, correct: 'The Departed', incorrect: ['Goodfellas', 'Infernal Affairs', 'The Town'], difficulty: 'hard', kind: 'movie', query: 'The Departed', year: 2006 },
  { slug: 'no-country-for-old-men', prompt: FILM, correct: 'No Country for Old Men', incorrect: ['Fargo', 'Hell or High Water', 'There Will Be Blood'], difficulty: 'hard', kind: 'movie', query: 'No Country for Old Men', year: 2007 },
  { slug: 'the-prestige', prompt: FILM, correct: 'The Prestige', incorrect: ['The Illusionist', 'Now You See Me', 'Inception'], difficulty: 'hard', kind: 'movie', query: 'The Prestige', year: 2006 },
  { slug: 'tenet', prompt: FILM, correct: 'Tenet', incorrect: ['Inception', 'Interstellar', 'Looper'], difficulty: 'hard', kind: 'movie', query: 'Tenet', year: 2020 },
  { slug: 'the-batman', prompt: FILM, correct: 'The Batman', incorrect: ['The Dark Knight', 'Joker', 'Batman Begins'], difficulty: 'medium', kind: 'movie', query: 'The Batman', year: 2022 },
  { slug: 'thor-ragnarok', prompt: FILM, correct: 'Thor: Ragnarok', incorrect: ['Guardians of the Galaxy', 'Thor: The Dark World', 'Black Panther'], difficulty: 'medium', kind: 'movie', query: 'Thor: Ragnarok', year: 2017 },
  { slug: 'doctor-strange', prompt: FILM, correct: 'Doctor Strange', incorrect: ['Thor: Ragnarok', 'Ant-Man', 'Inception'], difficulty: 'medium', kind: 'movie', query: 'Doctor Strange', year: 2016 },
  { slug: 'aquaman', prompt: FILM, correct: 'Aquaman', incorrect: ['Wonder Woman', 'Black Panther: Wakanda Forever', 'The Little Mermaid'], difficulty: 'medium', kind: 'movie', query: 'Aquaman', year: 2018 },
  { slug: 'logan', prompt: FILM, correct: 'Logan', incorrect: ['X-Men', 'The Wolverine', 'Deadpool'], difficulty: 'hard', kind: 'movie', query: 'Logan', year: 2017 },
  { slug: 'moulin-rouge', prompt: FILM, correct: 'Moulin Rouge!', incorrect: ['The Great Gatsby', 'Chicago', 'Romeo + Juliet'], difficulty: 'medium', kind: 'movie', query: 'Moulin Rouge!', year: 2001 },
  { slug: 'hairspray', prompt: FILM, correct: 'Hairspray', incorrect: ['Grease', 'Footloose', 'Dreamgirls'], difficulty: 'medium', kind: 'movie', query: 'Hairspray', year: 2007 },
  { slug: 'a-star-is-born', prompt: FILM, correct: 'A Star Is Born', incorrect: ['Bohemian Rhapsody', 'Walk the Line', 'Rocketman'], difficulty: 'medium', kind: 'movie', query: 'A Star Is Born', year: 2018 },
  { slug: 'elvis', prompt: FILM, correct: 'Elvis', incorrect: ['Rocketman', 'Bohemian Rhapsody', 'Walk the Line'], difficulty: 'medium', kind: 'movie', query: 'Elvis', year: 2022 },
  { slug: 'the-bourne-identity', prompt: FILM, correct: 'The Bourne Identity', incorrect: ['Mission: Impossible', 'Taken', 'Jason Bourne'], difficulty: 'medium', kind: 'movie', query: 'The Bourne Identity', year: 2002 },
  { slug: 'goldeneye', prompt: FILM, correct: 'GoldenEye', incorrect: ['Tomorrow Never Dies', 'Casino Royale', 'The World Is Not Enough'], difficulty: 'medium', kind: 'movie', query: 'GoldenEye', year: 1995 },
  { slug: 'the-worlds-end', prompt: FILM, correct: 'The World’s End', incorrect: ['Hot Fuzz', 'Shaun of the Dead', 'Paul'], difficulty: 'hard', kind: 'movie', query: 'The World\'s End', year: 2013 },
  { slug: 'attack-the-block', prompt: FILM, correct: 'Attack the Block', incorrect: ['Shaun of the Dead', 'Super 8', 'Kidulthood'], difficulty: 'hard', kind: 'movie', query: 'Attack the Block', year: 2011 },
  { slug: 'yesterday', prompt: FILM, correct: 'Yesterday', incorrect: ['Rocketman', 'Begin Again', 'Sing Street'], difficulty: 'medium', kind: 'movie', query: 'Yesterday', year: 2019 },
  { slug: 'east-is-east', prompt: FILM, correct: 'East Is East', incorrect: ['Bend It Like Beckham', 'Billy Elliot', 'Brassed Off'], difficulty: 'medium', kind: 'movie', query: 'East Is East', year: 1999 },
  { slug: 'brassed-off', prompt: FILM, correct: 'Brassed Off', incorrect: ['The Full Monty', 'Billy Elliot', 'Calendar Girls'], difficulty: 'hard', kind: 'movie', query: 'Brassed Off', year: 1996 },
  { slug: 'pride', prompt: FILM, correct: 'Pride', incorrect: ['Billy Elliot', 'Made in Dagenham', 'Brassed Off'], difficulty: 'hard', kind: 'movie', query: 'Pride', year: 2014 },
  { slug: 'belfast', prompt: FILM, correct: 'Belfast', incorrect: ['Derry Girls', 'Sing Street', 'Hope and Glory'], difficulty: 'hard', kind: 'movie', query: 'Belfast', year: 2021 },
  { slug: 'the-banshees-of-inisherin', prompt: FILM, correct: 'The Banshees of Inisherin', incorrect: ['In Bruges', 'Calvary', 'The Guard'], difficulty: 'hard', kind: 'movie', query: 'The Banshees of Inisherin', year: 2022 },
  { slug: 'arrival', prompt: FILM, correct: 'Arrival', incorrect: ['Interstellar', 'Contact', 'Annihilation'], difficulty: 'hard', kind: 'movie', query: 'Arrival', year: 2016 },
  { slug: 'ready-player-one', prompt: FILM, correct: 'Ready Player One', incorrect: ['Tron: Legacy', 'Free Guy', 'Jumanji: Welcome to the Jungle'], difficulty: 'medium', kind: 'movie', query: 'Ready Player One', year: 2018 },
  { slug: 'it-film', prompt: FILM, correct: 'It', incorrect: ['Annabelle', 'The Conjuring', 'Stranger Things'], difficulty: 'medium', kind: 'movie', query: 'It', year: 2017 },
  { slug: 'saw', prompt: FILM, correct: 'Saw', incorrect: ['Se7en', 'Hostel', 'The Purge'], difficulty: 'hard', kind: 'movie', query: 'Saw', year: 2004 },
  { slug: 'the-blair-witch-project', prompt: FILM, correct: 'The Blair Witch Project', incorrect: ['Paranormal Activity', 'The Ring', 'Cloverfield'], difficulty: 'hard', kind: 'movie', query: 'The Blair Witch Project', year: 1999 },
  { slug: 'the-polar-express', prompt: FILM, correct: 'The Polar Express', incorrect: ['Elf', 'Arthur Christmas', 'The Grinch'], difficulty: 'medium', kind: 'movie', query: 'The Polar Express', year: 2004 },
  { slug: 'nativity', prompt: FILM, correct: 'Nativity!', incorrect: ['Love Actually', 'Elf', 'Arthur Christmas'], difficulty: 'hard', kind: 'movie', query: 'Nativity!', year: 2009 },
  { slug: 'the-green-mile', prompt: FILM, correct: 'The Green Mile', incorrect: ['The Shawshank Redemption', 'Cast Away', 'Forrest Gump'], difficulty: 'medium', kind: 'movie', query: 'The Green Mile', year: 1999 },
  { slug: 'apollo-13', prompt: FILM, correct: 'Apollo 13', incorrect: ['Gravity', 'The Martian', 'First Man'], difficulty: 'medium', kind: 'movie', query: 'Apollo 13', year: 1995 },
  { slug: 'liar-liar', prompt: FILM, correct: 'Liar Liar', incorrect: ['Bruce Almighty', 'The Mask', 'Ace Ventura: Pet Detective'], difficulty: 'medium', kind: 'movie', query: 'Liar Liar', year: 1997 },
  { slug: 'ace-ventura-pet-detective', prompt: FILM, correct: 'Ace Ventura: Pet Detective', incorrect: ['Dumb and Dumber', 'The Mask', 'Liar Liar'], difficulty: 'medium', kind: 'movie', query: 'Ace Ventura: Pet Detective', year: 1994 },
  { slug: 'dumb-and-dumber', prompt: FILM, correct: 'Dumb and Dumber', incorrect: ['Ace Ventura: Pet Detective', 'The Mask', 'There’s Something About Mary'], difficulty: 'medium', kind: 'movie', query: 'Dumb and Dumber', year: 1994 },
  { slug: 'bruce-almighty', prompt: FILM, correct: 'Bruce Almighty', incorrect: ['Liar Liar', 'Evan Almighty', 'Click'], difficulty: 'medium', kind: 'movie', query: 'Bruce Almighty', year: 2003 },
  { slug: 'i-am-legend', prompt: FILM, correct: 'I Am Legend', incorrect: ['28 Days Later', 'World War Z', 'Children of Men'], difficulty: 'medium', kind: 'movie', query: 'I Am Legend', year: 2007 },
  { slug: 'hercules', prompt: FILM, correct: 'Hercules', incorrect: ['Aladdin', 'Mulan', 'Tarzan'], difficulty: 'medium', kind: 'movie', query: 'Hercules', year: 1997 },
  { slug: 'tarzan', prompt: FILM, correct: 'Tarzan', incorrect: ['The Jungle Book', 'Hercules', 'Pocahontas'], difficulty: 'medium', kind: 'movie', query: 'Tarzan', year: 1999 },
  { slug: 'pocahontas', prompt: FILM, correct: 'Pocahontas', incorrect: ['Mulan', 'Tarzan', 'Brave'], difficulty: 'medium', kind: 'movie', query: 'Pocahontas', year: 1995 },
  { slug: 'the-princess-and-the-frog', prompt: FILM, correct: 'The Princess and the Frog', incorrect: ['Tangled', 'Enchanted', 'Encanto'], difficulty: 'hard', kind: 'movie', query: 'The Princess and the Frog', year: 2009 },
  { slug: 'the-bodyguard', prompt: FILM, correct: 'The Bodyguard', incorrect: ['Ghost', 'Pretty Woman', 'Notting Hill'], difficulty: 'medium', kind: 'movie', query: 'The Bodyguard', year: 1992 },
  { slug: 'thelma-and-louise', prompt: FILM, correct: 'Thelma & Louise', incorrect: ['Bonnie and Clyde', 'Natural Born Killers', 'Fried Green Tomatoes'], difficulty: 'hard', kind: 'movie', query: 'Thelma & Louise', year: 1991 },
  { slug: 'troy', prompt: FILM, correct: 'Troy', incorrect: ['Gladiator', '300', 'Alexander'], difficulty: 'medium', kind: 'movie', query: 'Troy', year: 2004 },
  { slug: '300', prompt: FILM, correct: '300', incorrect: ['Troy', 'Gladiator', 'Immortals'], difficulty: 'medium', kind: 'movie', query: '300', year: 2006 },
  { slug: 'the-great-gatsby', prompt: FILM, correct: 'The Great Gatsby', incorrect: ['Moulin Rouge!', 'The Wolf of Wall Street', 'Romeo + Juliet'], difficulty: 'medium', kind: 'movie', query: 'The Great Gatsby', year: 2013 },
  { slug: 'hollyoaks', prompt: SHOW, correct: 'Hollyoaks', incorrect: ['Waterloo Road', 'Grange Hill', 'Byker Grove'], difficulty: 'medium', kind: 'tv', query: 'Hollyoaks', year: 1995 },
  { slug: 'bottom', prompt: SHOW, correct: 'Bottom', incorrect: ['The Young Ones', 'Men Behaving Badly', 'Red Dwarf'], difficulty: 'hard', kind: 'tv', query: 'Bottom', year: 1991 },
  { slug: 'the-league-of-gentlemen', prompt: SHOW, correct: 'The League of Gentlemen', incorrect: ['Inside No. 9', 'Little Britain', 'The Mighty Boosh'], difficulty: 'hard', kind: 'tv', query: 'The League of Gentlemen', year: 1999 },
  { slug: 'extras', prompt: SHOW, correct: 'Extras', incorrect: ['The Office', 'After Life', 'Episodes'], difficulty: 'medium', kind: 'tv', query: 'Extras', year: 2005 },
  { slug: 'after-life', prompt: SHOW, correct: 'After Life', incorrect: ['Extras', 'Fleabag', 'The Office'], difficulty: 'medium', kind: 'tv', query: 'After Life', year: 2019 },
  { slug: 'not-going-out', prompt: SHOW, correct: 'Not Going Out', incorrect: ['Miranda', 'Outnumbered', 'Friday Night Dinner'], difficulty: 'medium', kind: 'tv', query: 'Not Going Out', year: 2006 },
  { slug: 'benidorm', prompt: SHOW, correct: 'Benidorm', incorrect: ['Two Pints of Lager and a Packet of Crisps', 'Gavin & Stacey', 'The Royle Family'], difficulty: 'medium', kind: 'tv', query: 'Benidorm', year: 2007 },
  { slug: 'still-game', prompt: SHOW, correct: 'Still Game', incorrect: ['Rab C. Nesbitt', 'Two Doors Down', 'Mrs Brown’s Boys'], difficulty: 'medium', kind: 'tv', query: 'Still Game', year: 2002 },
  { slug: 'peter-kays-car-share', prompt: SHOW, correct: 'Peter Kay’s Car Share', incorrect: ['Phoenix Nights', 'Gavin & Stacey', 'Detectorists'], difficulty: 'medium', kind: 'tv', query: 'Peter Kay\'s Car Share', year: 2015 },
  { slug: 'motherland', prompt: SHOW, correct: 'Motherland', incorrect: ['Outnumbered', 'Breeders', 'Catastrophe'], difficulty: 'hard', kind: 'tv', query: 'Motherland', year: 2017, originCountry: 'GB' },
  { slug: 'cold-feet', prompt: SHOW, correct: 'Cold Feet', incorrect: ['Men Behaving Badly', 'This Life', 'Coupling'], difficulty: 'medium', kind: 'tv', query: 'Cold Feet', year: 1998, originCountry: 'GB' },
  { slug: 'the-mighty-boosh', prompt: SHOW, correct: 'The Mighty Boosh', incorrect: ['The League of Gentlemen', 'Toast of London', 'Mighty Morphin Power Rangers'], difficulty: 'hard', kind: 'tv', query: 'The Mighty Boosh', year: 2004 },
  { slug: 'spooks', prompt: SHOW, correct: 'Spooks', incorrect: ['The Night Manager', 'Bodyguard', 'Slow Horses'], difficulty: 'medium', kind: 'tv', query: 'Spooks', year: 2002 },
  { slug: 'life-on-mars-tv', prompt: SHOW, correct: 'Life on Mars', incorrect: ['Ashes to Ashes', 'Line of Duty', 'The Sweeney'], difficulty: 'medium', kind: 'tv', query: 'Life on Mars', year: 2006 },
  { slug: 'waterloo-road', prompt: SHOW, correct: 'Waterloo Road', incorrect: ['Grange Hill', 'Hollyoaks', 'Ackley Bridge'], difficulty: 'medium', kind: 'tv', query: 'Waterloo Road', year: 2006 },
  { slug: 'heartbeat', prompt: SHOW, correct: 'Heartbeat', incorrect: ['Last of the Summer Wine', 'All Creatures Great and Small', 'Emmerdale'], difficulty: 'medium', kind: 'tv', query: 'Heartbeat', year: 1992 },
  { slug: 'poldark', prompt: SHOW, correct: 'Poldark', incorrect: ['Outlander', 'Downton Abbey', 'Victoria'], difficulty: 'medium', kind: 'tv', query: 'Poldark', year: 2015 },
  { slug: 'outlander', prompt: SHOW, correct: 'Outlander', incorrect: ['Poldark', 'The Last Kingdom', 'Bridgerton'], difficulty: 'medium', kind: 'tv', query: 'Outlander', year: 2014 },
  { slug: 'shetland', prompt: SHOW, correct: 'Shetland', incorrect: ['Vera', 'Broadchurch', 'Hinterland'], difficulty: 'medium', kind: 'tv', query: 'Shetland', year: 2013 },
  { slug: 'silent-witness', prompt: SHOW, correct: 'Silent Witness', incorrect: ['Waking the Dead', 'Luther', 'Vera'], difficulty: 'medium', kind: 'tv', query: 'Silent Witness', year: 1996 },
  { slug: 'a-touch-of-frost', prompt: SHOW, correct: 'A Touch of Frost', incorrect: ['Midsomer Murders', 'Vera', 'Inspector Morse'], difficulty: 'medium', kind: 'tv', query: 'A Touch of Frost', year: 1992 },
  { slug: 'lewis', prompt: SHOW, correct: 'Lewis', incorrect: ['Endeavour', 'Inspector Morse', 'Midsomer Murders'], difficulty: 'medium', kind: 'tv', query: 'Lewis', year: 2007, originCountry: 'GB' },
  { slug: 'misfits', prompt: SHOW, correct: 'Misfits', incorrect: ['Skins', 'Being Human', 'The Inbetweeners'], difficulty: 'medium', kind: 'tv', query: 'Misfits', year: 2009 },
  { slug: 'fresh-meat', prompt: SHOW, correct: 'Fresh Meat', incorrect: ['The Inbetweeners', 'Skins', 'Peep Show'], difficulty: 'medium', kind: 'tv', query: 'Fresh Meat', year: 2011 },
  { slug: 'im-a-celebrity-get-me-out-of-here', prompt: SHOW, correct: 'I’m a Celebrity...Get Me Out of Here!', incorrect: ['Love Island', 'Big Brother', 'The Jump'], difficulty: 'easy', kind: 'tv', query: 'I\'m a Celebrity...Get Me Out of Here!', year: 2002 },
  { slug: 'the-x-factor', prompt: SHOW, correct: 'The X Factor', incorrect: ['Britain’s Got Talent', 'Pop Idol', 'The Voice UK'], difficulty: 'easy', kind: 'tv', query: 'The X Factor', year: 2004 },
  { slug: 'britains-got-talent', prompt: SHOW, correct: 'Britain’s Got Talent', incorrect: ['The X Factor', 'The Voice UK', 'America’s Got Talent'], difficulty: 'easy', kind: 'tv', query: 'Britain\'s Got Talent', year: 2007 },
  { slug: 'the-chase', prompt: SHOW, correct: 'The Chase', incorrect: ['Pointless', 'Eggheads', 'Tipping Point'], difficulty: 'easy', kind: 'tv', query: 'The Chase', year: 2009 },
  { slug: 'pointless', prompt: SHOW, correct: 'Pointless', incorrect: ['The Chase', 'Eggheads', 'Only Connect'], difficulty: 'medium', kind: 'tv', query: 'Pointless', year: 2009 },
  { slug: 'have-i-got-news-for-you', prompt: SHOW, correct: 'Have I Got News for You', incorrect: ['QI', 'Mock the Week', 'Would I Lie to You?'], difficulty: 'medium', kind: 'tv', query: 'Have I Got News for You', year: 1990 },
  { slug: 'the-grand-tour', prompt: SHOW, correct: 'The Grand Tour', incorrect: ['Top Gear', 'Clarkson’s Farm', 'Fifth Gear'], difficulty: 'medium', kind: 'tv', query: 'The Grand Tour', year: 2016 },
  { slug: 'big-brother', prompt: SHOW, correct: 'Big Brother', incorrect: ['Love Island', 'I’m a Celebrity...Get Me Out of Here!', 'The Traitors'], difficulty: 'medium', kind: 'tv', query: 'Big Brother', year: 2000, originCountry: 'GB' },
  { slug: 'made-in-chelsea', prompt: SHOW, correct: 'Made in Chelsea', incorrect: ['The Only Way Is Essex', 'Geordie Shore', 'Love Island'], difficulty: 'medium', kind: 'tv', query: 'Made in Chelsea', year: 2011 },
  { slug: 'the-only-way-is-essex', prompt: SHOW, correct: 'The Only Way Is Essex', incorrect: ['Made in Chelsea', 'Geordie Shore', 'Love Island'], difficulty: 'medium', kind: 'tv', query: 'The Only Way Is Essex', year: 2010 },
  { slug: 'sas-who-dares-wins', prompt: SHOW, correct: 'SAS: Who Dares Wins', incorrect: ['The Traitors', 'Bear Grylls: The Island', 'Gladiators'], difficulty: 'medium', kind: 'tv', query: 'SAS: Who Dares Wins', year: 2015 },
  { slug: 'clarksons-farm', prompt: SHOW, correct: 'Clarkson’s Farm', incorrect: ['The Grand Tour', 'This Farming Life', 'Top Gear'], difficulty: 'easy', kind: 'tv', query: 'Clarkson’s Farm', year: 2021 },
  { slug: 'grand-designs', prompt: SHOW, correct: 'Grand Designs', incorrect: ['Homes Under the Hammer', 'A Place in the Sun', 'George Clarke’s Amazing Spaces'], difficulty: 'medium', kind: 'tv', query: 'Grand Designs', year: 1999 },
  { slug: 'er', prompt: SHOW, correct: 'ER', incorrect: ['Grey’s Anatomy', 'Casualty', 'House'], difficulty: 'medium', kind: 'tv', query: 'ER', year: 1994 },
  { slug: 'scrubs', prompt: SHOW, correct: 'Scrubs', incorrect: ['Grey’s Anatomy', 'House', 'ER'], difficulty: 'medium', kind: 'tv', query: 'Scrubs', year: 2001 },
  { slug: 'house', prompt: SHOW, correct: 'House', incorrect: ['Grey’s Anatomy', 'Scrubs', 'ER'], difficulty: 'medium', kind: 'tv', query: 'House', year: 2004 },
  { slug: 'prison-break', prompt: SHOW, correct: 'Prison Break', incorrect: ['24', 'Lost', 'Breaking Bad'], difficulty: 'medium', kind: 'tv', query: 'Prison Break', year: 2005 },
  { slug: 'the-o-c', prompt: SHOW, correct: 'The O.C.', incorrect: ['Gossip Girl', 'One Tree Hill', 'Dawson’s Creek'], difficulty: 'medium', kind: 'tv', query: 'The O.C.', year: 2003 },
  { slug: 'gilmore-girls', prompt: SHOW, correct: 'Gilmore Girls', incorrect: ['Gossip Girl', 'Dawson’s Creek', 'The O.C.'], difficulty: 'medium', kind: 'tv', query: 'Gilmore Girls', year: 2000 },
  { slug: 'buffy-the-vampire-slayer', prompt: SHOW, correct: 'Buffy the Vampire Slayer', incorrect: ['Charmed', 'The Vampire Diaries', 'Angel'], difficulty: 'medium', kind: 'tv', query: 'Buffy the Vampire Slayer', year: 1997 },
  { slug: 'glee', prompt: SHOW, correct: 'Glee', incorrect: ['High School Musical', 'Pitch Perfect', 'Gossip Girl'], difficulty: 'medium', kind: 'tv', query: 'Glee', year: 2009 },
  { slug: 'parks-and-recreation', prompt: SHOW, correct: 'Parks and Recreation', incorrect: ['Brooklyn Nine-Nine', 'Community', 'Modern Family'], difficulty: 'medium', kind: 'tv', query: 'Parks and Recreation', year: 2009 },
  { slug: 'malcolm-in-the-middle', prompt: SHOW, correct: 'Malcolm in the Middle', incorrect: ['The Simpsons', 'Everybody Hates Chris', 'Outnumbered'], difficulty: 'medium', kind: 'tv', query: 'Malcolm in the Middle', year: 2000 },
  { slug: 'that-70s-show', prompt: SHOW, correct: 'That ’70s Show', incorrect: ['Friends', 'Happy Days', 'The Wonder Years'], difficulty: 'medium', kind: 'tv', query: 'That \'70s Show', year: 1998 },
  { slug: 'will-and-grace', prompt: SHOW, correct: 'Will & Grace', incorrect: ['Friends', 'Frasier', 'Sex and the City'], difficulty: 'medium', kind: 'tv', query: 'Will & Grace', year: 1998 },
  { slug: 'ozark', prompt: SHOW, correct: 'Ozark', incorrect: ['Breaking Bad', 'Better Call Saul', 'Narcos'], difficulty: 'medium', kind: 'tv', query: 'Ozark', year: 2017 },
  { slug: 'narcos', prompt: SHOW, correct: 'Narcos', incorrect: ['Ozark', 'Money Heist', 'Breaking Bad'], difficulty: 'medium', kind: 'tv', query: 'Narcos', year: 2015 },
  { slug: 'orange-is-the-new-black', prompt: SHOW, correct: 'Orange Is the New Black', incorrect: ['Prison Break', 'Wentworth', 'Orphan Black'], difficulty: 'medium', kind: 'tv', query: 'Orange Is the New Black', year: 2013 },
  { slug: 'house-of-cards', prompt: SHOW, correct: 'House of Cards', incorrect: ['The West Wing', 'Succession', 'Veep'], difficulty: 'medium', kind: 'tv', query: 'House of Cards', year: 2013 },
  { slug: 'you', prompt: SHOW, correct: 'You', incorrect: ['Dexter', 'Killing Eve', 'Gossip Girl'], difficulty: 'medium', kind: 'tv', query: 'You', year: 2018 },
  { slug: 'emily-in-paris', prompt: SHOW, correct: 'Emily in Paris', incorrect: ['Gossip Girl', 'Sex and the City', 'The Devil Wears Prada'], difficulty: 'medium', kind: 'tv', query: 'Emily in Paris', year: 2020 },
  { slug: 'cobra-kai', prompt: SHOW, correct: 'Cobra Kai', incorrect: ['Stranger Things', 'Outer Banks', 'Glow'], difficulty: 'medium', kind: 'tv', query: 'Cobra Kai', year: 2018 },
  { slug: 'the-gentlemen', prompt: SHOW, correct: 'The Gentlemen', incorrect: ['Peaky Blinders', 'Snatch', 'Gangs of London'], difficulty: 'medium', kind: 'tv', query: 'The Gentlemen', year: 2024 },
  { slug: 'loki', prompt: SHOW, correct: 'Loki', incorrect: ['WandaVision', 'The Mandalorian', 'Doctor Who'], difficulty: 'medium', kind: 'tv', query: 'Loki', year: 2021 },
  { slug: 'wandavision', prompt: SHOW, correct: 'WandaVision', incorrect: ['Loki', 'The Umbrella Academy', 'Agatha All Along'], difficulty: 'medium', kind: 'tv', query: 'WandaVision', year: 2021 },
  { slug: 'yellowstone', prompt: SHOW, correct: 'Yellowstone', incorrect: ['1883', 'Succession', 'Longmire'], difficulty: 'medium', kind: 'tv', query: 'Yellowstone', year: 2018 },
  { slug: 'better-call-saul', prompt: SHOW, correct: 'Better Call Saul', incorrect: ['Breaking Bad', 'Ozark', 'Suits'], difficulty: 'medium', kind: 'tv', query: 'Better Call Saul', year: 2015 },
  { slug: 'bob-the-builder', prompt: SHOW, correct: 'Bob the Builder', incorrect: ['Fireman Sam', 'Postman Pat', 'Thomas & Friends'], difficulty: 'easy', kind: 'tv', query: 'Bob the Builder', year: 1999 },
  { slug: 'tweenies', prompt: SHOW, correct: 'Tweenies', incorrect: ['Teletubbies', 'Balamory', 'The Fimbles'], difficulty: 'medium', kind: 'tv', query: 'Tweenies', year: 1999 },
  { slug: 'balamory', prompt: SHOW, correct: 'Balamory', incorrect: ['Tweenies', 'Teletubbies', 'Me Too!'], difficulty: 'medium', kind: 'tv', query: 'Balamory', year: 2002 },
  { slug: 'pokemon', prompt: SHOW, correct: 'Pokémon', incorrect: ['Digimon', 'Yu-Gi-Oh!', 'Dragon Ball Z'], difficulty: 'easy', kind: 'tv', query: 'Pokémon', year: 1997 },
  { slug: 'art-attack', prompt: SHOW, correct: 'Art Attack', incorrect: ['Blue Peter', 'SMart', 'Hey Duggee'], difficulty: 'medium', kind: 'tv', query: 'Art Attack', year: 1990 },
  { slug: 'the-story-of-tracy-beaker', prompt: SHOW, correct: 'The Story of Tracy Beaker', incorrect: ['Grange Hill', 'Byker Grove', 'Waterloo Road'], difficulty: 'medium', kind: 'tv', query: 'The Story of Tracy Beaker', year: 2002 },
];
