import type { Difficulty } from '../src/questions/types';

export interface SleeveSpec {
  slug: string;
  prompt: string;
  correct: string;
  incorrect: string[];
  difficulty: Difficulty;
  artist: string;
  term: string;
  /** When search is drowned by tributes, lookup this GB collection id. */
  collectionId?: number;
}

const COVER = 'Which album is this?';

export const SLEEVE_SPECS: SleeveSpec[] = [
  { slug: 'abbey-road', prompt: COVER, correct: 'Abbey Road', incorrect: ['Let It Be', 'Sgt. Pepper’s Lonely Hearts Club Band', 'Revolver'], difficulty: 'easy', artist: 'The Beatles', term: 'abbey road beatles' },
  { slug: 'dark-side', prompt: COVER, correct: 'The Dark Side of the Moon', incorrect: ['The Wall', 'Wish You Were Here', 'Animals'], difficulty: 'easy', artist: 'Pink Floyd', term: 'dark side of the moon pink floyd', collectionId: 1065973699 },
  { slug: 'nevermind', prompt: COVER, correct: 'Nevermind', incorrect: ['In Utero', 'Ten', 'Siamese Dream'], difficulty: 'easy', artist: 'Nirvana', term: 'Nevermind Nirvana', collectionId: 1440783617 },
  { slug: 'sgt-pepper', prompt: COVER, correct: 'Sgt. Pepper’s Lonely Hearts Club Band', incorrect: ['Magical Mystery Tour', 'Abbey Road', 'Their Satanic Majesties Request'], difficulty: 'easy', artist: 'The Beatles', term: 'sgt pepper beatles' },
  { slug: 'ziggy', prompt: COVER, correct: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', incorrect: ['Aladdin Sane', 'Hunky Dory', 'Diamond Dogs'], difficulty: 'medium', artist: 'David Bowie', term: 'ziggy stardust bowie' },
  { slug: 'aladdin-sane', prompt: COVER, correct: 'Aladdin Sane', incorrect: ['Ziggy Stardust', 'Heroes', 'Low'], difficulty: 'medium', artist: 'David Bowie', term: 'aladdin sane bowie' },
  { slug: 'london-calling', prompt: COVER, correct: 'London Calling', incorrect: ['The Clash', 'Combat Rock', 'Give ’Em Enough Rope'], difficulty: 'easy', artist: 'The Clash', term: 'london calling clash' },
  { slug: 'queen-is-dead', prompt: COVER, correct: 'The Queen Is Dead', incorrect: ['Meat Is Murder', 'Strangeways, Here We Come', 'The Smiths'], difficulty: 'medium', artist: 'The Smiths', term: 'the queen is dead smiths' },
  { slug: 'definitely-maybe', prompt: COVER, correct: 'Definitely Maybe', incorrect: ['(What’s the Story) Morning Glory?', 'Be Here Now', 'Parklife'], difficulty: 'easy', artist: 'Oasis', term: 'definitely maybe oasis' },
  { slug: 'morning-glory', prompt: COVER, correct: '(What’s the Story) Morning Glory?', incorrect: ['Definitely Maybe', 'The Bends', 'Parklife'], difficulty: 'easy', artist: 'Oasis', term: 'morning glory oasis' },
  { slug: 'ok-computer', prompt: COVER, correct: 'OK Computer', incorrect: ['The Bends', 'Kid A', 'In Rainbows'], difficulty: 'medium', artist: 'Radiohead', term: 'ok computer radiohead' },
  { slug: 'the-bends', prompt: COVER, correct: 'The Bends', incorrect: ['OK Computer', 'Pablo Honey', 'The Queen Is Dead'], difficulty: 'hard', artist: 'Radiohead', term: 'the bends radiohead' },
  { slug: 'stone-roses', prompt: COVER, correct: 'The Stone Roses', incorrect: ['Second Coming', 'Pills ’n’ Thrills and Bellyaches', 'Screamadelica'], difficulty: 'medium', artist: 'The Stone Roses', term: 'the stone roses album' },
  { slug: 'different-class', prompt: COVER, correct: 'Different Class', incorrect: ['His ’n’ Hers', 'This Is Hardcore', 'Parklife'], difficulty: 'medium', artist: 'Pulp', term: 'Different Class Pulp', collectionId: 1440923838 },
  { slug: 'parklife-album', prompt: COVER, correct: 'Parklife', incorrect: ['The Great Escape', 'Modern Life Is Rubbish', 'Definitely Maybe'], difficulty: 'medium', artist: 'Blur', term: 'parklife blur album' },
  { slug: 'am-album', prompt: COVER, correct: 'AM', incorrect: ['Whatever People Say I Am, That’s What I’m Not', 'Favourite Worst Nightmare', 'Tranquility Base Hotel & Casino'], difficulty: 'medium', artist: 'Arctic Monkeys', term: 'am arctic monkeys', collectionId: 663097964 },
  { slug: 'whatever-people-say', prompt: COVER, correct: 'Whatever People Say I Am, That’s What I’m Not', incorrect: ['AM', 'Favourite Worst Nightmare', 'Is This It'], difficulty: 'medium', artist: 'Arctic Monkeys', term: "Whatever People Say I Am That's What I'm Not", collectionId: 111153953 },
  { slug: 'rumours', prompt: COVER, correct: 'Rumours', incorrect: ['Tusk', 'Fleetwood Mac', 'Hotel California'], difficulty: 'easy', artist: 'Fleetwood Mac', term: 'rumours fleetwood mac' },
  { slug: 'thriller-album', prompt: COVER, correct: 'Thriller', incorrect: ['Bad', 'Off the Wall', 'Purple Rain'], difficulty: 'easy', artist: 'Michael Jackson', term: 'thriller michael jackson' },
  { slug: 'back-in-black-album', prompt: COVER, correct: 'Back in Black', incorrect: ['Highway to Hell', 'The Razors Edge', 'Appetite for Destruction'], difficulty: 'easy', artist: 'AC/DC', term: 'back in black acdc' },
  { slug: 'led-zeppelin-iv', prompt: COVER, correct: 'Led Zeppelin IV', incorrect: ['Led Zeppelin II', 'Houses of the Holy', 'Physical Graffiti'], difficulty: 'easy', artist: 'Led Zeppelin', term: 'led zeppelin iv' },
  { slug: 'the-wall', prompt: COVER, correct: 'The Wall', incorrect: ['The Dark Side of the Moon', 'Animals', 'Wish You Were Here'], difficulty: 'easy', artist: 'Pink Floyd', term: 'The Wall Pink Floyd', collectionId: 1065975633 },
  { slug: 'unknown-pleasures', prompt: COVER, correct: 'Unknown Pleasures', incorrect: ['Closer', 'Substance', 'The Queen Is Dead'], difficulty: 'medium', artist: 'Joy Division', term: 'unknown pleasures joy division' },
  { slug: 'velvet-underground-nico', prompt: COVER, correct: 'The Velvet Underground & Nico', incorrect: ['White Light/White Heat', 'Loaded', 'Transformer'], difficulty: 'medium', artist: 'The Velvet Underground', term: 'velvet underground nico' },
  { slug: 'sticky-fingers', prompt: COVER, correct: 'Sticky Fingers', incorrect: ['Exile on Main St.', 'Let It Bleed', 'Some Girls'], difficulty: 'medium', artist: 'The Rolling Stones', term: 'sticky fingers rolling stones' },
  { slug: 'appetite', prompt: COVER, correct: 'Appetite for Destruction', incorrect: ['Use Your Illusion I', 'Back in Black', 'Nevermind'], difficulty: 'medium', artist: "Guns N' Roses", term: 'Appetite for Destruction Guns N Roses', collectionId: 1377813284 },
  { slug: 'joshua-tree', prompt: COVER, correct: 'The Joshua Tree', incorrect: ['Achtung Baby', 'War', 'The Unforgettable Fire'], difficulty: 'easy', artist: 'U2', term: 'the joshua tree u2' },
  { slug: 'automatic-for-the-people', prompt: COVER, correct: 'Automatic for the People', incorrect: ['Out of Time', 'Monster', 'Document'], difficulty: 'medium', artist: 'R.E.M.', term: 'automatic for the people rem', collectionId: 1440949853 },
  { slug: 'is-this-it', prompt: COVER, correct: 'Is This It', incorrect: ['Room on Fire', 'Whatever People Say I Am, That’s What I’m Not', 'Turn On the Bright Lights'], difficulty: 'medium', artist: 'The Strokes', term: 'Is This It The Strokes', collectionId: 269080434 },
  { slug: 'discovery', prompt: COVER, correct: 'Discovery', incorrect: ['Homework', 'Random Access Memories', 'Human After All'], difficulty: 'medium', artist: 'Daft Punk', term: 'discovery daft punk' },
  { slug: '21-adele', prompt: COVER, correct: '21', incorrect: ['19', '25', '30'], difficulty: 'easy', artist: 'Adele', term: '21 adele' },
  { slug: '25-adele', prompt: COVER, correct: '25', incorrect: ['21', '19', '30'], difficulty: 'medium', artist: 'Adele', term: '25 adele' },
  { slug: 'x-ed', prompt: COVER, correct: 'x', incorrect: ['+', '÷', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'x ed sheeran' },
  { slug: 'back-to-black', prompt: COVER, correct: 'Back to Black', incorrect: ['Frank', 'Lioness: Hidden Treasures', '19'], difficulty: 'easy', artist: 'Amy Winehouse', term: 'back to black amy winehouse' },
  { slug: 'dummy', prompt: COVER, correct: 'Dummy', incorrect: ['Mezzanine', 'Third', 'Homogenic'], difficulty: 'hard', artist: 'Portishead', term: 'dummy portishead' },
  { slug: 'homogenic', prompt: COVER, correct: 'Homogenic', incorrect: ['Debut', 'Post', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'homogenic bjork' },
  { slug: 'kid-a', prompt: COVER, correct: 'Kid A', incorrect: ['OK Computer', 'Amnesiac', 'Hail to the Thief'], difficulty: 'hard', artist: 'Radiohead', term: 'kid a radiohead' },
  { slug: 'in-rainbows', prompt: COVER, correct: 'In Rainbows', incorrect: ['OK Computer', 'Kid A', 'A Moon Shaped Pool'], difficulty: 'hard', artist: 'Radiohead', term: 'in rainbows radiohead' },
  { slug: 'hounds-of-love', prompt: COVER, correct: 'Hounds of Love', incorrect: ['The Kick Inside', 'The Dreaming', 'Aerial'], difficulty: 'hard', artist: 'Kate Bush', term: 'hounds of love kate bush' },
  { slug: 'parallel-lines', prompt: COVER, correct: 'Parallel Lines', incorrect: ['Eat to the Beat', 'Autoamerican', 'Plastic Letters'], difficulty: 'medium', artist: 'Blondie', term: 'parallel lines blondie' },
  { slug: 'born-to-run-album', prompt: COVER, correct: 'Born to Run', incorrect: ['Darkness on the Edge of Town', 'Born in the U.S.A.', 'The River'], difficulty: 'medium', artist: 'Bruce Springsteen', term: 'born to run springsteen' },
  { slug: 'hotel-california-album', prompt: COVER, correct: 'Hotel California', incorrect: ['The Long Run', 'One of These Nights', 'Rumours'], difficulty: 'medium', artist: 'Eagles', term: 'hotel california eagles album' },
  { slug: 'illmatic', prompt: COVER, correct: 'Illmatic', incorrect: ['Ready to Die', 'The Chronic', 'Enter the Wu-Tang (36 Chambers)'], difficulty: 'hard', artist: 'Nas', term: 'illmatic nas' },
  { slug: 'to-pimp-a-butterfly', prompt: COVER, correct: 'To Pimp a Butterfly', incorrect: ['good kid, m.A.A.d city', 'DAMN.', 'Channel Orange'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'to pimp a butterfly kendrick' },
  { slug: 'channel-orange', prompt: COVER, correct: 'Channel Orange', incorrect: ['Blonde', 'Nostalgia, Ultra', 'To Pimp a Butterfly'], difficulty: 'hard', artist: 'Frank Ocean', term: 'channel orange frank ocean', collectionId: 1440765580 },
  { slug: 'the-fame', prompt: COVER, correct: 'The Fame', incorrect: ['Born This Way', 'The Fame Monster', 'Artpop'], difficulty: 'medium', artist: 'Lady Gaga', term: 'the fame lady gaga', collectionId: 1440818588 },
  { slug: '1989', prompt: COVER, correct: '1989', incorrect: ['Red', 'Lover', 'Midnights'], difficulty: 'easy', artist: 'Taylor Swift', term: '1989 taylor swift' },
  { slug: 'american-idiot', prompt: COVER, correct: 'American Idiot', incorrect: ['Dookie', 'Nimrod', 'Warning'], difficulty: 'medium', artist: 'Green Day', term: 'American Idiot Green Day', collectionId: 1161539183 },
  { slug: 'californication', prompt: COVER, correct: 'Californication', incorrect: ['Blood Sugar Sex Magik', 'Stadium Arcadium', 'By the Way'], difficulty: 'medium', artist: 'Red Hot Chili Peppers', term: 'californication red hot chili peppers' },
  { slug: 'screamadelica', prompt: COVER, correct: 'Screamadelica', incorrect: ['The Stone Roses', 'Pills ’n’ Thrills and Bellyaches', 'Lazer Guided Melodies'], difficulty: 'hard', artist: 'Primal Scream', term: 'screamadelica primal scream' },
  { slug: 'urban-hymns', prompt: COVER, correct: 'Urban Hymns', incorrect: ['A Northern Soul', 'A Storm in Heaven', 'The Bends'], difficulty: 'hard', artist: 'The Verve', term: 'urban hymns verve' },
  { slug: 'rush-of-blood', prompt: COVER, correct: 'A Rush of Blood to the Head', incorrect: ['Parachutes', 'X&Y', 'Viva la Vida or Death and All His Friends'], difficulty: 'medium', artist: 'Coldplay', term: 'a rush of blood to the head coldplay' },

  /*
    Added 21 September 2026, to refill the pack after the cover-text gate.

    Thirty-three of the original fifty-two sleeves print their own title, so
    `npm run sleeve-audit` refuses them and the pack fell to eighteen — below
    the forty-five a round wants. These are candidates, not keepers: none of
    them was chosen for having a wordless cover, because nobody here can see
    the artwork iTunes GB will return. The audit decides, and what it refuses
    stays in this list as a record of what was tried.
  */
  { slug: 'wish-you-were-here-album', prompt: COVER, correct: 'Wish You Were Here', incorrect: ['The Dark Side of the Moon', 'Animals', 'The Final Cut'], difficulty: 'medium', artist: 'Pink Floyd', term: 'wish you were here pink floyd' },
  { slug: 'animals-pf', prompt: COVER, correct: 'Animals', incorrect: ['The Wall', 'Meddle', 'Wish You Were Here'], difficulty: 'hard', artist: 'Pink Floyd', term: 'pink floyd animals' },
  { slug: 'let-it-be', prompt: COVER, correct: 'Let It Be', incorrect: ['Abbey Road', 'Help!', 'Rubber Soul'], difficulty: 'medium', artist: 'The Beatles', term: 'let it be beatles' },
  { slug: 'revolver', prompt: COVER, correct: 'Revolver', incorrect: ['Rubber Soul', 'Help!', 'A Hard Day’s Night'], difficulty: 'medium', artist: 'The Beatles', term: 'revolver beatles' },
  { slug: 'white-album', prompt: COVER, correct: 'The Beatles', incorrect: ['Abbey Road', 'Let It Be', 'Magical Mystery Tour'], difficulty: 'hard', artist: 'The Beatles', term: 'the beatles white album' },
  { slug: 'houses-of-the-holy', prompt: COVER, correct: 'Houses of the Holy', incorrect: ['Led Zeppelin IV', 'Physical Graffiti', 'Presence'], difficulty: 'medium', artist: 'Led Zeppelin', term: 'houses of the holy led zeppelin' },
  { slug: 'physical-graffiti', prompt: COVER, correct: 'Physical Graffiti', incorrect: ['Led Zeppelin II', 'Houses of the Holy', 'In Through the Out Door'], difficulty: 'hard', artist: 'Led Zeppelin', term: 'physical graffiti led zeppelin' },
  { slug: 'led-zeppelin-ii', prompt: COVER, correct: 'Led Zeppelin II', incorrect: ['Led Zeppelin IV', 'Presence', 'Coda'], difficulty: 'hard', artist: 'Led Zeppelin', term: 'led zeppelin ii' },
  { slug: 'in-utero', prompt: COVER, correct: 'In Utero', incorrect: ['Nevermind', 'Bleach', 'MTV Unplugged in New York'], difficulty: 'medium', artist: 'Nirvana', term: 'in utero nirvana' },
  { slug: 'closer-jd', prompt: COVER, correct: 'Closer', incorrect: ['Unknown Pleasures', 'Still', 'Substance'], difficulty: 'hard', artist: 'Joy Division', term: 'closer joy division' },
  { slug: 'power-corruption-lies', prompt: COVER, correct: 'Power, Corruption & Lies', incorrect: ['Technique', 'Low-Life', 'Brotherhood'], difficulty: 'hard', artist: 'New Order', term: 'power corruption and lies new order' },
  { slug: 'technique', prompt: COVER, correct: 'Technique', incorrect: ['Low-Life', 'Republic', 'Brotherhood'], difficulty: 'hard', artist: 'New Order', term: 'technique new order' },
  { slug: 'meat-is-murder', prompt: COVER, correct: 'Meat Is Murder', incorrect: ['The Queen Is Dead', 'Strangeways, Here We Come', 'The Smiths'], difficulty: 'hard', artist: 'The Smiths', term: 'meat is murder smiths' },
  { slug: 'strangeways', prompt: COVER, correct: 'Strangeways, Here We Come', incorrect: ['The Queen Is Dead', 'Meat Is Murder', 'The Smiths'], difficulty: 'hard', artist: 'The Smiths', term: 'strangeways here we come smiths' },
  { slug: 'post-bjork', prompt: COVER, correct: 'Post', incorrect: ['Debut', 'Homogenic', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'post bjork' },
  { slug: 'debut-bjork', prompt: COVER, correct: 'Debut', incorrect: ['Post', 'Homogenic', 'Vespertine'], difficulty: 'hard', artist: 'Björk', term: 'debut bjork' },
  { slug: 'vespertine', prompt: COVER, correct: 'Vespertine', incorrect: ['Debut', 'Post', 'Homogenic'], difficulty: 'hard', artist: 'Björk', term: 'vespertine bjork' },
  { slug: 'amnesiac', prompt: COVER, correct: 'Amnesiac', incorrect: ['Kid A', 'Hail to the Thief', 'In Rainbows'], difficulty: 'hard', artist: 'Radiohead', term: 'amnesiac radiohead' },
  { slug: 'moon-shaped-pool', prompt: COVER, correct: 'A Moon Shaped Pool', incorrect: ['In Rainbows', 'Amnesiac', 'Hail to the Thief'], difficulty: 'hard', artist: 'Radiohead', term: 'a moon shaped pool radiohead' },
  { slug: 'parachutes', prompt: COVER, correct: 'Parachutes', incorrect: ['A Rush of Blood to the Head', 'X&Y', 'Ghost Stories'], difficulty: 'medium', artist: 'Coldplay', term: 'parachutes coldplay' },
  { slug: 'x-and-y', prompt: COVER, correct: 'X&Y', incorrect: ['Parachutes', 'A Rush of Blood to the Head', 'Mylo Xyloto'], difficulty: 'medium', artist: 'Coldplay', term: 'x&y coldplay' },
  { slug: 'viva-la-vida-album', prompt: COVER, correct: 'Viva la Vida or Death and All His Friends', incorrect: ['Parachutes', 'X&Y', 'Ghost Stories'], difficulty: 'medium', artist: 'Coldplay', term: 'viva la vida coldplay' },
  { slug: 'homework', prompt: COVER, correct: 'Homework', incorrect: ['Discovery', 'Human After All', 'Random Access Memories'], difficulty: 'hard', artist: 'Daft Punk', term: 'homework daft punk' },
  { slug: 'random-access', prompt: COVER, correct: 'Random Access Memories', incorrect: ['Discovery', 'Homework', 'Human After All'], difficulty: 'medium', artist: 'Daft Punk', term: 'random access memories daft punk' },
  { slug: 'mezzanine', prompt: COVER, correct: 'Mezzanine', incorrect: ['Blue Lines', 'Protection', '100th Window'], difficulty: 'hard', artist: 'Massive Attack', term: 'mezzanine massive attack' },
  { slug: 'blue-lines', prompt: COVER, correct: 'Blue Lines', incorrect: ['Mezzanine', 'Protection', 'Heligoland'], difficulty: 'hard', artist: 'Massive Attack', term: 'blue lines massive attack' },
  { slug: 'fat-of-the-land', prompt: COVER, correct: 'The Fat of the Land', incorrect: ['Music for the Jilted Generation', 'Experience', 'Invaders Must Die'], difficulty: 'medium', artist: 'The Prodigy', term: 'the fat of the land prodigy' },
  { slug: 'good-kid', prompt: COVER, correct: 'good kid, m.A.A.d city', incorrect: ['To Pimp a Butterfly', 'DAMN.', 'Section.80'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'good kid maad city kendrick lamar' },
  { slug: 'damn-kendrick', prompt: COVER, correct: 'DAMN.', incorrect: ['good kid, m.A.A.d city', 'To Pimp a Butterfly', 'Section.80'], difficulty: 'hard', artist: 'Kendrick Lamar', term: 'damn kendrick lamar' },
  { slug: 'blonde-frank', prompt: COVER, correct: 'Blonde', incorrect: ['Channel Orange', 'Nostalgia, Ultra', 'Endless'], difficulty: 'hard', artist: 'Frank Ocean', term: 'frank ocean blonde album' },
  { slug: 'war-u2', prompt: COVER, correct: 'War', incorrect: ['Boy', 'October', 'The Unforgettable Fire'], difficulty: 'medium', artist: 'U2', term: 'war u2' },
  { slug: 'achtung-baby', prompt: COVER, correct: 'Achtung Baby', incorrect: ['The Joshua Tree', 'Zooropa', 'Pop'], difficulty: 'medium', artist: 'U2', term: 'achtung baby u2' },
  { slug: 'unforgettable-fire', prompt: COVER, correct: 'The Unforgettable Fire', incorrect: ['War', 'Boy', 'The Joshua Tree'], difficulty: 'hard', artist: 'U2', term: 'the unforgettable fire u2' },
  { slug: 'hunky-dory', prompt: COVER, correct: 'Hunky Dory', incorrect: ['Low', 'Heroes', 'Diamond Dogs'], difficulty: 'hard', artist: 'David Bowie', term: 'hunky dory bowie' },
  { slug: 'low-bowie', prompt: COVER, correct: 'Low', incorrect: ['Heroes', 'Lodger', 'Station to Station'], difficulty: 'hard', artist: 'David Bowie', term: 'low david bowie' },
  { slug: 'heroes-bowie', prompt: COVER, correct: 'Heroes', incorrect: ['Low', 'Lodger', 'Hunky Dory'], difficulty: 'hard', artist: 'David Bowie', term: 'heroes david bowie' },
  { slug: 'diamond-dogs', prompt: COVER, correct: 'Diamond Dogs', incorrect: ['Hunky Dory', 'Aladdin Sane', 'Pin Ups'], difficulty: 'hard', artist: 'David Bowie', term: 'diamond dogs bowie' },
  { slug: 'night-at-the-opera', prompt: COVER, correct: 'A Night at the Opera', incorrect: ['News of the World', 'Sheer Heart Attack', 'A Day at the Races'], difficulty: 'medium', artist: 'Queen', term: 'a night at the opera queen' },
  { slug: 'news-of-the-world', prompt: COVER, correct: 'News of the World', incorrect: ['A Night at the Opera', 'Jazz', 'The Game'], difficulty: 'medium', artist: 'Queen', term: 'news of the world queen' },
  { slug: 'whos-next', prompt: COVER, correct: 'Who’s Next', incorrect: ['Quadrophenia', 'Tommy', 'My Generation'], difficulty: 'hard', artist: 'The Who', term: 'whos next the who' },
  { slug: 'quadrophenia', prompt: COVER, correct: 'Quadrophenia', incorrect: ['Tommy', 'Who’s Next', 'My Generation'], difficulty: 'hard', artist: 'The Who', term: 'quadrophenia the who' },
  { slug: 'exile-on-main-st', prompt: COVER, correct: 'Exile on Main St.', incorrect: ['Sticky Fingers', 'Let It Bleed', 'Some Girls'], difficulty: 'hard', artist: 'The Rolling Stones', term: 'exile on main street rolling stones' },
  { slug: 'let-it-bleed', prompt: COVER, correct: 'Let It Bleed', incorrect: ['Sticky Fingers', 'Beggars Banquet', 'Aftermath'], difficulty: 'hard', artist: 'The Rolling Stones', term: 'let it bleed rolling stones' },
  { slug: 'disintegration', prompt: COVER, correct: 'Disintegration', incorrect: ['Faith', 'Pornography', 'Wish'], difficulty: 'hard', artist: 'The Cure', term: 'disintegration the cure' },
  { slug: 'violator', prompt: COVER, correct: 'Violator', incorrect: ['Music for the Masses', 'Songs of Faith and Devotion', 'Black Celebration'], difficulty: 'hard', artist: 'Depeche Mode', term: 'violator depeche mode' },
  { slug: 'remain-in-light', prompt: COVER, correct: 'Remain in Light', incorrect: ['Fear of Music', 'Speaking in Tongues', 'More Songs About Buildings and Food'], difficulty: 'hard', artist: 'Talking Heads', term: 'remain in light talking heads' },
  { slug: 'great-escape', prompt: COVER, correct: 'The Great Escape', incorrect: ['Parklife', 'Modern Life Is Rubbish', '13'], difficulty: 'hard', artist: 'Blur', term: 'the great escape blur' },
  { slug: 'modern-life', prompt: COVER, correct: 'Modern Life Is Rubbish', incorrect: ['Parklife', 'The Great Escape', 'Leisure'], difficulty: 'hard', artist: 'Blur', term: 'modern life is rubbish blur' },
  { slug: 'blur-13', prompt: COVER, correct: '13', incorrect: ['Parklife', 'The Great Escape', 'Think Tank'], difficulty: 'hard', artist: 'Blur', term: '13 blur album' },
  { slug: 'be-here-now', prompt: COVER, correct: 'Be Here Now', incorrect: ['Definitely Maybe', '(What’s the Story) Morning Glory?', 'Heathen Chemistry'], difficulty: 'medium', artist: 'Oasis', term: 'be here now oasis' },
  { slug: 'origin-of-symmetry', prompt: COVER, correct: 'Origin of Symmetry', incorrect: ['Absolution', 'Black Holes and Revelations', 'Showbiz'], difficulty: 'hard', artist: 'Muse', term: 'origin of symmetry muse' },
  { slug: 'absolution', prompt: COVER, correct: 'Absolution', incorrect: ['Origin of Symmetry', 'Black Holes and Revelations', 'The Resistance'], difficulty: 'hard', artist: 'Muse', term: 'absolution muse' },
  { slug: 'hot-fuss', prompt: COVER, correct: 'Hot Fuss', incorrect: ['Sam’s Town', 'Day & Age', 'Battle Born'], difficulty: 'medium', artist: 'The Killers', term: 'hot fuss the killers' },
  { slug: 'sams-town', prompt: COVER, correct: 'Sam’s Town', incorrect: ['Hot Fuss', 'Day & Age', 'Wonderful Wonderful'], difficulty: 'medium', artist: 'The Killers', term: 'sams town the killers' },
  { slug: 'favourite-worst-nightmare', prompt: COVER, correct: 'Favourite Worst Nightmare', incorrect: ['AM', 'Whatever People Say I Am, That’s What I’m Not', 'Humbug'], difficulty: 'medium', artist: 'Arctic Monkeys', term: 'arctic monkeys favourite worst nightmare' },
  { slug: 'employment', prompt: COVER, correct: 'Employment', incorrect: ['Yours Truly, Angry Mob', 'Off With Their Heads', 'Education, Education, Education & War'], difficulty: 'hard', artist: 'Kaiser Chiefs', term: 'employment kaiser chiefs' },
  { slug: 'seldom-seen-kid', prompt: COVER, correct: 'The Seldom Seen Kid', incorrect: ['Cast of Thousands', 'Asleep in the Back', 'Build a Rocket Boys!'], difficulty: 'hard', artist: 'Elbow', term: 'the seldom seen kid elbow' },
  { slug: 'hopes-and-fears', prompt: COVER, correct: 'Hopes and Fears', incorrect: ['Under the Iron Sea', 'Perfect Symmetry', 'Strangeland'], difficulty: 'medium', artist: 'Keane', term: 'hopes and fears keane' },
  { slug: 'final-straw', prompt: COVER, correct: 'Final Straw', incorrect: ['Eyes Open', 'A Hundred Million Suns', 'Songs for Polarbears'], difficulty: 'medium', artist: 'Snow Patrol', term: 'snow patrol final straw' },
  { slug: 'everything-must-go', prompt: COVER, correct: 'Everything Must Go', incorrect: ['The Holy Bible', 'Generation Terrorists', 'This Is My Truth Tell Me Yours'], difficulty: 'hard', artist: 'Manic Street Preachers', term: 'everything must go manic street preachers' },
  { slug: 'dog-man-star', prompt: COVER, correct: 'Dog Man Star', incorrect: ['Suede', 'Coming Up', 'Head Music'], difficulty: 'hard', artist: 'Suede', term: 'dog man star suede' },
  { slug: 'the-man-who', prompt: COVER, correct: 'The Man Who', incorrect: ['The Invisible Band', 'Good Feeling', '12 Memories'], difficulty: 'hard', artist: 'Travis', term: 'the man who travis' },
  { slug: 'goodbye-yellow-brick', prompt: COVER, correct: 'Goodbye Yellow Brick Road', incorrect: ['Madman Across the Water', 'Honky Château', 'Captain Fantastic'], difficulty: 'medium', artist: 'Elton John', term: 'goodbye yellow brick road elton john' },
  { slug: 'brothers-in-arms', prompt: COVER, correct: 'Brothers in Arms', incorrect: ['Love Over Gold', 'Making Movies', 'Communiqué'], difficulty: 'medium', artist: 'Dire Straits', term: 'brothers in arms dire straits' },
  { slug: 'so-gabriel', prompt: COVER, correct: 'So', incorrect: ['Us', 'Peter Gabriel', 'Security'], difficulty: 'hard', artist: 'Peter Gabriel', term: 'so peter gabriel' },
  { slug: 'big-chair', prompt: COVER, correct: 'Songs from the Big Chair', incorrect: ['The Hurting', 'The Seeds of Love', 'Elemental'], difficulty: 'hard', artist: 'Tears for Fears', term: 'songs from the big chair tears for fears' },
  { slug: 'all-mod-cons', prompt: COVER, correct: 'All Mod Cons', incorrect: ['Sound Affects', 'Setting Sons', 'The Gift'], difficulty: 'hard', artist: 'The Jam', term: 'all mod cons the jam' },
  { slug: 'one-step-beyond', prompt: COVER, correct: 'One Step Beyond', incorrect: ['Absolutely', '7', 'The Rise & Fall'], difficulty: 'hard', artist: 'Madness', term: 'one step beyond madness' },
  { slug: 'original-pirate', prompt: COVER, correct: 'Original Pirate Material', incorrect: ['A Grand Don’t Come for Free', 'The Hardest Way to Make an Easy Living', 'Computers and Blues'], difficulty: 'hard', artist: 'The Streets', term: 'the streets original pirate material' },
  { slug: 'boy-in-da-corner', prompt: COVER, correct: 'Boy in da Corner', incorrect: ['Showtime', 'Maths + English', 'Tongue n’ Cheek'], difficulty: 'hard', artist: 'Dizzee Rascal', term: 'boy in da corner dizzee rascal' },
  { slug: 'frank-amy', prompt: COVER, correct: 'Frank', incorrect: ['Back to Black', 'Lioness: Hidden Treasures', 'At the BBC'], difficulty: 'hard', artist: 'Amy Winehouse', term: 'frank amy winehouse' },
  { slug: 'lungs', prompt: COVER, correct: 'Lungs', incorrect: ['Ceremonials', 'How Big, How Blue, How Beautiful', 'High as Hope'], difficulty: 'medium', artist: 'Florence + The Machine', term: 'lungs florence and the machine' },
  { slug: 'plus-ed', prompt: COVER, correct: '+', incorrect: ['x', '÷', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'plus ed sheeran' },
  { slug: 'divide-ed', prompt: COVER, correct: '÷', incorrect: ['+', 'x', '='], difficulty: 'medium', artist: 'Ed Sheeran', term: 'divide ed sheeran' },
  { slug: 'after-hours', prompt: COVER, correct: 'After Hours', incorrect: ['Starboy', 'Beauty Behind the Madness', 'Dawn FM'], difficulty: 'medium', artist: 'The Weeknd', term: 'after hours the weeknd' },
  { slug: 'born-to-die', prompt: COVER, correct: 'Born to Die', incorrect: ['Ultraviolence', 'Honeymoon', 'Norman Fucking Rockwell!'], difficulty: 'medium', artist: 'Lana Del Rey', term: 'born to die lana del rey' },
  { slug: 'lemonade', prompt: COVER, correct: 'Lemonade', incorrect: ['Beyoncé', '4', 'B’Day'], difficulty: 'medium', artist: 'Beyoncé', term: 'beyonce lemonade album' },
  { slug: 'anti-rihanna', prompt: COVER, correct: 'Anti', incorrect: ['Good Girl Gone Bad', 'Loud', 'Unapologetic'], difficulty: 'medium', artist: 'Rihanna', term: 'anti rihanna' },
  { slug: 'purple-rain-album', prompt: COVER, correct: 'Purple Rain', incorrect: ['Sign o’ the Times', '1999', 'Around the World in a Day'], difficulty: 'medium', artist: 'Prince', term: 'purple rain prince' },
  { slug: 'off-the-wall', prompt: COVER, correct: 'Off the Wall', incorrect: ['Thriller', 'Bad', 'Dangerous'], difficulty: 'medium', artist: 'Michael Jackson', term: 'off the wall michael jackson' },
  { slug: 'bad-mj', prompt: COVER, correct: 'Bad', incorrect: ['Thriller', 'Off the Wall', 'Dangerous'], difficulty: 'medium', artist: 'Michael Jackson', term: 'bad michael jackson' },
  { slug: 'tusk', prompt: COVER, correct: 'Tusk', incorrect: ['Rumours', 'Fleetwood Mac', 'Mirage'], difficulty: 'hard', artist: 'Fleetwood Mac', term: 'tusk fleetwood mac' },
  { slug: 'the-long-run', prompt: COVER, correct: 'The Long Run', incorrect: ['Hotel California', 'One of These Nights', 'Desperado'], difficulty: 'hard', artist: 'Eagles', term: 'the long run eagles' },
  { slug: 'born-in-the-usa', prompt: COVER, correct: 'Born in the U.S.A.', incorrect: ['Born to Run', 'Nebraska', 'Darkness on the Edge of Town'], difficulty: 'medium', artist: 'Bruce Springsteen', term: 'born in the usa springsteen' },
  { slug: 'nebraska', prompt: COVER, correct: 'Nebraska', incorrect: ['Born to Run', 'Born in the U.S.A.', 'The River'], difficulty: 'hard', artist: 'Bruce Springsteen', term: 'nebraska springsteen' },
  { slug: 'master-of-puppets', prompt: COVER, correct: 'Master of Puppets', incorrect: ['Ride the Lightning', '…And Justice for All', 'Kill ’Em All'], difficulty: 'medium', artist: 'Metallica', term: 'metallica master of puppets' },
  { slug: 'ride-the-lightning', prompt: COVER, correct: 'Ride the Lightning', incorrect: ['Master of Puppets', 'Kill ’Em All', 'Load'], difficulty: 'hard', artist: 'Metallica', term: 'ride the lightning metallica' },
  { slug: 'highway-to-hell-album', prompt: COVER, correct: 'Highway to Hell', incorrect: ['Back in Black', 'The Razors Edge', 'Powerage'], difficulty: 'medium', artist: 'AC/DC', term: 'highway to hell acdc' },
  { slug: 'grace-buckley', prompt: COVER, correct: 'Grace', incorrect: ['Sketches for My Sweetheart the Drunk', 'Live at Sin-é', 'You and I'], difficulty: 'hard', artist: 'Jeff Buckley', term: 'grace jeff buckley' },
  { slug: 'funeral', prompt: COVER, correct: 'Funeral', incorrect: ['Neon Bible', 'The Suburbs', 'Reflektor'], difficulty: 'hard', artist: 'Arcade Fire', term: 'funeral arcade fire' },
  { slug: 'for-emma', prompt: COVER, correct: 'For Emma, Forever Ago', incorrect: ['Bon Iver', '22, A Million', 'i,i'], difficulty: 'hard', artist: 'Bon Iver', term: 'bon iver for emma forever ago' },
  { slug: 'currents', prompt: COVER, correct: 'Currents', incorrect: ['Lonerism', 'InnerSpeaker', 'The Slow Rush'], difficulty: 'medium', artist: 'Tame Impala', term: 'currents tame impala' },
  { slug: 'lonerism', prompt: COVER, correct: 'Lonerism', incorrect: ['Currents', 'InnerSpeaker', 'The Slow Rush'], difficulty: 'hard', artist: 'Tame Impala', term: 'lonerism tame impala' },
  { slug: 'demon-days', prompt: COVER, correct: 'Demon Days', incorrect: ['Gorillaz', 'Plastic Beach', 'Humanz'], difficulty: 'medium', artist: 'Gorillaz', term: 'demon days gorillaz' },
  { slug: 'dookie', prompt: COVER, correct: 'Dookie', incorrect: ['American Idiot', 'Nimrod', 'Insomniac'], difficulty: 'medium', artist: 'Green Day', term: 'green day dookie' },
  { slug: 'blood-sugar', prompt: COVER, correct: 'Blood Sugar Sex Magik', incorrect: ['Californication', 'By the Way', 'Stadium Arcadium'], difficulty: 'medium', artist: 'Red Hot Chili Peppers', term: 'red hot chili peppers blood sugar sex magik' },
  { slug: 'by-the-way', prompt: COVER, correct: 'By the Way', incorrect: ['Californication', 'Blood Sugar Sex Magik', 'One Hot Minute'], difficulty: 'hard', artist: 'Red Hot Chili Peppers', term: 'red hot chili peppers by the way' },
  { slug: 'enter-the-wu-tang', prompt: COVER, correct: 'Enter the Wu-Tang (36 Chambers)', incorrect: ['Illmatic', 'Ready to Die', 'The Chronic'], difficulty: 'hard', artist: 'Wu-Tang Clan', term: 'enter the wu tang 36 chambers' },
  { slug: 'the-chronic', prompt: COVER, correct: 'The Chronic', incorrect: ['2001', 'Illmatic', 'Ready to Die'], difficulty: 'hard', artist: 'Dr. Dre', term: 'dr dre the chronic' },
  { slug: 'ready-to-die', prompt: COVER, correct: 'Ready to Die', incorrect: ['Life After Death', 'Illmatic', 'The Chronic'], difficulty: 'hard', artist: 'The Notorious B.I.G.', term: 'ready to die notorious big' },
  { slug: 'pauls-boutique', prompt: COVER, correct: 'Paul’s Boutique', incorrect: ['Licensed to Ill', 'Check Your Head', 'Ill Communication'], difficulty: 'hard', artist: 'Beastie Boys', term: 'beastie boys pauls boutique' },
  { slug: 'third-portishead', prompt: COVER, correct: 'Third', incorrect: ['Dummy', 'Portishead', 'Roseland NYC Live'], difficulty: 'hard', artist: 'Portishead', term: 'third portishead' },
  { slug: 'selected-ambient', prompt: COVER, correct: 'Selected Ambient Works 85-92', incorrect: ['Richard D. James Album', 'Drukqs', 'Syro'], difficulty: 'hard', artist: 'Aphex Twin', term: 'selected ambient works aphex twin' },
  { slug: 'dig-your-own-hole', prompt: COVER, correct: 'Dig Your Own Hole', incorrect: ['Exit Planet Dust', 'Surrender', 'Come With Us'], difficulty: 'hard', artist: 'The Chemical Brothers', term: 'dig your own hole chemical brothers' },
  { slug: 'play-moby', prompt: COVER, correct: 'Play', incorrect: ['18', 'Everything Is Wrong', 'Animal Rights'], difficulty: 'medium', artist: 'Moby', term: 'play moby' },
  { slug: 'moon-safari', prompt: COVER, correct: 'Moon Safari', incorrect: ['Talkie Walkie', '10 000 Hz Legend', 'Premiers Symptômes'], difficulty: 'hard', artist: 'Air', term: 'moon safari air' },
];
