import type { Difficulty } from '../src/questions/types';

export interface ScreenSpec {
  slug: string;
  prompt: string;
  correct: string;
  incorrect: string[];
  difficulty: Difficulty;
  kind: 'movie' | 'tv';
  query: string;
  year: number;
  /** TMDB `origin_country`, when the title collides (The Office UK vs US). */
  originCountry?: string;
}

const FILM = 'Which film is this?';
const SHOW = 'Which TV show is this?';

/**
 * On the box. Mix of eras for a 2026 UK office — not a wall of 1960s–80s
 * “classics”. Fine Art already did that: PD-Art / Commons selected 15th–1930s
 * paintings because those stills were legal to hash, not because the room would
 * know them. Untitled TMDB backdrops (stills, then a cropped poster) must not
 * make the same call.
 */
export const SCREEN_SPECS: ScreenSpec[] = [
  // A few stills everyone has actually seen.
  { slug: 'jaws', prompt: FILM, correct: 'Jaws', incorrect: ['Jurassic Park', 'The Meg', 'Open Water'], difficulty: 'easy', kind: 'movie', query: 'Jaws', year: 1975 },
  { slug: 'star-wars', prompt: FILM, correct: 'Star Wars', incorrect: ['Star Trek', 'Dune', 'Guardians of the Galaxy'], difficulty: 'easy', kind: 'movie', query: 'Star Wars', year: 1977 },
  { slug: 'back-to-the-future', prompt: FILM, correct: 'Back to the Future', incorrect: ['Bill & Ted’s Excellent Adventure', 'Hot Tub Time Machine', 'Peggy Sue Got Married'], difficulty: 'easy', kind: 'movie', query: 'Back to the Future', year: 1985 },
  { slug: 'home-alone', prompt: FILM, correct: 'Home Alone', incorrect: ['Mrs. Doubtfire', 'Elf', 'The Santa Clause'], difficulty: 'easy', kind: 'movie', query: 'Home Alone', year: 1990 },
  { slug: 'jurassic-park', prompt: FILM, correct: 'Jurassic Park', incorrect: ['Jaws', 'King Kong', 'Godzilla'], difficulty: 'easy', kind: 'movie', query: 'Jurassic Park', year: 1993 },
  { slug: 'lion-king', prompt: FILM, correct: 'The Lion King', incorrect: ['The Jungle Book', 'Madagascar', 'Tarzan'], difficulty: 'easy', kind: 'movie', query: 'The Lion King', year: 1994 },
  { slug: 'toy-story', prompt: FILM, correct: 'Toy Story', incorrect: ['A Bug’s Life', 'Monsters, Inc.', 'Shrek'], difficulty: 'easy', kind: 'movie', query: 'Toy Story', year: 1995 },
  { slug: 'titanic', prompt: FILM, correct: 'Titanic', incorrect: ['The Notebook', 'Pearl Harbor', 'Atonement'], difficulty: 'easy', kind: 'movie', query: 'Titanic', year: 1997 },
  { slug: 'matrix', prompt: FILM, correct: 'The Matrix', incorrect: ['Inception', 'Blade Runner', 'Tron'], difficulty: 'easy', kind: 'movie', query: 'The Matrix', year: 1999 },
  { slug: 'harry-potter', prompt: FILM, correct: 'Harry Potter and the Philosopher’s Stone', incorrect: ['The Lord of the Rings: The Fellowship of the Ring', 'The Chronicles of Narnia', 'Percy Jackson & the Olympians'], difficulty: 'easy', kind: 'movie', query: 'Harry Potter and the Philosopher\'s Stone', year: 2001 },
  { slug: 'lotr', prompt: FILM, correct: 'The Lord of the Rings: The Fellowship of the Ring', incorrect: ['Harry Potter and the Philosopher’s Stone', 'The Hobbit: An Unexpected Journey', 'Willow'], difficulty: 'easy', kind: 'movie', query: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001 },
  { slug: 'shrek', prompt: FILM, correct: 'Shrek', incorrect: ['Shrek 2', 'Monsters, Inc.', 'Ice Age'], difficulty: 'easy', kind: 'movie', query: 'Shrek', year: 2001 },
  { slug: 'love-actually', prompt: FILM, correct: 'Love Actually', incorrect: ['Notting Hill', 'Bridget Jones’s Diary', 'Four Weddings and a Funeral'], difficulty: 'easy', kind: 'movie', query: 'Love Actually', year: 2003 },
  { slug: 'finding-nemo', prompt: FILM, correct: 'Finding Nemo', incorrect: ['Shark Tale', 'The Little Mermaid', 'Happy Feet'], difficulty: 'easy', kind: 'movie', query: 'Finding Nemo', year: 2003 },
  { slug: 'mean-girls', prompt: FILM, correct: 'Mean Girls', incorrect: ['Clueless', '10 Things I Hate About You', 'Legally Blonde'], difficulty: 'medium', kind: 'movie', query: 'Mean Girls', year: 2004 },
  { slug: 'casino-royale', prompt: FILM, correct: 'Casino Royale', incorrect: ['Skyfall', 'Quantum of Solace', 'Die Another Day'], difficulty: 'medium', kind: 'movie', query: 'Casino Royale', year: 2006 },
  { slug: 'mamma-mia', prompt: FILM, correct: 'Mamma Mia!', incorrect: ['Mamma Mia! Here We Go Again', 'Grease', 'The Greatest Showman'], difficulty: 'easy', kind: 'movie', query: 'Mamma Mia', year: 2008 },
  { slug: 'dark-knight', prompt: FILM, correct: 'The Dark Knight', incorrect: ['Batman Begins', 'Joker', 'The Batman'], difficulty: 'easy', kind: 'movie', query: 'The Dark Knight', year: 2008 },
  { slug: 'avatar', prompt: FILM, correct: 'Avatar', incorrect: ['Avatar: The Way of Water', 'Dune', 'Guardians of the Galaxy'], difficulty: 'easy', kind: 'movie', query: 'Avatar', year: 2009 },
  { slug: 'inception', prompt: FILM, correct: 'Inception', incorrect: ['The Matrix', 'Interstellar', 'Tenet'], difficulty: 'easy', kind: 'movie', query: 'Inception', year: 2010 },
  { slug: 'skyfall', prompt: FILM, correct: 'Skyfall', incorrect: ['Casino Royale', 'Spectre', 'No Time to Die'], difficulty: 'medium', kind: 'movie', query: 'Skyfall', year: 2012 },
  { slug: 'hunger-games', prompt: FILM, correct: 'The Hunger Games', incorrect: ['Divergent', 'The Maze Runner', 'Twilight'], difficulty: 'easy', kind: 'movie', query: 'The Hunger Games', year: 2012 },
  { slug: 'frozen', prompt: FILM, correct: 'Frozen', incorrect: ['Tangled', 'Brave', 'Moana'], difficulty: 'easy', kind: 'movie', query: 'Frozen', year: 2013 },
  { slug: 'guardians', prompt: FILM, correct: 'Guardians of the Galaxy', incorrect: ['Thor: Ragnarok', 'Ant-Man', 'The Avengers'], difficulty: 'easy', kind: 'movie', query: 'Guardians of the Galaxy', year: 2014 },
  { slug: 'deadpool', prompt: FILM, correct: 'Deadpool', incorrect: ['Deadpool 2', 'Logan', 'Venom'], difficulty: 'easy', kind: 'movie', query: 'Deadpool', year: 2016 },
  { slug: 'get-out', prompt: FILM, correct: 'Get Out', incorrect: ['Us', 'Nope', 'The Invisible Man'], difficulty: 'medium', kind: 'movie', query: 'Get Out', year: 2017 },
  { slug: 'paddington-2', prompt: FILM, correct: 'Paddington 2', incorrect: ['Paddington', 'Christopher Robin', 'Ted'], difficulty: 'easy', kind: 'movie', query: 'Paddington 2', year: 2017 },
  { slug: 'coco', prompt: FILM, correct: 'Coco', incorrect: ['Encanto', 'The Book of Life', 'Soul'], difficulty: 'easy', kind: 'movie', query: 'Coco', year: 2017 },
  { slug: 'black-panther', prompt: FILM, correct: 'Black Panther', incorrect: ['Black Panther: Wakanda Forever', 'Captain America: Civil War', 'Doctor Strange'], difficulty: 'easy', kind: 'movie', query: 'Black Panther', year: 2018 },
  { slug: 'joker', prompt: FILM, correct: 'Joker', incorrect: ['The Dark Knight', 'The Batman', 'Joker: Folie à Deux'], difficulty: 'medium', kind: 'movie', query: 'Joker', year: 2019 },
  { slug: 'endgame', prompt: FILM, correct: 'Avengers: Endgame', incorrect: ['Avengers: Infinity War', 'The Avengers', 'Spider-Man: No Way Home'], difficulty: 'easy', kind: 'movie', query: 'Avengers Endgame', year: 2019 },
  { slug: 'dune', prompt: FILM, correct: 'Dune', incorrect: ['Dune: Part Two', 'Star Wars', 'Avatar'], difficulty: 'medium', kind: 'movie', query: 'Dune', year: 2021 },
  { slug: 'no-way-home', prompt: FILM, correct: 'Spider-Man: No Way Home', incorrect: ['Spider-Man: Far From Home', 'Avengers: Endgame', 'The Amazing Spider-Man'], difficulty: 'easy', kind: 'movie', query: 'Spider-Man No Way Home', year: 2021 },
  { slug: 'top-gun-maverick', prompt: FILM, correct: 'Top Gun: Maverick', incorrect: ['Top Gun', 'Days of Thunder', 'Mission: Impossible – Fallout'], difficulty: 'easy', kind: 'movie', query: 'Top Gun Maverick', year: 2022 },
  { slug: 'barbie', prompt: FILM, correct: 'Barbie', incorrect: ['Barbie as The Princess and the Pauper', 'The Lego Movie', 'Wicked'], difficulty: 'easy', kind: 'movie', query: 'Barbie', year: 2023 },
  { slug: 'oppenheimer', prompt: FILM, correct: 'Oppenheimer', incorrect: ['The Imitation Game', 'Dunkirk', 'Napoleon'], difficulty: 'medium', kind: 'movie', query: 'Oppenheimer', year: 2023 },

  { slug: 'friends', prompt: SHOW, correct: 'Friends', incorrect: ['How I Met Your Mother', 'Seinfeld', 'The Big Bang Theory'], difficulty: 'easy', kind: 'tv', query: 'Friends', year: 1994 },
  { slug: 'the-office-uk', prompt: SHOW, correct: 'The Office', incorrect: ['Peep Show', 'The Inbetweeners', 'Parks and Recreation'], difficulty: 'medium', kind: 'tv', query: 'The Office', year: 2001, originCountry: 'GB' },
  { slug: 'doctor-who', prompt: SHOW, correct: 'Doctor Who', incorrect: ['Torchwood', 'Sherlock', 'Merlin'], difficulty: 'easy', kind: 'tv', query: 'Doctor Who', year: 2005 },
  { slug: 'gavin-and-stacey', prompt: SHOW, correct: 'Gavin & Stacey', incorrect: ['Gimme Gimme Gimme', 'This Country', 'The Inbetweeners'], difficulty: 'medium', kind: 'tv', query: 'Gavin & Stacey', year: 2007 },
  { slug: 'breaking-bad', prompt: SHOW, correct: 'Breaking Bad', incorrect: ['Better Call Saul', 'The Wire', 'Ozark'], difficulty: 'easy', kind: 'tv', query: 'Breaking Bad', year: 2008 },
  { slug: 'sherlock', prompt: SHOW, correct: 'Sherlock', incorrect: ['Elementary', 'Luther', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Sherlock', year: 2010 },
  { slug: 'downton', prompt: SHOW, correct: 'Downton Abbey', incorrect: ['The Crown', 'Bridgerton', 'Upstairs, Downstairs'], difficulty: 'medium', kind: 'tv', query: 'Downton Abbey', year: 2010 },
  { slug: 'game-of-thrones', prompt: SHOW, correct: 'Game of Thrones', incorrect: ['The Witcher', 'House of the Dragon', 'Vikings'], difficulty: 'easy', kind: 'tv', query: 'Game of Thrones', year: 2011 },
  { slug: 'line-of-duty', prompt: SHOW, correct: 'Line of Duty', incorrect: ['Bodyguard', 'Happy Valley', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Line of Duty', year: 2012 },
  { slug: 'peaky-blinders', prompt: SHOW, correct: 'Peaky Blinders', incorrect: ['Boardwalk Empire', 'Gangs of London', 'Taboo'], difficulty: 'medium', kind: 'tv', query: 'Peaky Blinders', year: 2013 },
  { slug: 'happy-valley', prompt: SHOW, correct: 'Happy Valley', incorrect: ['Line of Duty', 'Broadchurch', 'Scott & Bailey'], difficulty: 'hard', kind: 'tv', query: 'Happy Valley', year: 2014 },
  { slug: 'stranger-things', prompt: SHOW, correct: 'Stranger Things', incorrect: ['Dark', 'The OA', 'Wednesday'], difficulty: 'easy', kind: 'tv', query: 'Stranger Things', year: 2016 },
  { slug: 'fleabag', prompt: SHOW, correct: 'Fleabag', incorrect: ['Killing Eve', 'Catastrophe', 'I May Destroy You'], difficulty: 'medium', kind: 'tv', query: 'Fleabag', year: 2016 },
  { slug: 'the-crown', prompt: SHOW, correct: 'The Crown', incorrect: ['Downton Abbey', 'The Queen', 'Victoria'], difficulty: 'medium', kind: 'tv', query: 'The Crown', year: 2016 },
  { slug: 'succession', prompt: SHOW, correct: 'Succession', incorrect: ['Billions', 'Industry', 'The White Lotus'], difficulty: 'medium', kind: 'tv', query: 'Succession', year: 2018 },
  { slug: 'bridgerton', prompt: SHOW, correct: 'Bridgerton', incorrect: ['Downton Abbey', 'The Crown', 'Sanditon'], difficulty: 'easy', kind: 'tv', query: 'Bridgerton', year: 2020 },
  { slug: 'squid-game', prompt: SHOW, correct: 'Squid Game', incorrect: ['Alice in Borderland', 'The Traitors', 'Money Heist'], difficulty: 'easy', kind: 'tv', query: 'Squid Game', year: 2021 },
  { slug: 'wednesday', prompt: SHOW, correct: 'Wednesday', incorrect: ['Stranger Things', 'The Addams Family', 'Locke & Key'], difficulty: 'easy', kind: 'tv', query: 'Wednesday', year: 2022 },

  // Second harvest, 24 September 2026. The first 54 were played out in four
  // rounds and were 37 easy to 1 hard, so this half leans medium and hard, and
  // pairs each title with the films it is most easily mistaken for.
  { slug: 'gladiator', prompt: FILM, correct: 'Gladiator', incorrect: ['Troy', 'Kingdom of Heaven', 'Ben-Hur'], difficulty: 'medium', kind: 'movie', query: 'Gladiator', year: 2000 },
  { slug: 'notting-hill', prompt: FILM, correct: 'Notting Hill', incorrect: ['Four Weddings and a Funeral', 'Love Actually', 'About Time'], difficulty: 'medium', kind: 'movie', query: 'Notting Hill', year: 1999 },
  { slug: 'four-weddings', prompt: FILM, correct: 'Four Weddings and a Funeral', incorrect: ['Notting Hill', 'Bridget Jones’s Diary', 'About Time'], difficulty: 'hard', kind: 'movie', query: 'Four Weddings and a Funeral', year: 1994 },
  { slug: 'hot-fuzz', prompt: FILM, correct: 'Hot Fuzz', incorrect: ['Shaun of the Dead', 'The World’s End', 'Paul'], difficulty: 'medium', kind: 'movie', query: 'Hot Fuzz', year: 2007 },
  { slug: 'shaun-of-the-dead', prompt: FILM, correct: 'Shaun of the Dead', incorrect: ['Hot Fuzz', '28 Days Later', 'Zombieland'], difficulty: 'medium', kind: 'movie', query: 'Shaun of the Dead', year: 2004 },
  { slug: 'full-monty', prompt: FILM, correct: 'The Full Monty', incorrect: ['Brassed Off', 'Calendar Girls', 'Billy Elliot'], difficulty: 'hard', kind: 'movie', query: 'The Full Monty', year: 1997 },
  { slug: 'billy-elliot', prompt: FILM, correct: 'Billy Elliot', incorrect: ['Brassed Off', 'Pride', 'The Full Monty'], difficulty: 'hard', kind: 'movie', query: 'Billy Elliot', year: 2000 },
  { slug: 'trainspotting', prompt: FILM, correct: 'Trainspotting', incorrect: ['Human Traffic', 'Lock, Stock and Two Smoking Barrels', 'Shallow Grave'], difficulty: 'medium', kind: 'movie', query: 'Trainspotting', year: 1996 },
  { slug: 'lock-stock', prompt: FILM, correct: 'Lock, Stock and Two Smoking Barrels', incorrect: ['Snatch', 'Layer Cake', 'RocknRolla'], difficulty: 'hard', kind: 'movie', query: 'Lock, Stock and Two Smoking Barrels', year: 1998 },
  { slug: 'snatch', prompt: FILM, correct: 'Snatch', incorrect: ['Lock, Stock and Two Smoking Barrels', 'The Gentlemen', 'RocknRolla'], difficulty: 'medium', kind: 'movie', query: 'Snatch', year: 2000 },
  { slug: 'pulp-fiction', prompt: FILM, correct: 'Pulp Fiction', incorrect: ['Reservoir Dogs', 'Jackie Brown', 'True Romance'], difficulty: 'medium', kind: 'movie', query: 'Pulp Fiction', year: 1994 },
  { slug: 'forrest-gump', prompt: FILM, correct: 'Forrest Gump', incorrect: ['Big', 'Cast Away', 'The Green Mile'], difficulty: 'easy', kind: 'movie', query: 'Forrest Gump', year: 1994 },
  { slug: 'shawshank', prompt: FILM, correct: 'The Shawshank Redemption', incorrect: ['The Green Mile', 'Escape from Alcatraz', 'The Great Escape'], difficulty: 'medium', kind: 'movie', query: 'The Shawshank Redemption', year: 1994 },
  { slug: 'pretty-woman', prompt: FILM, correct: 'Pretty Woman', incorrect: ['Runaway Bride', 'Notting Hill', 'Maid in Manhattan'], difficulty: 'medium', kind: 'movie', query: 'Pretty Woman', year: 1990 },
  { slug: 'mrs-doubtfire', prompt: FILM, correct: 'Mrs. Doubtfire', incorrect: ['Tootsie', 'Hook', 'Jumanji'], difficulty: 'medium', kind: 'movie', query: 'Mrs. Doubtfire', year: 1993 },
  { slug: 'men-in-black', prompt: FILM, correct: 'Men in Black', incorrect: ['Independence Day', 'Galaxy Quest', 'Ghostbusters'], difficulty: 'medium', kind: 'movie', query: 'Men in Black', year: 1997 },
  { slug: 'independence-day', prompt: FILM, correct: 'Independence Day', incorrect: ['Armageddon', 'Men in Black', 'War of the Worlds'], difficulty: 'medium', kind: 'movie', query: 'Independence Day', year: 1996 },
  { slug: 'saving-private-ryan', prompt: FILM, correct: 'Saving Private Ryan', incorrect: ['Dunkirk', 'Fury', 'Black Hawk Down'], difficulty: 'medium', kind: 'movie', query: 'Saving Private Ryan', year: 1998 },
  { slug: 'film-1917', prompt: FILM, correct: '1917', incorrect: ['Dunkirk', 'Saving Private Ryan', 'All Quiet on the Western Front'], difficulty: 'hard', kind: 'movie', query: '1917', year: 2019 },
  { slug: 'dunkirk', prompt: FILM, correct: 'Dunkirk', incorrect: ['1917', 'Darkest Hour', 'Atonement'], difficulty: 'hard', kind: 'movie', query: 'Dunkirk', year: 2017 },
  { slug: 'devil-wears-prada', prompt: FILM, correct: 'The Devil Wears Prada', incorrect: ['The Intern', 'Legally Blonde', 'Confessions of a Shopaholic'], difficulty: 'medium', kind: 'movie', query: 'The Devil Wears Prada', year: 2006 },
  { slug: 'pirates-caribbean', prompt: FILM, correct: 'Pirates of the Caribbean: The Curse of the Black Pearl', incorrect: ['Hook', 'Master and Commander: The Far Side of the World', 'Treasure Planet'], difficulty: 'easy', kind: 'movie', query: 'Pirates of the Caribbean: The Curse of the Black Pearl', year: 2003 },
  { slug: 'gravity', prompt: FILM, correct: 'Gravity', incorrect: ['Interstellar', 'The Martian', 'Apollo 13'], difficulty: 'medium', kind: 'movie', query: 'Gravity', year: 2013 },
  { slug: 'interstellar', prompt: FILM, correct: 'Interstellar', incorrect: ['Gravity', 'The Martian', 'Arrival'], difficulty: 'medium', kind: 'movie', query: 'Interstellar', year: 2014 },
  { slug: 'the-martian', prompt: FILM, correct: 'The Martian', incorrect: ['Gravity', 'Interstellar', 'Moon'], difficulty: 'medium', kind: 'movie', query: 'The Martian', year: 2015 },
  { slug: 'la-la-land', prompt: FILM, correct: 'La La Land', incorrect: ['The Greatest Showman', 'Whiplash', 'A Star Is Born'], difficulty: 'medium', kind: 'movie', query: 'La La Land', year: 2016 },
  { slug: 'greatest-showman', prompt: FILM, correct: 'The Greatest Showman', incorrect: ['La La Land', 'Moulin Rouge!', 'Chicago'], difficulty: 'medium', kind: 'movie', query: 'The Greatest Showman', year: 2017 },
  { slug: 'bohemian-rhapsody-film', prompt: FILM, correct: 'Bohemian Rhapsody', incorrect: ['Rocketman', 'Elvis', 'Walk the Line'], difficulty: 'medium', kind: 'movie', query: 'Bohemian Rhapsody', year: 2018 },
  { slug: 'mad-max-fury-road', prompt: FILM, correct: 'Mad Max: Fury Road', incorrect: ['Waterworld', 'The Book of Eli', 'Dredd'], difficulty: 'medium', kind: 'movie', query: 'Mad Max: Fury Road', year: 2015 },
  { slug: 'parasite', prompt: FILM, correct: 'Parasite', incorrect: ['Oldboy', 'Shoplifters', 'Burning'], difficulty: 'hard', kind: 'movie', query: 'Parasite', year: 2019 },
  { slug: 'everything-everywhere', prompt: FILM, correct: 'Everything Everywhere All at Once', incorrect: ['Crouching Tiger, Hidden Dragon', 'Shang-Chi and the Legend of the Ten Rings', 'The Farewell'], difficulty: 'hard', kind: 'movie', query: 'Everything Everywhere All at Once', year: 2022 },
  { slug: 'knives-out', prompt: FILM, correct: 'Knives Out', incorrect: ['Glass Onion: A Knives Out Mystery', 'Murder on the Orient Express', 'Death on the Nile'], difficulty: 'medium', kind: 'movie', query: 'Knives Out', year: 2019 },
  { slug: 'wicked', prompt: FILM, correct: 'Wicked', incorrect: ['The Wizard of Oz', 'Into the Woods', 'Enchanted'], difficulty: 'medium', kind: 'movie', query: 'Wicked', year: 2024 },
  { slug: 'inside-out', prompt: FILM, correct: 'Inside Out', incorrect: ['Soul', 'Up', 'Elemental'], difficulty: 'medium', kind: 'movie', query: 'Inside Out', year: 2015 },
  { slug: 'up', prompt: FILM, correct: 'Up', incorrect: ['Ratatouille', 'WALL·E', 'Inside Out'], difficulty: 'easy', kind: 'movie', query: 'Up', year: 2009 },
  { slug: 'the-incredibles', prompt: FILM, correct: 'The Incredibles', incorrect: ['Megamind', 'Despicable Me', 'Big Hero 6'], difficulty: 'medium', kind: 'movie', query: 'The Incredibles', year: 2004 },
  { slug: 'despicable-me', prompt: FILM, correct: 'Despicable Me', incorrect: ['Megamind', 'The Incredibles', 'Madagascar'], difficulty: 'easy', kind: 'movie', query: 'Despicable Me', year: 2010 },
  { slug: 'were-rabbit', prompt: FILM, correct: 'Wallace & Gromit: The Curse of the Were-Rabbit', incorrect: ['Chicken Run', 'Flushed Away', 'Shaun the Sheep Movie'], difficulty: 'medium', kind: 'movie', query: 'Wallace & Gromit: The Curse of the Were-Rabbit', year: 2005 },
  { slug: 'chicken-run', prompt: FILM, correct: 'Chicken Run', incorrect: ['Wallace & Gromit: The Curse of the Were-Rabbit', 'Flushed Away', 'Shaun the Sheep Movie'], difficulty: 'medium', kind: 'movie', query: 'Chicken Run', year: 2000 },
  { slug: 'slumdog-millionaire', prompt: FILM, correct: 'Slumdog Millionaire', incorrect: ['Life of Pi', 'Lion', 'The Best Exotic Marigold Hotel'], difficulty: 'medium', kind: 'movie', query: 'Slumdog Millionaire', year: 2008 },
  { slug: 'kings-speech', prompt: FILM, correct: 'The King’s Speech', incorrect: ['Darkest Hour', 'The Queen', 'Mrs Brown'], difficulty: 'hard', kind: 'movie', query: 'The King\'s Speech', year: 2010 },
  { slug: 'darkest-hour', prompt: FILM, correct: 'Darkest Hour', incorrect: ['The King’s Speech', 'Dunkirk', 'The Imitation Game'], difficulty: 'hard', kind: 'movie', query: 'Darkest Hour', year: 2017 },
  { slug: 'imitation-game', prompt: FILM, correct: 'The Imitation Game', incorrect: ['The Theory of Everything', 'Enigma', 'A Beautiful Mind'], difficulty: 'hard', kind: 'movie', query: 'The Imitation Game', year: 2014 },
  { slug: 'theory-of-everything', prompt: FILM, correct: 'The Theory of Everything', incorrect: ['The Imitation Game', 'A Beautiful Mind', 'Good Will Hunting'], difficulty: 'hard', kind: 'movie', query: 'The Theory of Everything', year: 2014 },
  { slug: 'kingsman', prompt: FILM, correct: 'Kingsman: The Secret Service', incorrect: ['The Man from U.N.C.L.E.', 'Johnny English', 'Spectre'], difficulty: 'medium', kind: 'movie', query: 'Kingsman: The Secret Service', year: 2014 },
  { slug: 'johnny-english', prompt: FILM, correct: 'Johnny English', incorrect: ['Mr. Bean’s Holiday', 'Kingsman: The Secret Service', 'Austin Powers: International Man of Mystery'], difficulty: 'hard', kind: 'movie', query: 'Johnny English', year: 2003 },
  { slug: 'mr-beans-holiday', prompt: FILM, correct: 'Mr. Bean’s Holiday', incorrect: ['Johnny English', 'Bean', 'Hot Fuzz'], difficulty: 'medium', kind: 'movie', query: 'Mr. Bean\'s Holiday', year: 2007 },
  { slug: 'gone-girl', prompt: FILM, correct: 'Gone Girl', incorrect: ['The Girl on the Train', 'Prisoners', 'Zodiac'], difficulty: 'hard', kind: 'movie', query: 'Gone Girl', year: 2014 },
  { slug: 'social-network', prompt: FILM, correct: 'The Social Network', incorrect: ['The Big Short', 'Steve Jobs', 'Moneyball'], difficulty: 'hard', kind: 'movie', query: 'The Social Network', year: 2010 },
  { slug: 'wolf-of-wall-street', prompt: FILM, correct: 'The Wolf of Wall Street', incorrect: ['The Big Short', 'Wall Street', 'Catch Me If You Can'], difficulty: 'medium', kind: 'movie', query: 'The Wolf of Wall Street', year: 2013 },
  { slug: 'catch-me-if-you-can', prompt: FILM, correct: 'Catch Me If You Can', incorrect: ['The Wolf of Wall Street', 'The Talented Mr. Ripley', 'Ocean’s Eleven'], difficulty: 'hard', kind: 'movie', query: 'Catch Me If You Can', year: 2002 },
  { slug: 'oceans-eleven', prompt: FILM, correct: 'Ocean’s Eleven', incorrect: ['The Italian Job', 'Now You See Me', 'Ocean’s Twelve'], difficulty: 'medium', kind: 'movie', query: 'Ocean\'s Eleven', year: 2001 },
  { slug: 'elf', prompt: FILM, correct: 'Elf', incorrect: ['Home Alone', 'The Santa Clause', 'Jingle All the Way'], difficulty: 'easy', kind: 'movie', query: 'Elf', year: 2003 },
  { slug: 'the-holiday', prompt: FILM, correct: 'The Holiday', incorrect: ['Love Actually', 'The Family Stone', 'Last Christmas'], difficulty: 'hard', kind: 'movie', query: 'The Holiday', year: 2006 },
  { slug: 'about-time', prompt: FILM, correct: 'About Time', incorrect: ['Notting Hill', 'Love Actually', 'The Time Traveler’s Wife'], difficulty: 'hard', kind: 'movie', query: 'About Time', year: 2013 },
  { slug: 'legally-blonde', prompt: FILM, correct: 'Legally Blonde', incorrect: ['Clueless', 'Mean Girls', 'The Devil Wears Prada'], difficulty: 'medium', kind: 'movie', query: 'Legally Blonde', year: 2001 },
  { slug: 'clueless', prompt: FILM, correct: 'Clueless', incorrect: ['Mean Girls', 'Legally Blonde', '10 Things I Hate About You'], difficulty: 'medium', kind: 'movie', query: 'Clueless', year: 1995 },
  { slug: 'pitch-perfect', prompt: FILM, correct: 'Pitch Perfect', incorrect: ['Bring It On', 'Step Up', 'High School Musical'], difficulty: 'medium', kind: 'movie', query: 'Pitch Perfect', year: 2012 },
  { slug: 'fast-and-furious', prompt: FILM, correct: 'The Fast and the Furious', incorrect: ['Gone in 60 Seconds', 'Need for Speed', 'Drive'], difficulty: 'medium', kind: 'movie', query: 'The Fast and the Furious', year: 2001 },
  { slug: 'john-wick', prompt: FILM, correct: 'John Wick', incorrect: ['The Equalizer', 'Taken', 'Nobody'], difficulty: 'medium', kind: 'movie', query: 'John Wick', year: 2014 },
  { slug: 'braveheart', prompt: FILM, correct: 'Braveheart', incorrect: ['Rob Roy', 'Gladiator', 'Outlaw King'], difficulty: 'medium', kind: 'movie', query: 'Braveheart', year: 1995 },
  { slug: 'moana', prompt: FILM, correct: 'Moana', incorrect: ['Frozen', 'Tangled', 'Encanto'], difficulty: 'easy', kind: 'movie', query: 'Moana', year: 2016 },
  { slug: 'encanto', prompt: FILM, correct: 'Encanto', incorrect: ['Coco', 'Moana', 'Luca'], difficulty: 'medium', kind: 'movie', query: 'Encanto', year: 2021 },
  { slug: 'tangled', prompt: FILM, correct: 'Tangled', incorrect: ['Frozen', 'Brave', 'Enchanted'], difficulty: 'medium', kind: 'movie', query: 'Tangled', year: 2010 },
  { slug: 'aladdin', prompt: FILM, correct: 'Aladdin', incorrect: ['Hercules', 'The Jungle Book', 'Sinbad: Legend of the Seven Seas'], difficulty: 'easy', kind: 'movie', query: 'Aladdin', year: 1992 },
  { slug: 'beauty-and-the-beast', prompt: FILM, correct: 'Beauty and the Beast', incorrect: ['The Little Mermaid', 'Cinderella', 'Aladdin'], difficulty: 'medium', kind: 'movie', query: 'Beauty and the Beast', year: 1991 },
  { slug: 'poor-things', prompt: FILM, correct: 'Poor Things', incorrect: ['The Favourite', 'The Shape of Water', 'Edward Scissorhands'], difficulty: 'hard', kind: 'movie', query: 'Poor Things', year: 2023 },
  { slug: 'saltburn', prompt: FILM, correct: 'Saltburn', incorrect: ['The Talented Mr. Ripley', 'Brideshead Revisited', 'Promising Young Woman'], difficulty: 'hard', kind: 'movie', query: 'Saltburn', year: 2023 },
  { slug: 'bend-it-like-beckham', prompt: FILM, correct: 'Bend It Like Beckham', incorrect: ['Goal!', 'Fever Pitch', 'Bhaji on the Beach'], difficulty: 'medium', kind: 'movie', query: 'Bend It Like Beckham', year: 2002 },
  { slug: 'inbetweeners-movie', prompt: FILM, correct: 'The Inbetweeners Movie', incorrect: ['Kevin & Perry Go Large', 'Superbad', 'Project X'], difficulty: 'medium', kind: 'movie', query: 'The Inbetweeners Movie', year: 2011 },
  { slug: 'die-hard', prompt: FILM, correct: 'Die Hard', incorrect: ['Lethal Weapon', 'Speed', 'Under Siege'], difficulty: 'medium', kind: 'movie', query: 'Die Hard', year: 1988 },
  { slug: 'only-fools', prompt: SHOW, correct: 'Only Fools and Horses', incorrect: ['Open All Hours', 'Minder', 'Still Game'], difficulty: 'easy', kind: 'tv', query: 'Only Fools and Horses', year: 1981, originCountry: 'GB' },
  { slug: 'fawlty-towers', prompt: SHOW, correct: 'Fawlty Towers', incorrect: ['Hi-de-Hi!', 'Are You Being Served?', 'The Good Life'], difficulty: 'medium', kind: 'tv', query: 'Fawlty Towers', year: 1975, originCountry: 'GB' },
  { slug: 'mr-bean', prompt: SHOW, correct: 'Mr. Bean', incorrect: ['The Thin Blue Line', 'Only Fools and Horses', 'Blackadder'], difficulty: 'easy', kind: 'tv', query: 'Mr. Bean', year: 1990 },
  { slug: 'fresh-prince', prompt: SHOW, correct: 'The Fresh Prince of Bel-Air', incorrect: ['Family Matters', 'Everybody Hates Chris', 'Saved by the Bell'], difficulty: 'easy', kind: 'tv', query: 'The Fresh Prince of Bel-Air', year: 1990 },
  { slug: 'inbetweeners', prompt: SHOW, correct: 'The Inbetweeners', incorrect: ['Skins', 'Friday Night Dinner', 'Bad Education'], difficulty: 'medium', kind: 'tv', query: 'The Inbetweeners', year: 2008, originCountry: 'GB' },
  { slug: 'peep-show', prompt: SHOW, correct: 'Peep Show', incorrect: ['The IT Crowd', 'Green Wing', 'Spaced'], difficulty: 'medium', kind: 'tv', query: 'Peep Show', year: 2003, originCountry: 'GB' },
  { slug: 'it-crowd', prompt: SHOW, correct: 'The IT Crowd', incorrect: ['Black Books', 'Peep Show', 'Silicon Valley'], difficulty: 'medium', kind: 'tv', query: 'The IT Crowd', year: 2006, originCountry: 'GB' },
  { slug: 'strictly', prompt: SHOW, correct: 'Strictly Come Dancing', incorrect: ['Dancing on Ice', 'The X Factor', 'Britain’s Got Talent'], difficulty: 'easy', kind: 'tv', query: 'Strictly Come Dancing', year: 2004 },
  { slug: 'bake-off', prompt: SHOW, correct: 'The Great British Bake Off', incorrect: ['MasterChef', 'The Great Pottery Throw Down', 'Kitchen Nightmares'], difficulty: 'easy', kind: 'tv', query: 'The Great British Bake Off', year: 2010 },
  { slug: 'top-gear', prompt: SHOW, correct: 'Top Gear', incorrect: ['The Grand Tour', 'Fifth Gear', 'Wheeler Dealers'], difficulty: 'easy', kind: 'tv', query: 'Top Gear', year: 2002, originCountry: 'GB' },
  { slug: 'the-traitors', prompt: SHOW, correct: 'The Traitors', incorrect: ['The Mole', 'Survivor', 'Race Across the World'], difficulty: 'medium', kind: 'tv', query: 'The Traitors', year: 2022, originCountry: 'GB' },
  { slug: 'love-island', prompt: SHOW, correct: 'Love Island', incorrect: ['Big Brother', 'The Only Way Is Essex', 'Too Hot to Handle'], difficulty: 'easy', kind: 'tv', query: 'Love Island', year: 2015, originCountry: 'GB' },
  { slug: 'gogglebox', prompt: SHOW, correct: 'Gogglebox', incorrect: ['The Royle Family', 'Married at First Sight', 'Big Brother'], difficulty: 'medium', kind: 'tv', query: 'Gogglebox', year: 2013, originCountry: 'GB' },
  { slug: 'royle-family', prompt: SHOW, correct: 'The Royle Family', incorrect: ['Gogglebox', 'Early Doors', 'Mrs Brown’s Boys'], difficulty: 'hard', kind: 'tv', query: 'The Royle Family', year: 1998 },
  { slug: 'father-ted', prompt: SHOW, correct: 'Father Ted', incorrect: ['Derry Girls', 'The Vicar of Dibley', 'Black Books'], difficulty: 'medium', kind: 'tv', query: 'Father Ted', year: 1995 },
  { slug: 'derry-girls', prompt: SHOW, correct: 'Derry Girls', incorrect: ['Father Ted', 'The Young Offenders', 'Sex Education'], difficulty: 'medium', kind: 'tv', query: 'Derry Girls', year: 2018 },
  { slug: 'vicar-of-dibley', prompt: SHOW, correct: 'The Vicar of Dibley', incorrect: ['Father Ted', 'Rev.', 'Keeping Up Appearances'], difficulty: 'medium', kind: 'tv', query: 'The Vicar of Dibley', year: 1994 },
  { slug: 'sex-education', prompt: SHOW, correct: 'Sex Education', incorrect: ['Heartstopper', 'Skins', 'The Inbetweeners'], difficulty: 'medium', kind: 'tv', query: 'Sex Education', year: 2019 },
  { slug: 'normal-people', prompt: SHOW, correct: 'Normal People', incorrect: ['Conversations with Friends', 'Heartstopper', 'One Day'], difficulty: 'hard', kind: 'tv', query: 'Normal People', year: 2020 },
  { slug: 'bodyguard', prompt: SHOW, correct: 'Bodyguard', incorrect: ['Line of Duty', 'The Night Manager', 'Vigil'], difficulty: 'medium', kind: 'tv', query: 'Bodyguard', year: 2018, originCountry: 'GB' },
  { slug: 'night-manager', prompt: SHOW, correct: 'The Night Manager', incorrect: ['Bodyguard', 'The Little Drummer Girl', 'Killing Eve'], difficulty: 'hard', kind: 'tv', query: 'The Night Manager', year: 2016 },
  { slug: 'killing-eve', prompt: SHOW, correct: 'Killing Eve', incorrect: ['The Night Manager', 'Luther', 'Slow Horses'], difficulty: 'medium', kind: 'tv', query: 'Killing Eve', year: 2018 },
  { slug: 'luther', prompt: SHOW, correct: 'Luther', incorrect: ['Line of Duty', 'Bodyguard', 'Top Boy'], difficulty: 'medium', kind: 'tv', query: 'Luther', year: 2010 },
  { slug: 'slow-horses', prompt: SHOW, correct: 'Slow Horses', incorrect: ['The Night Manager', 'Spooks', 'Killing Eve'], difficulty: 'hard', kind: 'tv', query: 'Slow Horses', year: 2022 },
  { slug: 'broadchurch', prompt: SHOW, correct: 'Broadchurch', incorrect: ['Happy Valley', 'Line of Duty', 'Shetland'], difficulty: 'medium', kind: 'tv', query: 'Broadchurch', year: 2013 },
  { slug: 'call-the-midwife', prompt: SHOW, correct: 'Call the Midwife', incorrect: ['Downton Abbey', 'All Creatures Great and Small', 'Heartbeat'], difficulty: 'medium', kind: 'tv', query: 'Call the Midwife', year: 2012 },
  { slug: 'death-in-paradise', prompt: SHOW, correct: 'Death in Paradise', incorrect: ['Midsomer Murders', 'Doc Martin', 'Bergerac'], difficulty: 'medium', kind: 'tv', query: 'Death in Paradise', year: 2011 },
  { slug: 'midsomer', prompt: SHOW, correct: 'Midsomer Murders', incorrect: ['Death in Paradise', 'Inspector Morse', 'Vera'], difficulty: 'hard', kind: 'tv', query: 'Midsomer Murders', year: 1997 },
  { slug: 'vera', prompt: SHOW, correct: 'Vera', incorrect: ['Shetland', 'Midsomer Murders', 'Scott & Bailey'], difficulty: 'hard', kind: 'tv', query: 'Vera', year: 2011, originCountry: 'GB' },
  { slug: 'walking-dead', prompt: SHOW, correct: 'The Walking Dead', incorrect: ['The Last of Us', 'Z Nation', 'Fear the Walking Dead'], difficulty: 'easy', kind: 'tv', query: 'The Walking Dead', year: 2010 },
  { slug: 'last-of-us', prompt: SHOW, correct: 'The Last of Us', incorrect: ['The Walking Dead', 'Station Eleven', 'The Rain'], difficulty: 'medium', kind: 'tv', query: 'The Last of Us', year: 2023 },
  { slug: 'mandalorian', prompt: SHOW, correct: 'The Mandalorian', incorrect: ['Andor', 'The Book of Boba Fett', 'Obi-Wan Kenobi'], difficulty: 'medium', kind: 'tv', query: 'The Mandalorian', year: 2019 },
  { slug: 'the-boys', prompt: SHOW, correct: 'The Boys', incorrect: ['Invincible', 'Gen V', 'Watchmen'], difficulty: 'medium', kind: 'tv', query: 'The Boys', year: 2019 },
  { slug: 'family-guy', prompt: SHOW, correct: 'Family Guy', incorrect: ['American Dad!', 'The Simpsons', 'Bob’s Burgers'], difficulty: 'easy', kind: 'tv', query: 'Family Guy', year: 1999 },
  { slug: 'big-bang-theory', prompt: SHOW, correct: 'The Big Bang Theory', incorrect: ['Young Sheldon', 'How I Met Your Mother', 'The IT Crowd'], difficulty: 'easy', kind: 'tv', query: 'The Big Bang Theory', year: 2007 },
  { slug: 'himym', prompt: SHOW, correct: 'How I Met Your Mother', incorrect: ['Friends', 'The Big Bang Theory', 'New Girl'], difficulty: 'medium', kind: 'tv', query: 'How I Met Your Mother', year: 2005 },
  { slug: 'modern-family', prompt: SHOW, correct: 'Modern Family', incorrect: ['Arrested Development', 'The Middle', 'Parenthood'], difficulty: 'medium', kind: 'tv', query: 'Modern Family', year: 2009 },
  { slug: 'brooklyn-99', prompt: SHOW, correct: 'Brooklyn Nine-Nine', incorrect: ['Parks and Recreation', 'Superstore', 'Reno 911!'], difficulty: 'medium', kind: 'tv', query: 'Brooklyn Nine-Nine', year: 2013 },
  { slug: 'ted-lasso', prompt: SHOW, correct: 'Ted Lasso', incorrect: ['Mike Bassett: England Manager', 'Sunderland ’Til I Die', 'Welcome to Wrexham'], difficulty: 'medium', kind: 'tv', query: 'Ted Lasso', year: 2020 },
  { slug: 'white-lotus', prompt: SHOW, correct: 'The White Lotus', incorrect: ['Nine Perfect Strangers', 'Big Little Lies', 'Industry'], difficulty: 'medium', kind: 'tv', query: 'The White Lotus', year: 2021 },
  { slug: 'sopranos', prompt: SHOW, correct: 'The Sopranos', incorrect: ['Boardwalk Empire', 'The Wire', 'Gomorrah'], difficulty: 'medium', kind: 'tv', query: 'The Sopranos', year: 1999 },
  { slug: 'the-wire', prompt: SHOW, correct: 'The Wire', incorrect: ['The Sopranos', 'Oz', 'Top Boy'], difficulty: 'hard', kind: 'tv', query: 'The Wire', year: 2002 },
  { slug: 'mad-men', prompt: SHOW, correct: 'Mad Men', incorrect: ['Boardwalk Empire', 'Suits', 'Masters of Sex'], difficulty: 'hard', kind: 'tv', query: 'Mad Men', year: 2007 },
  { slug: 'suits', prompt: SHOW, correct: 'Suits', incorrect: ['The Good Wife', 'Billions', 'Silk'], difficulty: 'medium', kind: 'tv', query: 'Suits', year: 2011 },
  { slug: 'greys-anatomy', prompt: SHOW, correct: 'Grey’s Anatomy', incorrect: ['ER', 'Chicago Med', 'Scrubs'], difficulty: 'medium', kind: 'tv', query: 'Grey\'s Anatomy', year: 2005 },
  { slug: 'ghosts-bbc', prompt: SHOW, correct: 'Ghosts', incorrect: ['Being Human', 'The League of Gentlemen', 'Inside No. 9'], difficulty: 'medium', kind: 'tv', query: 'Ghosts', year: 2019, originCountry: 'GB' },
  { slug: 'inside-no-9', prompt: SHOW, correct: 'Inside No. 9', incorrect: ['The League of Gentlemen', 'Black Mirror', 'Psychoville'], difficulty: 'hard', kind: 'tv', query: 'Inside No. 9', year: 2014 },
  { slug: 'black-mirror', prompt: SHOW, correct: 'Black Mirror', incorrect: ['Inside No. 9', 'The Twilight Zone', 'Years and Years'], difficulty: 'medium', kind: 'tv', query: 'Black Mirror', year: 2011 },
  { slug: 'taskmaster', prompt: SHOW, correct: 'Taskmaster', incorrect: ['Would I Lie to You?', '8 Out of 10 Cats Does Countdown', 'QI'], difficulty: 'medium', kind: 'tv', query: 'Taskmaster', year: 2015, originCountry: 'GB' },
  { slug: 'apprentice-uk', prompt: SHOW, correct: 'The Apprentice', incorrect: ['Dragons’ Den', 'Undercover Boss', 'Secret Millionaire'], difficulty: 'medium', kind: 'tv', query: 'The Apprentice', year: 2005, originCountry: 'GB' },
  { slug: 'dragons-den', prompt: SHOW, correct: 'Dragons’ Den', incorrect: ['The Apprentice', 'Shark Tank', 'Undercover Boss'], difficulty: 'hard', kind: 'tv', query: 'Dragons\' Den', year: 2005, originCountry: 'GB' },
  { slug: 'shameless-uk', prompt: SHOW, correct: 'Shameless', incorrect: ['Benidorm', 'The Royle Family', 'This Is England ’86'], difficulty: 'medium', kind: 'tv', query: 'Shameless', year: 2004, originCountry: 'GB' },
  { slug: 'friday-night-dinner', prompt: SHOW, correct: 'Friday Night Dinner', incorrect: ['Outnumbered', 'The Inbetweeners', 'Not Going Out'], difficulty: 'medium', kind: 'tv', query: 'Friday Night Dinner', year: 2011 },
  { slug: 'outnumbered', prompt: SHOW, correct: 'Outnumbered', incorrect: ['Motherland', 'My Family', 'Not Going Out'], difficulty: 'hard', kind: 'tv', query: 'Outnumbered', year: 2007, originCountry: 'GB' },
  { slug: 'baby-reindeer', prompt: SHOW, correct: 'Baby Reindeer', incorrect: ['I May Destroy You', 'Adolescence', 'Eric'], difficulty: 'hard', kind: 'tv', query: 'Baby Reindeer', year: 2024 },
  { slug: 'adolescence', prompt: SHOW, correct: 'Adolescence', incorrect: ['Baby Reindeer', 'Mr Bates vs The Post Office', 'Broadchurch'], difficulty: 'medium', kind: 'tv', query: 'Adolescence', year: 2025 },
  { slug: 'severance', prompt: SHOW, correct: 'Severance', incorrect: ['Black Mirror', 'Silo', 'Mr. Robot'], difficulty: 'medium', kind: 'tv', query: 'Severance', year: 2022 },
  { slug: 'the-bear', prompt: SHOW, correct: 'The Bear', incorrect: ['Boiling Point', 'Hell’s Kitchen', 'Kitchen Confidential'], difficulty: 'medium', kind: 'tv', query: 'The Bear', year: 2022 },
  { slug: 'house-of-the-dragon', prompt: SHOW, correct: 'House of the Dragon', incorrect: ['Game of Thrones', 'The Witcher', 'Vikings'], difficulty: 'medium', kind: 'tv', query: 'House of the Dragon', year: 2022 },
  { slug: 'the-witcher', prompt: SHOW, correct: 'The Witcher', incorrect: ['House of the Dragon', 'Game of Thrones', 'Shadow and Bone'], difficulty: 'medium', kind: 'tv', query: 'The Witcher', year: 2019 },
  { slug: 'band-of-brothers', prompt: SHOW, correct: 'Band of Brothers', incorrect: ['The Pacific', 'Masters of the Air', 'Generation Kill'], difficulty: 'hard', kind: 'tv', query: 'Band of Brothers', year: 2001 },
  { slug: 'chernobyl', prompt: SHOW, correct: 'Chernobyl', incorrect: ['The Salisbury Poisonings', 'Years and Years', 'The Terror'], difficulty: 'hard', kind: 'tv', query: 'Chernobyl', year: 2019 },
];
